import type { Star } from '../../types';

/**
 * Grade 3 reading comprehension.
 *
 * Passages run 150–260 words and lean on inference, author's purpose, and
 * vocabulary-in-context rather than literal recall. A mix of narrative,
 * informational, and biographical text, because third grade is where the
 * difference between those starts to matter.
 */

export const grade3Reading: Star[] = [
  {
    id: 'g3_read_01',
    subject: 'reading',
    grade: 3,
    title: 'The Girl Who Counted Stars',
    blurb: 'A true story about someone who did the maths that put people on the moon.',
    minutes: 14,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Girl Who Counted Stars',
        preview: [
          { word: 'trajectory', meaning: 'the curved path a moving object follows' },
          { word: 'segregated', meaning: 'kept apart by unfair rules, usually by race' },
        ],
        paragraphs: [
          'Katherine Johnson counted everything. Steps to the road. Plates on the table. Stars, when she could not sleep.',
          'She finished high school at fourteen and college at eighteen. But when she began looking for work in the 1950s, the doors that were open to her were narrow. She was Black, and she was a woman, and America was segregated. The building where she eventually worked had separate bathrooms and a separate table in the lunchroom for people who looked like her.',
          'Her job title was "computer." Before machines took the name, a computer was a person who did calculations by hand.',
          'Katherine calculated trajectories — the exact curved paths spacecraft would travel. Get the numbers wrong and an astronaut misses Earth entirely and drifts into space forever.',
          'In 1962, NASA had electronic computers for the first time. But John Glenn did not trust them. Before he agreed to fly, he asked engineers to have Katherine check the machine\'s numbers by hand.',
          '"If she says they\'re good," he said, "then I\'m ready to go."',
          'She checked. They were good. He flew.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_01_c1',
          prompt: 'In this passage, what did the word "computer" originally mean?',
          options: [
            'An electronic machine',
            'A person who does calculations by hand',
            'A kind of telescope',
            'A job at a bank',
          ],
          correct: 1,
          teach: 'A person. The passage tells us the machines took the name later.',
        },
        {
          kind: 'choice',
          id: 'g3_read_01_c2',
          prompt: 'Why did John Glenn ask Katherine to check the machine\'s numbers?',
          options: [
            'The machine was broken',
            'He did not trust the electronic computers yet',
            'Katherine was faster than the machine',
            'It was a NASA rule',
          ],
          correct: 1,
          teach: 'He did not trust them. They were brand new, and his life depended on the answer.',
        },
        {
          kind: 'speak',
          id: 'g3_read_01_s1',
          prompt: 'Why do you think the author starts by telling us Katherine counted steps, plates, and stars?',
          accept: [
            'she loved numbers', 'she always liked counting', 'to show she loved math',
            'she was good at numbers', 'to show she liked numbers from the start',
            'she was born loving numbers', 'it shows what she was like',
          ],
          sampleAnswer: 'To show she loved numbers even as a child, long before it was her job.',
          hint: 'What does that detail tell you about who she was?',
          teach: 'Right. It shows the maths was part of her from the beginning, not just a job she took.',
        },
        {
          kind: 'choice',
          id: 'g3_read_01_c3',
          prompt: 'What does "segregated" mean in this passage?',
          options: [
            'Very large and busy',
            'Kept apart by unfair rules',
            'Newly built',
            'Owned by the government',
          ],
          correct: 1,
          teach: 'Kept apart by unfair rules. The separate bathrooms and lunch table are the evidence.',
        },
        {
          kind: 'speak',
          id: 'g3_read_01_s2',
          prompt: 'What would happen if a trajectory calculation was wrong?',
          accept: [
            'the astronaut would miss earth', 'they would drift into space',
            'he would be lost in space', 'miss earth', 'lost forever',
            'the astronaut would be lost', 'drift into space',
          ],
          sampleAnswer: 'The astronaut would miss Earth and drift into space forever.',
          teach: 'Exactly. That is why Glenn wanted a human he trusted to check.',
        },
        {
          kind: 'choice',
          id: 'g3_read_01_c4',
          prompt: 'What is the main idea of this passage?',
          options: [
            'Electronic computers were invented in 1962',
            'Katherine\'s skill was trusted with astronauts\' lives, despite unfair barriers',
            'John Glenn was a nervous pilot',
            'Counting is a useful hobby',
          ],
          correct: 1,
          teach: 'That is the thread running through the whole piece — barriers on one side, undeniable skill on the other.',
        },
        {
          kind: 'speak',
          id: 'g3_read_01_s3',
          prompt: 'The passage ends with three very short sentences. Why do you think the author wrote it that way?',
          accept: [
            'to make it strong', 'it sounds important', 'to make it feel big',
            'for effect', 'to slow it down', 'to make you notice', 'it makes it powerful',
            'to end strong',
          ],
          sampleAnswer: 'Short sentences make the ending feel strong and certain.',
          teach: 'Authors choose sentence length on purpose. Short and plain can land harder than long and fancy.',
        },
      ],
    },
  },
  {
    id: 'g3_read_02',
    subject: 'reading',
    grade: 3,
    title: 'How a Seed Knows Which Way Is Up',
    blurb: 'Informational text. There is a real puzzle hidden in this one.',
    minutes: 14,
    content: {
      kind: 'passage',
      passage: {
        title: 'How a Seed Knows Which Way Is Up',
        preview: [
          { word: 'gravity', meaning: 'the pull that draws everything toward the ground' },
          { word: 'root', meaning: 'the part of a plant that grows down into the soil' },
        ],
        paragraphs: [
          'Here is a puzzle. A seed underground is in total darkness. It cannot see the sun. So how does it know to send its root down and its shoot up?',
          'If it guessed wrong, the root would grow into the air and the plant would die.',
          'The answer is gravity. Inside the cells of a seed are tiny grains heavier than everything around them. They sink. They always sink, no matter which way the seed is lying.',
          'The seed senses where those grains have settled, and that tells it which direction is down. The root grows that way. The shoot grows the opposite way.',
          'Scientists tested this by growing seeds on the International Space Station, where there is almost no gravity to feel. The roots grew in confused spirals. They had lost their sense of down.',
          'A seed cannot see, hear, or think. But it can feel which way the world is pulling, and that turns out to be enough.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_02_c1',
          prompt: 'What tells a seed which way is down?',
          options: ['Sunlight', 'Water in the soil', 'Tiny heavy grains that sink', 'The temperature'],
          correct: 2,
          teach: 'Heavy grains inside its cells. They sink, and the seed reads where they land.',
        },
        {
          kind: 'choice',
          id: 'g3_read_02_c2',
          prompt: 'What happened to seeds grown on the space station?',
          options: [
            'They grew twice as fast',
            'Their roots grew in confused spirals',
            'They did not grow at all',
            'They grew upside down',
          ],
          correct: 1,
          teach: 'Confused spirals. With no gravity to feel, they had no "down" to grow toward.',
        },
        {
          kind: 'speak',
          id: 'g3_read_02_s1',
          prompt: 'Why does the author start with a question instead of an explanation?',
          accept: [
            'to make you curious', 'to make you think', 'to get you interested',
            'so you wonder', 'to hook you', 'to make you want to know',
            'it makes it interesting',
          ],
          sampleAnswer: 'To make the reader curious before giving the answer.',
          teach: 'Setting up a puzzle first is a choice. It makes you want the answer instead of just receiving it.',
        },
        {
          kind: 'choice',
          id: 'g3_read_02_c3',
          prompt: 'Why was the space station experiment useful?',
          options: [
            'It proved plants can live in space',
            'It removed gravity, testing whether gravity was really the cause',
            'It showed seeds grow faster in the dark',
            'It measured how tall plants get',
          ],
          correct: 1,
          teach: 'That is how good experiments work. Take away the thing you suspect and see what breaks.',
          hint: 'What was different up there compared to Earth?',
        },
        {
          kind: 'speak',
          id: 'g3_read_02_s2',
          prompt: 'The last line says the seed cannot see, hear, or think. So what CAN it do?',
          accept: [
            'feel gravity', 'feel which way the world pulls', 'feel the pull',
            'sense gravity', 'it can feel', 'feel down', 'sense which way is down',
          ],
          sampleAnswer: 'It can feel which way gravity is pulling.',
          teach: 'One single sense, and it is enough to get the whole job done.',
        },
        {
          kind: 'choice',
          id: 'g3_read_02_c4',
          prompt: 'What kind of text is this?',
          options: [
            'A made-up story',
            'Informational text explaining how something works',
            'A poem',
            'A letter to a friend',
          ],
          correct: 1,
          teach: 'Informational. It explains a real process using real evidence.',
        },
      ],
    },
  },
  {
    id: 'g3_read_03',
    subject: 'reading',
    grade: 3,
    title: 'The Argument at the Fence',
    blurb: 'A story where both girls think they are right. See if you can spot what neither of them noticed.',
    minutes: 14,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Argument at the Fence',
        preview: [{ word: 'insisted', meaning: 'said firmly, again and again' }],
        paragraphs: [
          'Priya and Naomi stood on opposite sides of the fence, both looking at the same painted number on the ground.',
          '"It is a six," Priya said.',
          '"It is a nine," said Naomi.',
          '"Six."',
          '"Nine."',
          'They insisted for a long time. Priya thought Naomi was being stubborn on purpose. Naomi thought Priya could not read.',
          'Finally Naomi walked all the way around to Priya\'s side of the fence. She looked down.',
          'It was a six.',
          'Then Priya walked around to where Naomi had been standing. She looked down at the same painted mark.',
          'It was a nine.',
          'They stood there for a second. Then they both started laughing.',
          '"We were both right," Naomi said.',
          '"No," Priya said slowly. "We were both only half right. That is different."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_03_c1',
          prompt: 'Why did the girls see different numbers?',
          options: [
            'One of them could not read',
            'They were standing on opposite sides',
            'The paint changed colour',
            'There were two different numbers',
          ],
          correct: 1,
          teach: 'Opposite sides. Same mark, different angle.',
        },
        {
          kind: 'speak',
          id: 'g3_read_03_s1',
          prompt: 'What did each girl think about the other before they walked around?',
          accept: [
            'stubborn', 'she thought she was being stubborn', 'she could not read',
            'they thought the other was wrong', 'priya thought naomi was stubborn',
            'naomi thought priya could not read', 'that she was wrong',
          ],
          sampleAnswer: 'Priya thought Naomi was being stubborn, and Naomi thought Priya could not read.',
          teach: 'They both assumed the worst instead of assuming a different view. That is the real mistake in the story.',
        },
        {
          kind: 'choice',
          id: 'g3_read_03_c2',
          prompt: 'What solved the argument?',
          options: [
            'A grown-up told them the answer',
            'They each went and looked from the other\'s spot',
            'They looked it up',
            'They agreed to stop talking about it',
          ],
          correct: 1,
          teach: 'They physically moved to each other\'s position. Nobody had to be told.',
        },
        {
          kind: 'speak',
          id: 'g3_read_03_s2',
          prompt: 'At the end Priya says they were "both only half right." What is the difference between that and "both right"?',
          accept: [
            'they each only saw part', 'they only saw one side', 'neither saw the whole thing',
            'they each had half the answer', 'they were missing something',
            'both saw only part of it', 'they did not see everything',
          ],
          sampleAnswer: 'Each of them only saw part of the truth, not all of it.',
          hint: 'Did either girl know the full story on her own?',
          teach: '"Both right" means nobody has to change. "Both half right" means everybody still has something to learn. Priya caught something real.',
        },
        {
          kind: 'choice',
          id: 'g3_read_03_c3',
          prompt: 'What is the theme of this story?',
          options: [
            'Fences cause problems',
            'Understanding someone means seeing from where they stand',
            'Numbers are confusing',
            'Always agree with your friends',
          ],
          correct: 1,
          teach: 'That is it exactly. The fence and the number are just the way the story shows it.',
        },
        {
          kind: 'speak',
          id: 'g3_read_03_s3',
          prompt: 'Think of a time you disagreed with someone. What might you have seen from their side?',
          accept: ['i', 'they', 'maybe', 'my sister', 'my friend', 'i think', 'they thought'],
          sampleAnswer: 'My sister was upset because I took the toy without asking, not because she was mean.',
          teach: 'That is genuinely hard to do. Thank you for trying it.',
        },
      ],
    },
  },
  {
    id: 'g3_read_04',
    subject: 'reading',
    grade: 3,
    title: 'Why the Ocean Is Salty',
    blurb: 'A question you have probably asked. Here is the real answer.',
    minutes: 14,
    content: {
      kind: 'passage',
      passage: {
        title: 'Why the Ocean Is Salty',
        preview: [
          { word: 'dissolve', meaning: 'to break apart into water until it disappears from sight' },
          { word: 'mineral', meaning: 'a solid natural substance found in rock and soil' },
        ],
        paragraphs: [
          'Rain is not salty. Rivers are not salty. So why is the ocean?',
          'The answer takes millions of years.',
          'When rain falls on land, it is slightly acidic. Not enough to hurt you, but enough to slowly wear away rock. As rainwater runs over stone, it dissolves tiny amounts of minerals — including salt — and carries them along.',
          'Those minerals travel down streams, into rivers, and finally into the sea. Each river carries only a small amount. You would never taste it.',
          'But here is the important part: water leaves the ocean by evaporating into the air, and when it evaporates, it leaves the salt behind. The water goes. The salt stays.',
          'So for millions of years, rivers have delivered salt to the ocean and evaporation has refused to take it back out. It builds and builds.',
          'The ocean is not salty because something made it salty. It is salty because salt has been arriving for a very long time and has nowhere else to go.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_04_c1',
          prompt: 'How does salt get into the ocean?',
          options: [
            'It falls from the sky as salty rain',
            'Rivers carry dissolved minerals from rock',
            'Fish produce it',
            'It rises up from the sea floor',
          ],
          correct: 1,
          teach: 'Rivers carry it, after rain dissolves it out of rock on land.',
        },
        {
          kind: 'choice',
          id: 'g3_read_04_c2',
          prompt: 'Why does the salt stay in the ocean instead of leaving?',
          options: [
            'Salt is too heavy to move',
            'Evaporation takes the water but leaves the salt',
            'Fish eat the water',
            'The salt freezes to the bottom',
          ],
          correct: 1,
          teach: 'That is the key step. Water evaporates, salt does not.',
        },
        {
          kind: 'speak',
          id: 'g3_read_04_s1',
          prompt: 'Rivers carry salt too. So why do rivers not taste salty?',
          accept: [
            'only a small amount', 'it is a tiny amount', 'not enough salt',
            'the water keeps moving', 'it does not build up', 'a little bit',
            'because it keeps flowing', 'small amount',
          ],
          sampleAnswer: 'Each river only carries a tiny amount, and it keeps flowing instead of building up.',
          hint: 'What does the ocean do that a river does not?',
          teach: 'Right. A river never gets to collect. The ocean has been collecting for millions of years.',
        },
        {
          kind: 'choice',
          id: 'g3_read_04_c3',
          prompt: 'What does "dissolve" mean here?',
          options: [
            'To freeze solid',
            'To break apart into water until it disappears from sight',
            'To float on top',
            'To turn into steam',
          ],
          correct: 1,
          teach: 'The salt is still there, just spread through the water where you cannot see it.',
        },
        {
          kind: 'speak',
          id: 'g3_read_04_s2',
          prompt: 'The last paragraph says the ocean is salty because salt "has nowhere else to go." Explain that in your own words.',
          accept: [
            'salt keeps coming in and cannot leave', 'it comes in but does not go out',
            'it builds up', 'salt goes in and stays', 'it cannot get out',
            'more comes in and none leaves', 'it just keeps adding up',
          ],
          sampleAnswer: 'Salt keeps arriving and never leaves, so it builds up over time.',
          teach: 'In goes salt, out goes only water. Over millions of years that adds up to an ocean.',
        },
        {
          kind: 'choice',
          id: 'g3_read_04_c4',
          prompt: 'Why does the author say "The answer takes millions of years" right at the start?',
          options: [
            'To warn the reader the passage is long',
            'To signal that this is a slow process, not a single event',
            'Because nobody knows the real answer',
            'To make the ocean sound old',
          ],
          correct: 1,
          teach: 'It prepares you to think about build-up over time rather than one cause.',
        },
      ],
    },
  },
  {
    id: 'g3_read_05',
    subject: 'reading',
    grade: 3,
    title: 'The Bridge That Sang',
    blurb: 'A true story about a mistake that taught engineers something important.',
    minutes: 15,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Bridge That Sang',
        preview: [
          { word: 'engineer', meaning: 'someone who designs and builds structures and machines' },
          { word: 'resonance', meaning: 'when small pushes at just the right rhythm build into a big movement' },
        ],
        paragraphs: [
          'In 1940, a brand new bridge opened across a windy strait in Washington State. It was long, narrow, and elegant. Drivers noticed something odd almost immediately: on windy days, the road surface rippled up and down like a ribbon.',
          'People thought it was fun. They drove across on purpose to feel it. They nicknamed the bridge "Galloping Gertie."',
          'The engineers were not worried. The bridge was strong. Steel does not break because it wobbles a little.',
          'But on a November morning, with steady wind at about forty miles an hour, the ripple changed. Instead of rolling up and down, the bridge began to twist — one side of the road rising as the other fell.',
          'The twisting grew. Not because the wind got stronger, but because each gust arrived at exactly the rhythm of the bridge\'s own sway, adding a little more each time. That is resonance. It is the same reason a swing goes higher when you push at the right moment, and no higher at all when you push at the wrong one.',
          'The bridge tore itself apart and fell into the water. Nobody was killed.',
          'Engineers now test every long bridge design in a wind tunnel first. The failure of Galloping Gertie is taught in engineering classes around the world — not as a disaster, but as a lesson that got paid for once so it would not have to be paid for again.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_05_c1',
          prompt: 'What was the bridge nicknamed?',
          options: ['Windy Wanda', 'Galloping Gertie', 'The Ribbon', 'Rolling Rosie'],
          correct: 1,
          teach: 'Galloping Gertie, because the road rippled like a running horse.',
        },
        {
          kind: 'speak',
          id: 'g3_read_05_s1',
          prompt: 'Explain resonance using the swing example from the passage.',
          accept: [
            'push at the right time', 'pushing at the right moment makes it go higher',
            'if you push at the right rhythm it gets bigger', 'right timing makes it bigger',
            'each push adds up', 'pushing at the right time adds up',
            'small pushes at the right time',
          ],
          sampleAnswer: 'Small pushes at exactly the right moment add up and make the swing go higher and higher.',
          hint: 'What matters more — how hard you push, or when?',
          teach: 'Timing, not strength. That is the whole idea, and it is why a steady wind could destroy a steel bridge.',
        },
        {
          kind: 'choice',
          id: 'g3_read_05_c2',
          prompt: 'Why did the twisting grow worse?',
          options: [
            'The wind became much stronger',
            'Each gust arrived at the rhythm of the bridge\'s own sway',
            'Too many cars were on the bridge',
            'The steel had rusted through',
          ],
          correct: 1,
          teach: 'The wind stayed steady. It was the timing that did the damage.',
        },
        {
          kind: 'choice',
          id: 'g3_read_05_c3',
          prompt: 'What mistake did the engineers make?',
          options: [
            'They used cheap materials',
            'They assumed strength was enough and ignored the wobble',
            'They built it too short',
            'They ignored the weather forecast',
          ],
          correct: 1,
          teach: 'The passage says it directly: "The engineers were not worried. The bridge was strong." Strong was not the right thing to check.',
        },
        {
          kind: 'speak',
          id: 'g3_read_05_s2',
          prompt: 'The last line calls it "a lesson that got paid for once." What does the author mean?',
          accept: [
            'other bridges are safe now', 'we learned from it', 'it only had to happen once',
            'now everyone knows', 'it taught everyone', 'so it would not happen again',
            'people learned so it does not happen again', 'we learned so nobody else has to',
          ],
          sampleAnswer: 'The failure taught everyone something, so no one has to learn it the hard way again.',
          teach: 'That is a generous way to look at failure. Something went wrong once and made everything after it safer.',
        },
        {
          kind: 'choice',
          id: 'g3_read_05_c4',
          prompt: 'How is this passage organised?',
          options: [
            'A list of bridge types',
            'A problem told in time order, ending with what changed because of it',
            'Two things compared side by side',
            'A set of instructions',
          ],
          correct: 1,
          teach: 'Time order, then consequence. Noticing structure helps you predict where a text is going.',
        },
      ],
    },
  },
  {
    id: 'g3_read_06',
    subject: 'reading',
    grade: 3,
    title: 'What the Fox Knew',
    blurb: 'A story that does not tell you the lesson. You have to find it.',
    minutes: 14,
    content: {
      kind: 'passage',
      passage: {
        title: 'What the Fox Knew',
        preview: [{ word: 'patient', meaning: 'able to wait calmly without giving up' }],
        paragraphs: [
          'The young fox watched the field mouse disappear under the snow and pounced immediately. Snow everywhere. No mouse.',
          'She tried again. Pounce. Nothing. Again. Nothing.',
          'Her mother sat at the edge of the field, not moving.',
          '"You are not helping," the young fox said.',
          '"I am helping," her mother said. "You are just not watching me."',
          'The young fox sat down beside her, mostly out of frustration. She watched. Her mother did nothing for a long time. Her ears turned slightly. She tilted her head. Still nothing.',
          'Then, without warning, her mother leapt — and came up with a mouse.',
          '"You were listening," the young fox said.',
          '"I was listening for where it was going to be," her mother said. "Not where it was."',
          'The young fox thought about that all winter. It was, she decided later, the only useful thing anyone had ever taught her.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_06_c1',
          prompt: 'Why did the young fox keep missing?',
          options: [
            'She was too slow',
            'She pounced where the mouse was, not where it was going',
            'The snow was too deep',
            'She could not see well',
          ],
          correct: 1,
          teach: 'That is the mother\'s exact lesson at the end.',
        },
        {
          kind: 'speak',
          id: 'g3_read_06_s1',
          prompt: 'The mother says "I am helping. You are just not watching me." What did she mean?',
          accept: [
            'she was showing her', 'she was teaching by doing', 'watch and learn',
            'she was showing how', 'she was demonstrating', 'she was teaching her by example',
            'she was showing instead of telling', 'you have to watch',
          ],
          sampleAnswer: 'She was teaching by showing, not by telling.',
          hint: 'Was she doing nothing, or was she doing something the young fox had not noticed?',
          teach: 'She was teaching the whole time. The lesson only started when the young fox sat down and paid attention.',
        },
        {
          kind: 'choice',
          id: 'g3_read_06_c2',
          prompt: 'Why did the young fox finally sit down next to her mother?',
          options: [
            'She was tired of hunting',
            'Mostly out of frustration',
            'Her mother called her over',
            'She had caught a mouse',
          ],
          correct: 1,
          teach: 'The passage says it plainly. She did not sit down because she was ready to learn — that came after.',
        },
        {
          kind: 'speak',
          id: 'g3_read_06_s2',
          prompt: 'What is the difference between listening for where something IS and where it is GOING to be?',
          accept: [
            'one is now and one is later', 'you have to think ahead', 'predicting',
            'guessing where it will go', 'thinking about the future', 'one is thinking ahead',
            'you have to predict', 'where it will be next',
          ],
          sampleAnswer: 'One is about right now. The other means thinking ahead and predicting.',
          teach: 'Predicting. It is what good readers do with stories, too — you are already doing it.',
        },
        {
          kind: 'choice',
          id: 'g3_read_06_c3',
          prompt: 'Which sentence best states the theme?',
          options: [
            'Foxes are good hunters',
            'Skill often means anticipating, not just reacting',
            'Mothers are always right',
            'Snow makes hunting difficult',
          ],
          correct: 1,
          teach: 'The story never says that sentence out loud. You had to build it yourself from what happened.',
        },
        {
          kind: 'speak',
          id: 'g3_read_06_s3',
          prompt: 'Why do you think the author never states the lesson directly?',
          accept: [
            'so you figure it out', 'to make you think', 'it is better if you find it',
            'so the reader works it out', 'so you learn it yourself',
            'to let you discover it', 'so we have to think about it',
          ],
          sampleAnswer: 'So the reader works it out and remembers it better.',
          teach: 'A lesson you find yourself sticks. A lesson handed to you slides right off.',
        },
      ],
    },
  },
  {
    id: 'g3_read_07',
    subject: 'reading',
    grade: 3,
    title: 'The Longest Word in the Room',
    blurb: 'About a girl who found out that sounding smart and being smart are not the same thing.',
    minutes: 14,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Longest Word in the Room',
        preview: [{ word: 'impressed', meaning: 'filled with admiration for someone' }],
        paragraphs: [
          'Clara collected long words the way other people collect stamps. Magnificent. Extraordinary. Incomprehensible.',
          'In class she used them all. Her teacher smiled. The other students looked slightly annoyed, which Clara took as a good sign.',
          'Then came the day she had to explain photosynthesis to a first grader named Esther, as part of the reading buddy program.',
          'Clara began. "Photosynthesis is the process by which chlorophyll-containing organisms convert luminous energy into chemical energy."',
          'Esther looked at her.',
          'Clara said it again, slower. Esther still looked at her.',
          'Clara stopped. She thought for a while. It was uncomfortable.',
          '"Plants eat light," she said finally. "They catch sunlight with the green stuff in their leaves and turn it into food."',
          'Esther\'s whole face changed. "Plants EAT LIGHT?"',
          '"Yes."',
          '"That is the best thing I have ever heard."',
          'Walking home, Clara realised something that annoyed her a little. The second version had been much harder to come up with than the first.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_07_c1',
          prompt: 'Why did Clara use long words in class?',
          options: [
            'Her teacher required it',
            'She liked how they made her sound',
            'She did not know shorter words',
            'It was a class assignment',
          ],
          correct: 1,
          teach: 'She collected them and enjoyed the effect. Even the annoyance of others felt like a win to her.',
        },
        {
          kind: 'choice',
          id: 'g3_read_07_c2',
          prompt: 'What finally made Esther understand?',
          options: [
            'Clara said it slower',
            'Clara drew a picture',
            'Clara said "plants eat light"',
            'The teacher explained it',
          ],
          correct: 2,
          teach: 'Three plain words did what the long sentence could not.',
        },
        {
          kind: 'speak',
          id: 'g3_read_07_s1',
          prompt: 'Why was the simple version harder for Clara to come up with?',
          accept: [
            'she had to understand it', 'you have to really know it',
            'she had to think about what it means', 'it takes more thinking',
            'she had to understand it herself first', 'you need to really understand',
            'she had to work it out',
          ],
          sampleAnswer: 'Because to explain something simply, you have to actually understand it yourself.',
          hint: 'Which version proves she really understood photosynthesis?',
          teach: 'Repeating a definition needs memory. Explaining it plainly needs understanding. Very different things.',
        },
        {
          kind: 'choice',
          id: 'g3_read_07_c3',
          prompt: 'Why did the realisation annoy Clara a little?',
          options: [
            'She had wasted her time learning long words',
            'It meant her impressive-sounding version was the easy one',
            'Esther did not thank her',
            'She was late getting home',
          ],
          correct: 1,
          teach: 'The thing she was proud of turned out to be the lazier option. That stings.',
        },
        {
          kind: 'speak',
          id: 'g3_read_07_s2',
          prompt: 'Try it yourself. Explain rain to a four-year-old in one sentence.',
          accept: ['water', 'clouds', 'falls', 'sky', 'drops', 'wet'],
          sampleAnswer: 'Clouds get too full of water and it falls down.',
          teach: 'That is a genuinely hard skill and you just did it.',
        },
        {
          kind: 'choice',
          id: 'g3_read_07_c4',
          prompt: 'What is the author\'s message?',
          options: [
            'Long words are bad',
            'Real understanding shows up as clear, simple explanation',
            'First graders are hard to teach',
            'You should not try to impress people',
          ],
          correct: 1,
          teach: 'Not that long words are bad — Clara still knows them. That clarity is the better test of understanding.',
        },
      ],
    },
  },
  {
    id: 'g3_read_08',
    subject: 'reading',
    grade: 3,
    title: 'Two Accounts of the Same Storm',
    blurb: 'The same night, described by two people. Notice what each one leaves out.',
    minutes: 15,
    content: {
      kind: 'passage',
      passage: {
        title: 'Two Accounts of the Same Storm',
        preview: [
          { word: 'account', meaning: 'a person\'s description of what happened' },
          { word: 'perspective', meaning: 'the particular way one person sees a thing' },
        ],
        paragraphs: [
          'FROM AMARA\'S JOURNAL:',
          'The storm was incredible. The thunder was so loud the windows shook, and the lightning lit up the whole yard like daytime. I counted the seconds between the flash and the boom to work out how far away it was. At one point it was only two seconds — that means the lightning was less than a mile away! Mom made us sit in the hallway. I did not want to. I wanted to watch.',
          'FROM HER GRANDMOTHER\'S LETTER, THE SAME NIGHT:',
          'We had a bad storm last night. The power went out just after eight. I could not find the candles in the dark, and the stairs are difficult for me now. Amara was so calm — she found the flashlight and brought it to me, and she talked the whole time about counting seconds. I do not think she noticed I was frightened. I was very glad she was there.',
          'Neither account is wrong. But if you only read one, you would not know what the night was really like.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g3_read_08_c1',
          prompt: 'How did Amara feel about the storm?',
          options: ['Terrified', 'Excited and curious', 'Bored', 'Angry'],
          correct: 1,
          teach: 'She called it incredible and wanted to watch instead of shelter.',
        },
        {
          kind: 'choice',
          id: 'g3_read_08_c2',
          prompt: 'How did the grandmother feel?',
          options: ['Excited', 'Frightened', 'Amused', 'Sleepy'],
          correct: 1,
          teach: 'She says it herself in her letter, though Amara never noticed.',
        },
        {
          kind: 'speak',
          id: 'g3_read_08_s1',
          prompt: 'Name one thing the grandmother mentions that Amara left out completely.',
          accept: [
            'the power went out', 'power', 'the candles', 'she was scared',
            'the flashlight', 'the stairs', 'grandmother was frightened',
            'she was frightened', 'the lights went out',
          ],
          sampleAnswer: 'The power going out, and that Grandmother was frightened.',
          teach: 'Amara never mentions the power at all. She was busy counting seconds.',
        },
        {
          kind: 'speak',
          id: 'g3_read_08_s2',
          prompt: 'Amara helped her grandmother without realising it. What did she do?',
          accept: [
            'brought the flashlight', 'found the flashlight', 'she talked to her',
            'she stayed calm', 'she kept talking', 'flashlight',
            'she brought a flashlight and talked',
          ],
          sampleAnswer: 'She found the flashlight and kept talking, which kept her grandmother calm.',
          teach: 'She thought she was just excited about lightning. She was also being a comfort.',
        },
        {
          kind: 'choice',
          id: 'g3_read_08_c3',
          prompt: 'Why does the author include BOTH accounts?',
          options: [
            'To show one of them is lying',
            'To show that each perspective is incomplete on its own',
            'To compare writing styles',
            'To make the passage longer',
          ],
          correct: 1,
          teach: 'The final line states it: neither is wrong, and neither alone is the whole night.',
        },
        {
          kind: 'speak',
          id: 'g3_read_08_s3',
          prompt: 'If you asked a third person in that house, what might they have noticed that neither of these two did?',
          accept: ['mom', 'the mother', 'i think', 'maybe', 'they might', 'the dog', 'someone'],
          sampleAnswer: 'Mom might have noticed how hard it was to keep everyone calm at once.',
          teach: 'Good — you are extending the idea past what the text gave you. That is real reading.',
        },
      ],
    },
  },
];
