import type { Star } from '../../types';

/**
 * Grade 3 critical thinking — 10 stars.
 *
 * Deduction, fact versus opinion, analogies, estimation, and spotting bad
 * reasoning. Several stars deliberately include claims that sound convincing
 * and are wrong, because recognising that is the actual skill.
 */

export const grade3Thinking: Star[] = [
  {
    id: 'g3_think_01',
    subject: 'thinking',
    grade: 3,
    title: 'Working It Out',
    blurb: 'Every clue you need is in the words. Nothing is hidden.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_01_a',
          prompt: 'Mia is older than Priya. Priya is older than Zoe. Zoe is older than Ana. Who is the youngest?',
          options: ['Mia', 'Priya', 'Zoe', 'Ana'],
          correct: 3,
          teach: 'Ana. You put all four in order from one sentence at a time.',
          hint: 'Line them up oldest to youngest as you read.',
        },
        {
          kind: 'choice',
          id: 'g3_think_01_b',
          prompt: 'All the books on the top shelf are blue. This book is red. What do we know?',
          options: [
            'It is on the top shelf',
            'It is not on the top shelf',
            'It is the only red book',
            'We cannot know anything',
          ],
          correct: 1,
          teach: 'If every top-shelf book is blue, a red book cannot be up there. That is real logic.',
        },
        {
          kind: 'choice',
          id: 'g3_think_01_c',
          prompt: 'Three girls each have one pet: a cat, a dog, a bird. Naomi has no fur on her clothes. Clara\'s pet barks. Who has the bird?',
          options: ['Naomi', 'Clara', 'The third girl', 'Cannot tell'],
          correct: 0,
          teach: 'Clara has the dog. Naomi has no fur, so not the cat — she has the bird.',
          hint: 'Start with the clue that names an animal directly.',
        },
        {
          kind: 'speak',
          id: 'g3_think_01_d',
          prompt: 'Every student who finished the project got a sticker. Esther did not get a sticker. What can we conclude?',
          accept: [
            'she did not finish', 'esther did not finish', 'she did not finish the project',
            'she didnt finish', 'she has not finished', 'she did not finish it',
          ],
          sampleAnswer: 'Esther did not finish the project.',
          teach: 'Exactly right. And notice — we know nothing about WHY. Logic tells us what, not why.',
        },
        {
          kind: 'choice',
          id: 'g3_think_01_e',
          prompt: 'The window is open and the papers are on the floor. What is the most reasonable conclusion?',
          options: [
            'Someone threw the papers down',
            'Wind from the window blew them off',
            'The papers fell by themselves',
            'A bird came in',
          ],
          correct: 1,
          teach: 'The most reasonable, given both facts together. Not the only possible one — the most reasonable.',
        },
        {
          kind: 'speak',
          id: 'g3_think_01_f',
          prompt: 'The ground is wet, but the sky is clear and the roof is completely dry. What might explain it?',
          accept: [
            'sprinkler', 'a sprinkler', 'someone watered', 'a hose', 'watering',
            'someone washed', 'a sprinkler was on', 'it was watered',
          ],
          sampleAnswer: 'A sprinkler or hose, because rain would have wet the roof too.',
          hint: 'Why does the dry roof matter?',
          teach: 'The dry roof rules out rain. Noticing what is MISSING is often the sharpest move.',
        },
      ],
    },
  },
  {
    id: 'g3_think_02',
    subject: 'thinking',
    grade: 3,
    title: 'Fact or Opinion',
    blurb: 'One of these can be checked. The other can only be argued.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_02_a',
          prompt: 'Fact or opinion? "The Pacific is the largest ocean on Earth."',
          options: ['Fact', 'Opinion'],
          correct: 0,
          teach: 'Fact. You can measure it and check.',
        },
        {
          kind: 'choice',
          id: 'g3_think_02_b',
          prompt: 'Fact or opinion? "The ocean is the most beautiful place in the world."',
          options: ['Fact', 'Opinion'],
          correct: 1,
          teach: 'Opinion. There is no measuring instrument for beautiful.',
        },
        {
          kind: 'choice',
          id: 'g3_think_02_c',
          prompt: 'Fact or opinion? "Everyone should learn to type."',
          options: ['Fact', 'Opinion'],
          correct: 1,
          teach: 'Opinion — a reasonable one, but the word "should" is the giveaway.',
        },
        {
          kind: 'choice',
          id: 'g3_think_02_d',
          prompt: 'Fact or opinion? "Water freezes at zero degrees Celsius."',
          options: ['Fact', 'Opinion'],
          correct: 0,
          teach: 'Fact. Anyone can test it and get the same result.',
        },
        {
          kind: 'speak',
          id: 'g3_think_02_e',
          prompt: 'Say a fact about yourself — something anyone could check.',
          accept: ['i am', 'i have', 'my', 'i live', 'im'],
          sampleAnswer: 'I am in third grade.',
          teach: 'That is checkable, so it is a fact.',
        },
        {
          kind: 'speak',
          id: 'g3_think_02_f',
          prompt: 'Now say an opinion you hold — something someone could disagree with.',
          accept: ['i think', 'i like', 'i love', 'the best', 'i believe', 'is better', 'i prefer'],
          sampleAnswer: 'I think summer is the best season.',
          teach: 'Opinions are not weaker than facts. They are just a different kind of claim.',
        },
      ],
    },
  },
  {
    id: 'g3_think_03',
    subject: 'thinking',
    grade: 3,
    title: 'That Argument Has a Hole',
    blurb: 'These all sound convincing. Every one of them is broken. Find the crack.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_03_a',
          prompt: '"Everyone in my class has a scooter, so scooters must be the most popular toy in the country." What is wrong?',
          options: [
            'Nothing, it is correct',
            'One class is too small to speak for the whole country',
            'Scooters are not toys',
            'Classes do not have opinions',
          ],
          correct: 1,
          teach: 'A small group cannot stand in for everyone. That is called a hasty generalization.',
        },
        {
          kind: 'choice',
          id: 'g3_think_03_b',
          prompt: '"I wore my red socks and we won the game. My socks made us win." What is wrong?',
          options: [
            'Red is not a lucky color',
            'Two things happening together does not mean one caused the other',
            'The socks were not clean',
            'Nothing is wrong',
          ],
          correct: 1,
          teach: 'Together in time is not the same as one causing the other. Adults get this wrong constantly.',
        },
        {
          kind: 'choice',
          id: 'g3_think_03_c',
          prompt: '"You either love math or you hate it." What is wrong?',
          options: [
            'Math is not lovable',
            'It ignores everything in between',
            'Nobody hates math',
            'It is too short',
          ],
          correct: 1,
          teach: 'Only two options offered when there are many. You can find math interesting and hard at once.',
        },
        {
          kind: 'speak',
          id: 'g3_think_03_d',
          prompt: '"My older sister says the moon is made of ice, and she is eleven, so it must be true." What is wrong with that reasoning?',
          accept: [
            'being older does not make you right', 'age does not mean correct',
            'she could be wrong', 'older does not mean right', 'she might be wrong',
            'that is not evidence', 'being eleven does not prove it',
            'you need evidence',
          ],
          sampleAnswer: 'Being older does not make someone right. You need evidence, not just age.',
          teach: 'Who said it is not evidence for whether it is true. Ask how they know.',
        },
        {
          kind: 'choice',
          id: 'g3_think_03_e',
          prompt: '"This cereal is the healthiest, because the box says so." What is wrong?',
          options: [
            'The box wants to sell you cereal, so it is not a neutral source',
            'Cereal is never healthy',
            'Boxes cannot have writing',
            'Nothing is wrong',
          ],
          correct: 0,
          teach: 'Always ask who benefits from you believing a claim.',
        },
        {
          kind: 'speak',
          id: 'g3_think_03_f',
          prompt: '"It rained the last three Saturdays, so it will definitely rain this Saturday." What is the problem?',
          accept: [
            'it might not', 'that does not mean it will', 'three times is not proof',
            'you cannot know', 'the past does not decide', 'it is not definite',
            'weather changes', 'that is not proof',
          ],
          sampleAnswer: 'Three times in a row does not guarantee the next one.',
          teach: 'A pattern can be a good hint. The word "definitely" is what breaks this one.',
        },
      ],
    },
  },
  {
    id: 'g3_think_04',
    subject: 'thinking',
    grade: 3,
    title: 'This Is Like That',
    blurb: 'Analogies. Find the relationship first, then apply it.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_04_a',
          prompt: 'Bird is to nest as bee is to ___?',
          options: ['Flower', 'Hive', 'Honey', 'Sky'],
          correct: 1,
          teach: 'Hive. The relationship is "creature to the home it builds."',
        },
        {
          kind: 'choice',
          id: 'g3_think_04_b',
          prompt: 'Hot is to cold as day is to ___?',
          options: ['Sun', 'Morning', 'Night', 'Week'],
          correct: 2,
          teach: 'Night. The relationship is opposites.',
        },
        {
          kind: 'choice',
          id: 'g3_think_04_c',
          prompt: 'Author is to book as composer is to ___?',
          options: ['Piano', 'Music', 'Orchestra', 'Concert'],
          correct: 1,
          teach: 'Music. The relationship is "maker to the thing they make."',
          hint: 'A piano is a tool, not the creation.',
        },
        {
          kind: 'choice',
          id: 'g3_think_04_d',
          prompt: 'Petal is to flower as ___ is to book?',
          options: ['Page', 'Library', 'Reader', 'Story'],
          correct: 0,
          teach: 'Page. The relationship is "one part to the whole."',
        },
        {
          kind: 'speak',
          id: 'g3_think_04_e',
          prompt: 'Telescope is to far away as microscope is to what?',
          accept: ['small', 'tiny', 'close', 'very small', 'little things', 'small things'],
          sampleAnswer: 'Very small things.',
          teach: 'Each tool makes visible what our eyes cannot reach — one by distance, one by size.',
        },
        {
          kind: 'speak',
          id: 'g3_think_04_f',
          prompt: 'Practice is to skill as water is to what?',
          accept: ['plant', 'a plant', 'growth', 'flower', 'plants', 'growing'],
          sampleAnswer: 'A plant.',
          hint: 'What does the first thing make possible in the second?',
          teach: 'Both are the thing you supply steadily so something else can grow.',
        },
      ],
    },
  },
  {
    id: 'g3_think_05',
    subject: 'thinking',
    grade: 3,
    title: 'About How Many',
    blurb: 'Estimation is not guessing. It is reasoning with numbers you already have.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_05_a',
          prompt: 'About how many days are in three years?',
          options: ['About 100', 'About 400', 'About 1,100', 'About 5,000'],
          correct: 2,
          teach: 'About 1,100. Three lots of 365 is a bit under 1,100.',
          hint: 'Round 365 to 400 and multiply, then adjust down.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_b',
          prompt: 'Is 48 + 51 closer to 50 or to 100?',
          options: ['50', '100'],
          correct: 1,
          teach: '100. Both numbers are near 50, and two 50s make 100.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_c',
          prompt: 'A book has 12 chapters, each about 10 pages. About how long is it?',
          options: ['About 22 pages', 'About 120 pages', 'About 1,200 pages', 'About 60 pages'],
          correct: 1,
          teach: '120 pages. Twelve tens.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_d',
          prompt: 'Which is the best estimate for how tall a classroom door is?',
          options: ['1 meter', '2 meters', '5 meters', '10 meters'],
          correct: 1,
          teach: 'About 2 meters — a bit taller than a grown-up.',
        },
        {
          kind: 'speak',
          id: 'g3_think_05_e',
          prompt: 'Without adding exactly: is 19 + 22 + 18 more or less than 60?',
          accept: ['less', 'less than 60', 'under', 'under 60', 'no', 'less than sixty'],
          sampleAnswer: 'Less than 60.',
          hint: 'Round each one to the nearest ten first.',
          teach: 'Less — about 59. Rounding to 20 + 20 + 20 gets you there in your head.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_f',
          prompt: 'Someone says a cat weighs 400 kilograms. What should you think?',
          options: [
            'That sounds about right',
            'That cannot be right — that is heavier than a horse',
            'Cats cannot be weighed',
            'It depends on the cat',
          ],
          correct: 1,
          teach: 'Estimation is a lie detector. When a number feels impossible, check it.',
        },
      ],
    },
  },
  {
    id: 'g3_think_06',
    subject: 'thinking',
    grade: 3,
    title: 'What Is Missing',
    blurb: 'Sometimes the most important information is the information you were not given.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_06_a',
          prompt: '"Buy this bike — nine out of ten riders recommend it!" What would you want to know?',
          options: [
            'The color of the bike',
            'How many riders were asked, and who asked them',
            'The name of the shop',
            'Nothing else',
          ],
          correct: 1,
          teach: 'Nine out of ten sounds strong until you learn only ten people were asked — by the seller.',
        },
        {
          kind: 'choice',
          id: 'g3_think_06_b',
          prompt: '"Our team scored more goals this season than last." What is missing?',
          options: [
            'How many games were played each season',
            'The color of the uniforms',
            'The name of the coach',
            'Nothing',
          ],
          correct: 0,
          teach: 'More goals across twice as many games is not an improvement at all.',
        },
        {
          kind: 'speak',
          id: 'g3_think_06_c',
          prompt: 'A sign says "Now 50% off!" What would you need to know to tell if it is a good deal?',
          accept: [
            'the original price', 'the price before', 'what it cost before',
            'the old price', 'how much it was', 'the regular price', 'the first price',
          ],
          sampleAnswer: 'The original price, before the discount.',
          teach: 'Half off a price they just doubled is not a discount. Always ask "off what?"',
        },
        {
          kind: 'choice',
          id: 'g3_think_06_d',
          prompt: 'A friend says "the movie was terrible, do not watch it." What is worth asking?',
          options: [
            'What they usually like, and why they disliked it',
            'How long the movie was',
            'Where they watched it',
            'Nothing — just trust them',
          ],
          correct: 0,
          teach: 'A review tells you about the reviewer as much as the thing reviewed.',
        },
        {
          kind: 'speak',
          id: 'g3_think_06_e',
          prompt: '"Most students at our school prefer pizza." How could you check whether that is true?',
          accept: [
            'ask them', 'ask everyone', 'a survey', 'take a vote', 'ask the students',
            'ask a lot of people', 'count', 'survey', 'ask lots of students',
          ],
          sampleAnswer: 'Ask a lot of students, not just your friends.',
          teach: 'And ask a spread of them. Asking only your own table gives you your table\'s answer.',
        },
      ],
    },
  },
  {
    id: 'g3_think_07',
    subject: 'thinking',
    grade: 3,
    title: 'Puzzles That Bite Back',
    blurb: 'Read each of these twice. The obvious answer is wrong on purpose.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g3_think_07_a',
          prompt: 'A farmer has 17 sheep. All but 9 run away. How many are left?',
          accept: ['9', 'nine'],
          sampleAnswer: '9',
          hint: 'Read "all but 9" very carefully.',
          teach: 'Nine. "All but 9 ran away" means 9 stayed. Most people say 8.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_b',
          prompt: 'You are in a race and you pass the person in second place. What place are you in now?',
          accept: ['second', '2nd', 'second place', '2'],
          sampleAnswer: 'Second place.',
          hint: 'You took their spot, not the spot ahead of them.',
          teach: 'Second. If you pass the person in second, you become second.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_c',
          prompt: 'A doctor gives you 3 pills and says take one every half hour. How long until they are gone?',
          accept: ['1 hour', 'one hour', '60 minutes', 'an hour', '60'],
          sampleAnswer: 'One hour.',
          hint: 'When do you take the first one?',
          teach: 'One hour. Take the first immediately — only two gaps of half an hour follow.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_d',
          prompt: 'Some months have 31 days. Some have 30. How many have 28 days?',
          accept: ['12', 'twelve', 'all', 'all of them', 'all twelve'],
          sampleAnswer: 'All twelve.',
          hint: 'The question does not say "only 28 days."',
          teach: 'All twelve. Every month has 28 days, and most have a few more.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_e',
          prompt: 'If a red house is made of red bricks and a blue house of blue bricks, what is a greenhouse made of?',
          accept: ['glass', 'made of glass'],
          sampleAnswer: 'Glass.',
          teach: 'Glass. The pattern set you up, and the last one does not follow it.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_f',
          prompt: 'Which weighs more: a kilogram of feathers or a kilogram of stones?',
          accept: ['same', 'the same', 'equal', 'neither', 'they weigh the same', 'both the same'],
          sampleAnswer: 'They weigh the same.',
          teach: 'The same. A kilogram is a kilogram. Feathers just take up far more space.',
        },
      ],
    },
  },
  {
    id: 'g3_think_08',
    subject: 'thinking',
    grade: 3,
    title: 'Breaking It Down',
    blurb: 'Big problems are just small problems stacked up.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g3_think_08_a',
          prompt: 'Put these steps in order for planning a birthday party.',
          items: [
            'Decide the date and who to invite',
            'Send the invitations',
            'Buy the food and decorations',
            'Set up on the day',
          ],
          teach: 'You cannot invite people before you pick a date. Order is part of the plan.',
        },
        {
          kind: 'order',
          id: 'g3_think_08_b',
          prompt: 'Put these in order for writing a report about penguins.',
          items: [
            'Decide what you want to find out',
            'Read and take notes',
            'Organise notes into topics',
            'Write the report',
            'Check it for mistakes',
          ],
          teach: 'Notice that writing is fourth, not first. Most of the work happens before the writing.',
        },
        {
          kind: 'choice',
          id: 'g3_think_08_c',
          prompt: 'You have one hour to clean a very messy room. What is the best first step?',
          options: [
            'Start scrubbing the floor',
            'Look around and decide what makes the biggest difference',
            'Organise the bookshelf perfectly',
            'Clean one small corner completely',
          ],
          correct: 1,
          teach: 'Plan before you act. With limited time, choosing what matters most is the real work.',
        },
        {
          kind: 'speak',
          id: 'g3_think_08_d',
          prompt: 'You need 100 cookies for a bake sale and each batch makes 12. About how many batches?',
          accept: ['9', 'nine', '8', 'eight', '8 or 9', 'about 9', 'nine batches'],
          sampleAnswer: 'About 9 batches.',
          hint: '12 times 8 is 96 — is that enough?',
          teach: 'Nine. Eight batches gives 96, which is short, so you round up. Real problems often round up.',
        },
        {
          kind: 'choice',
          id: 'g3_think_08_e',
          prompt: 'Your math homework is very hard. What is the most useful first move?',
          options: [
            'Give up and do something else',
            'Find the easiest problem and start there',
            'Copy someone else\'s answers',
            'Do them in order no matter what',
          ],
          correct: 1,
          teach: 'Starting where you can build momentum is a real strategy, not a shortcut.',
        },
      ],
    },
  },
  {
    id: 'g3_think_09',
    subject: 'thinking',
    grade: 3,
    title: 'Patterns and Rules',
    blurb: 'Find the rule, then use it. The rule is always simpler than it looks.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g3_think_09_a',
          prompt: '2, 4, 8, 16, ... what comes next?',
          accept: ['32', 'thirty two', 'thirty-two'],
          sampleAnswer: '32',
          hint: 'What are you doing to each number to get the next?',
          teach: '32. Each number doubles.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_b',
          prompt: '1, 4, 9, 16, 25, ... what comes next?',
          accept: ['36', 'thirty six', 'thirty-six'],
          sampleAnswer: '36',
          hint: 'Try one times one, two times two, three times three...',
          teach: '36. These are square numbers: 6 times 6.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_c',
          prompt: '100, 90, 81, 73, ... what comes next?',
          accept: ['66', 'sixty six', 'sixty-six'],
          sampleAnswer: '66',
          hint: 'How much is taken away each time? Is it the same amount?',
          teach: '66. The gaps shrink: minus 10, minus 9, minus 8, then minus 7.',
        },
        {
          kind: 'choice',
          id: 'g3_think_09_d',
          prompt: 'A, C, E, G, ... what comes next?',
          options: ['H', 'I', 'J', 'K'],
          correct: 1,
          teach: 'I. The pattern skips a letter each time.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_e',
          prompt: 'A machine turns 3 into 7, and 5 into 11, and 6 into 13. What is the rule?',
          accept: [
            'double plus one', 'times 2 plus 1', 'multiply by 2 and add 1',
            'double it and add one', 'x2 plus 1', 'twice plus one', 'double and add 1',
          ],
          sampleAnswer: 'Double it and add one.',
          hint: 'Try doubling first and see how far off you are.',
          teach: 'Double and add one. Three doubled is six, plus one is seven. It works for all three.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_f',
          prompt: 'Using that same rule, what does the machine turn 10 into?',
          accept: ['21', 'twenty one', 'twenty-one'],
          sampleAnswer: '21',
          teach: '21. You found a rule and then used it on something new. That is exactly what mathematicians do.',
        },
      ],
    },
  },
  {
    id: 'g3_think_10',
    subject: 'thinking',
    grade: 3,
    title: 'The Puzzle Weaver',
    blurb: 'The last star here. Everything at once, and no hints about which kind is which.',
    minutes: 14,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_10_a',
          prompt: 'Fact or opinion? "This is the hardest star in the whole app."',
          options: ['Fact', 'Opinion'],
          correct: 1,
          teach: 'Opinion — even when I am the one saying it.',
        },
        {
          kind: 'speak',
          id: 'g3_think_10_b',
          prompt: 'Clara is not the tallest. Naomi is taller than Clara but shorter than Ruby. Who is tallest?',
          accept: ['ruby'],
          sampleAnswer: 'Ruby',
          teach: 'Ruby. The first sentence was a distraction — the second gave you everything.',
        },
        {
          kind: 'choice',
          id: 'g3_think_10_c',
          prompt: 'Pen is to write as ___ is to cut.',
          options: ['Paper', 'Scissors', 'Glue', 'Ruler'],
          correct: 1,
          teach: 'Scissors. Tool to the action it performs.',
        },
        {
          kind: 'speak',
          id: 'g3_think_10_d',
          prompt: 'A shelf holds 6 rows with 8 books in each. About how many books?',
          accept: ['48', 'forty eight', 'forty-eight', 'about 50', '50'],
          sampleAnswer: '48',
          teach: '48. Six eights.',
        },
        {
          kind: 'choice',
          id: 'g3_think_10_e',
          prompt: '"Everyone I asked agreed with me, so I must be right." What is wrong?',
          options: [
            'Nothing is wrong',
            'They may all have been people who already agreed with you',
            'You should ask more loudly',
            'Agreement is impossible',
          ],
          correct: 1,
          teach: 'Who you ask decides what you hear. Seek out someone likely to disagree — that is the real test.',
        },
        {
          kind: 'speak',
          id: 'g3_think_10_f',
          prompt: 'Last one. What is the most useful question to ask when someone tells you something surprising?',
          accept: [
            'how do you know', 'why', 'how do they know', 'what is the evidence',
            'are you sure', 'how do you know that', 'whats the proof', 'where did you hear that',
            'how',
          ],
          sampleAnswer: 'How do you know?',
          teach: '"How do you know?" It is polite, it is short, and it works on almost everything. Carry it with you.',
        },
      ],
    },
  },
  {
    id: 'g3_think_11',
    subject: 'thinking',
    grade: 3,
    title: 'The Detective\'s Notebook',
    blurb: 'Read the clues. Rule things out. Find what must be true.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_11_a',
          prompt: 'Three cups: red, blue, green. The coin is not in the red cup. It is not in the blue cup. Where is the coin?',
          options: ['Red cup', 'Blue cup', 'Green cup', 'Cannot be known'],
          correct: 2,
          teach: 'Green — the only one left. Ruling out is as powerful as finding.',
        },
        {
          kind: 'choice',
          id: 'g3_think_11_b',
          prompt: 'Ana, Ben, and Cara each have one pet: a cat, a dog, or a fish. Ana is allergic to fur. Ben\'s pet barks. What is Cara\'s pet?',
          options: ['The cat', 'The dog', 'The fish', 'Cannot be known'],
          correct: 0,
          teach: 'Ana must have the fish (no fur), Ben has the dog (barks), so Cara has the cat.',
        },
        {
          kind: 'speak',
          id: 'g3_think_11_c',
          prompt: 'The cookie jar is empty. Dad was at work. The dog cannot open jars. Your sister has crumbs on her shirt. What do you conclude?',
          accept: ['sister', 'my sister ate them', 'the sister took the cookies', 'sister ate the cookies'],
          sampleAnswer: 'My sister ate the cookies — the crumbs are evidence.',
          teach: 'Opportunity plus evidence. The crumbs close the case.',
        },
        {
          kind: 'choice',
          id: 'g3_think_11_d',
          prompt: 'Which is the strongest evidence that it snowed overnight?',
          options: ['The forecast said maybe', 'You dreamed of snow', 'Fresh snow is covering your yard', 'It is December'],
          correct: 2,
          teach: 'Seeing the snow itself beats predictions, dreams, and calendars combined.',
        },
        {
          kind: 'choice',
          id: 'g3_think_11_e',
          prompt: 'A good detective changes their mind when...',
          options: ['Never — that is weakness', 'New evidence points a different way', 'Someone argues loudly', 'They get tired'],
          correct: 1,
          teach: 'Following the evidence — even when it surprises you — IS the job.',
        },
      ],
    },
  },
  {
    id: 'g3_think_12',
    subject: 'thinking',
    grade: 3,
    title: 'If This, Then That',
    blurb: 'Rules connect. Follow the chain to the end.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_12_a',
          prompt: 'Rule: If it rains, the game is canceled. It is raining. What do you know?',
          options: ['The game is on', 'The game is canceled', 'The rain will stop', 'Nothing'],
          correct: 1,
          teach: 'The rule fires: rain means canceled. If-then chains are logic\'s building blocks.',
        },
        {
          kind: 'choice',
          id: 'g3_think_12_b',
          prompt: 'Rule: If it rains, the game is canceled. The game is canceled. Does that PROVE it rained?',
          options: ['Yes, definitely', 'No — something else could have canceled it', 'Games never cancel', 'Rules work backwards'],
          correct: 1,
          teach: 'Careful! Maybe the coach got sick. Rules do not automatically run in reverse.',
        },
        {
          kind: 'choice',
          id: 'g3_think_12_c',
          prompt: 'If all fish live in water, and a trout is a fish, then...',
          options: ['Trout live in water', 'Trout live in trees', 'Water is a fish', 'Nothing follows'],
          correct: 0,
          teach: 'The chain connects: all fish → water; trout → fish; so trout → water.',
        },
        {
          kind: 'speak',
          id: 'g3_think_12_d',
          prompt: 'Finish the chain: If I practice daily, I improve. If I improve, I gain confidence. So if I practice daily...',
          accept: ['i gain confidence', 'confidence', 'i get confident', 'i will gain confidence', 'then i gain confidence'],
          sampleAnswer: 'I gain confidence.',
          teach: 'Chains link end to end. Practice → improvement → confidence.',
        },
        {
          kind: 'choice',
          id: 'g3_think_12_e',
          prompt: 'Rule: If you finish homework, you may play. Jo is playing. Her brother says she MUST have finished. Is he right?',
          options: ['Yes, always', 'Not necessarily — maybe she broke the rule, or was excused', 'Playing proves homework', 'Rules cannot be checked'],
          correct: 1,
          teach: 'Seeing the result does not prove the rule was followed. Check before concluding.',
        },
      ],
    },
  },
  {
    id: 'g3_think_13',
    subject: 'thinking',
    grade: 3,
    title: 'The Estimation Station',
    blurb: 'Close-enough answers, fast — a real superpower.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_13_a',
          prompt: 'About how many jellybeans fit in a school backpack?',
          options: ['About 50', 'Thousands', 'Two or three', 'A million'],
          correct: 1,
          teach: 'A backpack holds thousands of bean-sized things. Feel the size, do not count.',
        },
        {
          kind: 'choice',
          id: 'g3_think_13_b',
          prompt: '29 + 32 is closest to...',
          options: ['40', '50', '60', '90'],
          correct: 2,
          teach: 'Round: 30 + 30 = 60. Estimating catches mistakes before they happen.',
        },
        {
          kind: 'choice',
          id: 'g3_think_13_c',
          prompt: 'Your book has 90 pages. You read about 10 pages a day. About how long to finish?',
          options: ['3 days', '9 days', '30 days', '90 days'],
          correct: 1,
          teach: 'About 9 days. Estimates help you plan real things.',
        },
        {
          kind: 'speak',
          id: 'g3_think_13_d',
          prompt: 'Estimate: about how many steps from your bedroom to the kitchen?',
          accept: ['10', '15', '20', '25', '30', '40', '50', 'about', 'steps', 'maybe'],
          sampleAnswer: 'About 20 steps.',
          teach: 'Any reasonable number wins. Estimating means being roughly right instantly.',
        },
        {
          kind: 'choice',
          id: 'g3_think_13_e',
          prompt: 'A friend says a movie ticket costs $200. Your estimation alarm should say...',
          options: ['Sounds right', 'Way too high — tickets are closer to $10-15', 'Too low', 'Estimation cannot help'],
          correct: 1,
          teach: 'Estimation is a lie detector for numbers. $200 fails the smell test.',
        },
      ],
    },
  },
  {
    id: 'g3_think_14',
    subject: 'thinking',
    grade: 3,
    title: 'Whose Job Is the Truth',
    blurb: 'Claims need checking. Learn who and what to trust.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_14_a',
          prompt: 'You want to know if a mushroom is safe to eat. Best source?',
          options: ['A guess', 'A mushroom expert or field guide', 'A friend who "thinks so"', 'Its pretty color'],
          correct: 1,
          teach: 'For dangerous questions, expertise matters most. Never guess with mushrooms.',
        },
        {
          kind: 'choice',
          id: 'g3_think_14_b',
          prompt: 'A cereal ad says "the BEST breakfast in the world!" What is the ad\'s job?',
          options: ['To inform you fairly', 'To sell you cereal', 'To test breakfasts', 'To report news'],
          correct: 1,
          teach: 'Ads sell. Knowing WHY someone tells you something changes how you weigh it.',
        },
        {
          kind: 'choice',
          id: 'g3_think_14_c',
          prompt: 'Two friends describe the same playground argument completely differently. Why?',
          options: ['One must be lying', 'Each saw it from their own side', 'Arguments change reality', 'Playgrounds are confusing'],
          correct: 1,
          teach: 'People honestly see events from where they stood. Hearing both sides fills the picture.',
        },
        {
          kind: 'speak',
          id: 'g3_think_14_d',
          prompt: 'Someone online says "scientists discovered chocolate makes you fly." What should you do before believing it?',
          accept: ['check', 'verify', 'look it up', 'find the source', 'ask if it is true', 'check other places'],
          sampleAnswer: 'Check it — look for a real source.',
          teach: 'Extraordinary claims need extraordinary checking. (Also: chocolate does not do that.)',
        },
        {
          kind: 'choice',
          id: 'g3_think_14_e',
          prompt: 'Which claim needs the MOST checking before you believe it?',
          options: ['"The library closes at 5"', '"My cat sleeps a lot"', '"This bracelet cures all sickness"', '"It might rain Tuesday"'],
          correct: 2,
          teach: 'Big promises about health and money deserve your strongest doubt.',
        },
      ],
    },
  },
  {
    id: 'g3_think_15',
    subject: 'thinking',
    grade: 3,
    title: 'The Planning Table',
    blurb: 'Good plans think backwards from the goal.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g3_think_15_a',
          prompt: 'Order the steps for a lemonade stand.',
          items: ['Make the lemonade', 'Set up the table', 'Sell cups to neighbors', 'Count the money'],
          teach: 'Product, setup, sales, counting. Plans are steps in working order.',
        },
        {
          kind: 'choice',
          id: 'g3_think_15_b',
          prompt: 'Your project is due Friday. It needs 4 hours. You have 1 free hour a day. When must you start?',
          options: ['Friday', 'Thursday', 'Monday', 'Never'],
          correct: 2,
          teach: 'Four hours at one per day means starting Monday. Count backwards from the deadline.',
        },
        {
          kind: 'choice',
          id: 'g3_think_15_c',
          prompt: 'What is a backup plan for an outdoor party?',
          options: ['Hope hard', 'An indoor space ready if it rains', 'Cancel everything', 'Ignore weather'],
          correct: 1,
          teach: 'A backup plan answers "what if?" before it happens.',
        },
        {
          kind: 'speak',
          id: 'g3_think_15_d',
          prompt: 'You are packing for the beach. Name two things you must not forget.',
          accept: ['sunscreen', 'water', 'towel', 'swimsuit', 'hat', 'snacks', 'sunglasses'],
          sampleAnswer: 'Sunscreen and water.',
          teach: 'Packing lists are plans against forgetting. Planners write things down.',
        },
        {
          kind: 'order',
          id: 'g3_think_15_e',
          prompt: 'Order these for baking cookies with a friend arriving at 3:00.',
          items: ['Check you have ingredients', 'Mix the dough', 'Bake them', 'Cool and share at 3:00'],
          teach: 'Ingredients first — discovering no flour mid-mix ruins the plan.',
        },
      ],
    },
  },
  {
    id: 'g3_think_16',
    subject: 'thinking',
    grade: 3,
    title: 'The Both-Sides Bench',
    blurb: 'Strong thinkers can argue the side they disagree with.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_16_a',
          prompt: 'Should recess be longer? Which is the strongest argument FOR?',
          options: ['Kids just like it', 'Exercise and breaks improve focus in class', 'Teachers need naps', 'School is boring'],
          correct: 1,
          teach: 'The strongest FOR connects recess to learning itself.',
        },
        {
          kind: 'choice',
          id: 'g3_think_16_b',
          prompt: 'Same question. Which is the strongest argument AGAINST?',
          options: ['Recess is silly', 'Less class time might mean less learning', 'Playgrounds are loud', 'Kids get muddy'],
          correct: 1,
          teach: 'The strongest AGAINST takes the trade-off seriously. Real questions have real both-sides.',
        },
        {
          kind: 'speak',
          id: 'g3_think_16_c',
          prompt: 'You think dogs are better than cats. Give one honest point for the CAT side.',
          accept: ['cats are', 'they are quiet', 'independent', 'clean', 'less work', 'calm', 'soft'],
          sampleAnswer: 'Cats are quieter and need less care.',
          teach: 'You argued against yourself honestly. That is rare and valuable.',
        },
        {
          kind: 'choice',
          id: 'g3_think_16_d',
          prompt: 'Why practice arguing the other side?',
          options: ['To trick people', 'To understand the whole question, not half of it', 'To always win', 'To be annoying'],
          correct: 1,
          teach: 'Seeing both sides shows you the whole shape of the question.',
        },
        {
          kind: 'choice',
          id: 'g3_think_16_e',
          prompt: 'After hearing a strong other side, a good thinker...',
          options: ['Ignores it', 'Might update their opinion — that is strength', 'Argues louder', 'Leaves'],
          correct: 1,
          teach: 'Changing your mind for good reasons is a superpower, not a defeat.',
        },
      ],
    },
  },
  {
    id: 'g3_think_17',
    subject: 'thinking',
    grade: 3,
    title: 'Riddle Mountain',
    blurb: 'Harder riddles for stronger climbers.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_17_a',
          prompt: 'The more you take from me, the bigger I get. What am I?',
          options: ['A cookie', 'A hole', 'A balloon', 'A river'],
          correct: 1,
          teach: 'A hole. Taking away is its kind of growing.',
        },
        {
          kind: 'choice',
          id: 'g3_think_17_b',
          prompt: 'I speak without a mouth and hear without ears. What am I?',
          options: ['A phone', 'An echo', 'A book', 'The wind'],
          correct: 1,
          teach: 'An echo answers you with your own voice.',
        },
        {
          kind: 'choice',
          id: 'g3_think_17_c',
          prompt: 'What has cities but no houses, forests but no trees, and water but no fish?',
          options: ['A dream', 'A map', 'A painting', 'A story'],
          correct: 1,
          teach: 'A map holds the shapes of things, not the things themselves.',
        },
        {
          kind: 'speak',
          id: 'g3_think_17_d',
          prompt: 'What gets sharper the more you use it? (Hint: it is not a knife — it is in your head.)',
          accept: ['brain', 'your brain', 'the mind', 'your mind', 'my brain'],
          sampleAnswer: 'Your brain.',
          teach: 'Your brain. Knives dull with use; minds sharpen. You are sharpening yours right now.',
        },
        {
          kind: 'choice',
          id: 'g3_think_17_e',
          prompt: 'What belongs to you but is used far more by other people?',
          options: ['Your shoes', 'Your name', 'Your lunch', 'Your thoughts'],
          correct: 1,
          teach: 'Your name. Others say it a hundred times for every once you do.',
        },
      ],
    },
  },
  {
    id: 'g3_think_18',
    subject: 'thinking',
    grade: 3,
    title: 'The Fair Share Court',
    blurb: 'What is fair? Harder than it sounds.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_18_a',
          prompt: 'Two kids must split one cake fairly. The classic trick?',
          options: ['Older kid decides', 'One cuts, the other picks first', 'Flip the cake', 'Nobody eats'],
          correct: 1,
          teach: 'The cutter cuts evenly BECAUSE they pick last. The rule makes fairness automatic.',
        },
        {
          kind: 'choice',
          id: 'g3_think_18_b',
          prompt: 'Does fair always mean exactly equal? A baby and a teenager at dinner...',
          options: ['Must eat identical amounts', 'Fair can mean each gets what they need', 'The teen gets nothing', 'Fairness is impossible'],
          correct: 1,
          teach: 'Equal portions for unequal needs is not fair. Fair sometimes means fitting the need.',
        },
        {
          kind: 'speak',
          id: 'g3_think_18_c',
          prompt: 'Both teams want the field at the same time. Suggest a fair solution.',
          accept: ['take turns', 'split the time', 'share', 'half and half', 'flip a coin', 'alternate'],
          sampleAnswer: 'Split the time in half, or alternate days.',
          teach: 'Turns, splits, and coin flips are all fairness machines humans invented.',
        },
        {
          kind: 'choice',
          id: 'g3_think_18_d',
          prompt: 'A rule says "no ball games" because ONE kid broke a window. Is the rule fair to everyone else?',
          options: ['Perfectly fair', 'Worth questioning — it punishes many for one', 'Rules cannot be questioned', 'Windows matter more than fairness'],
          correct: 1,
          teach: 'Group punishment for one person\'s mistake deserves the question: is there a better rule?',
        },
        {
          kind: 'choice',
          id: 'g3_think_18_e',
          prompt: 'Why do referees exist in games?',
          options: ['To ruin fun', 'Players judging their own side see unfairly', 'To wear stripes', 'Nobody knows'],
          correct: 1,
          teach: 'We all see our own side kindly. A neutral judge corrects for that lean.',
        },
      ],
    },
  },
  {
    id: 'g3_think_19',
    subject: 'thinking',
    grade: 3,
    title: 'The Chance Machine',
    blurb: 'Likely, unlikely, certain, impossible — sorting the future.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_19_a',
          prompt: 'Which is CERTAIN?',
          options: ['It will rain tomorrow', 'The sun will rise tomorrow', 'You will find a coin', 'Your team wins'],
          correct: 1,
          teach: 'Sunrise is as certain as things get. The rest are maybes.',
        },
        {
          kind: 'choice',
          id: 'g3_think_19_b',
          prompt: 'Which is IMPOSSIBLE?',
          options: ['Snow in summer', 'Rolling a 7 on one normal die', 'A cat napping', 'Rain on your birthday'],
          correct: 1,
          teach: 'A die has faces 1-6. Seven is not unlikely — it is impossible. Different things!',
        },
        {
          kind: 'choice',
          id: 'g3_think_19_c',
          prompt: 'A bag has 9 red marbles and 1 blue. You pull one without looking. Most likely?',
          options: ['Blue', 'Red', 'Equal chances', 'Green'],
          correct: 1,
          teach: 'Nine chances to one. Not guaranteed — but a smart bet.',
        },
        {
          kind: 'speak',
          id: 'g3_think_19_d',
          prompt: 'Name something LIKELY to happen at school tomorrow.',
          accept: ['lunch', 'recess', 'we will read', 'homework', 'the bell', 'learning', 'my teacher'],
          sampleAnswer: 'We will have lunch.',
          teach: 'Likely means it usually happens — not promised, but expected.',
        },
        {
          kind: 'choice',
          id: 'g3_think_19_e',
          prompt: 'You flipped heads 3 times in a row. The next flip is...',
          options: ['Definitely heads', 'Definitely tails', 'Still 50-50 — coins have no memory', 'Broken'],
          correct: 2,
          teach: 'The coin does not remember. Every flip starts fresh at 50-50. Most adults get this wrong!',
        },
      ],
    },
  },
  {
    id: 'g3_think_20',
    subject: 'thinking',
    grade: 3,
    title: 'The Invention Workshop',
    blurb: 'Problems are invitations. RSVP with ideas.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_20_a',
          prompt: 'Every invention starts with...',
          options: ['A factory', 'A problem someone noticed', 'Money', 'Luck'],
          correct: 1,
          teach: 'Umbrellas came from rain, erasers from mistakes. Problems are seeds.',
        },
        {
          kind: 'speak',
          id: 'g3_think_20_b',
          prompt: 'Your ice cream always melts before you finish. Invent any solution!',
          accept: ['a', 'bowl', 'freezer', 'cold', 'eat faster', 'smaller', 'i would'],
          sampleAnswer: 'A bowl with a tiny freezer inside.',
          teach: 'Wild or practical, that was inventing: problem, then idea.',
        },
        {
          kind: 'choice',
          id: 'g3_think_20_c',
          prompt: 'Your first version fails. Real inventors...',
          options: ['Quit forever', 'Study the failure and build version two', 'Hide it', 'Blame the tools'],
          correct: 1,
          teach: 'Like Priya\'s bird feeder: every failure teaches the next version.',
        },
        {
          kind: 'choice',
          id: 'g3_think_20_d',
          prompt: 'What is a good way to test an invention?',
          options: ['Assume it works', 'Try it in the real situation and watch what happens', 'Sell it fast', 'Never test'],
          correct: 1,
          teach: 'Reality is the honest tester. Watch closely what actually happens.',
        },
        {
          kind: 'speak',
          id: 'g3_think_20_e',
          prompt: 'Name a problem in your daily life an invention could fix.',
          accept: ['my', 'i', 'the', 'when', 'lost', 'forget', 'tangled', 'heavy'],
          sampleAnswer: 'My headphones always tangle in my bag.',
          teach: 'You just found a seed. Water it with ideas.',
        },
      ],
    },
  },
  {
    id: 'g3_think_21',
    subject: 'thinking',
    grade: 3,
    title: 'The Memory Workshop',
    blurb: 'Tricks for making your brain keep what you give it.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_21_a',
          prompt: 'Which is easier to remember?',
          options: ['A random word list', 'A story connecting the words', 'Nothing is memorable', 'Numbers only'],
          correct: 1,
          teach: 'Brains love stories. Weaving items into a tale is an ancient memory trick.',
        },
        {
          kind: 'choice',
          id: 'g3_think_21_b',
          prompt: 'To spell "because": Big Elephants Can Always Understand Small Elephants. This trick is called...',
          options: ['Cheating', 'A mnemonic — a memory helper', 'A riddle', 'A poem'],
          correct: 1,
          teach: 'Mnemonics turn hard-to-hold facts into easy-to-hold sentences.',
        },
        {
          kind: 'choice',
          id: 'g3_think_21_c',
          prompt: 'Cramming once versus practicing a little daily. Which sticks longer?',
          options: ['Cramming', 'A little daily', 'Both equal', 'Neither works'],
          correct: 1,
          teach: 'Spaced practice wins every time. Your multiplication stars use exactly this.',
        },
        {
          kind: 'speak',
          id: 'g3_think_21_d',
          prompt: 'You must remember: milk, eggs, bread. Make a tiny story or picture connecting them.',
          accept: ['the', 'a', 'milk', 'egg', 'bread', 'i imagine'],
          sampleAnswer: 'An egg drinking milk on a slice of bread like a raft.',
          teach: 'The sillier the picture, the harder it sticks. Silly is memory glue.',
        },
        {
          kind: 'choice',
          id: 'g3_think_21_e',
          prompt: 'Why does teaching something to someone else help YOU remember it?',
          options: ['It does not', 'Explaining forces your brain to organize it fully', 'Talking is loud', 'They remember for you'],
          correct: 1,
          teach: 'To explain clearly you must truly understand. Teaching is learning twice.',
        },
      ],
    },
  },
  {
    id: 'g3_think_22',
    subject: 'thinking',
    grade: 3,
    title: 'Trade-Off Corner',
    blurb: 'Every choice costs the road not taken.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_22_a',
          prompt: 'You have $5. The toy costs $5. The book costs $5. Buying the toy means...',
          options: ['You get both', 'The book is the cost of choosing the toy', 'Money grows back', 'Books are free'],
          correct: 1,
          teach: 'Every choice has a hidden price: the thing you did not choose.',
        },
        {
          kind: 'choice',
          id: 'g3_think_22_b',
          prompt: 'Saturday: birthday party AND championship game, same time. This is called...',
          options: ['Good luck', 'A trade-off — choosing means losing one', 'A double win', 'A mistake'],
          correct: 1,
          teach: 'Trade-offs are not failures. They are what real choices look like.',
        },
        {
          kind: 'speak',
          id: 'g3_think_22_c',
          prompt: 'Staying up late to play means what trade-off tomorrow?',
          accept: ['tired', 'being tired', 'sleepy', 'no energy', 'grumpy', 'hard to wake'],
          sampleAnswer: 'Being tired and grumpy tomorrow.',
          teach: 'Tonight borrows from tomorrow. Good deciders see both days at once.',
        },
        {
          kind: 'choice',
          id: 'g3_think_22_d',
          prompt: 'A bigger backpack carries more but is heavier. Choosing backpack size means balancing...',
          options: ['Color and price', 'Space against weight', 'Nothing', 'Zippers'],
          correct: 1,
          teach: 'More of one good thing often means less of another. Designers juggle this daily.',
        },
        {
          kind: 'choice',
          id: 'g3_think_22_e',
          prompt: 'Wise deciders handle trade-offs by...',
          options: ['Pretending they do not exist', 'Naming what each choice truly costs, then picking', 'Always refusing to choose', 'Flipping out'],
          correct: 1,
          teach: 'Name the costs out loud, then choose with open eyes. That is mature deciding.',
        },
      ],
    },
  },
  {
    id: 'g3_think_23',
    subject: 'thinking',
    grade: 3,
    title: 'The Category Shuffle',
    blurb: 'One thing can live in many boxes at once.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_23_a',
          prompt: 'A tomato is botanically a fruit AND used as a vegetable in cooking. How?',
          options: ['Impossible', 'Different systems sort by different rules', 'Tomatoes are confused', 'Someone lied'],
          correct: 1,
          teach: 'Science sorts by seeds; kitchens sort by flavor. Same tomato, two true boxes.',
        },
        {
          kind: 'choice',
          id: 'g3_think_23_b',
          prompt: 'Sort these by SIZE and "whale, mouse" splits one way. Sort by HABITAT and...',
          options: ['Nothing changes', 'Whale joins fish-neighbors; mouse joins land animals', 'Sorting breaks', 'Mice swim'],
          correct: 1,
          teach: 'Change the sorting rule, change the groups. Categories are tools, not truths.',
        },
        {
          kind: 'speak',
          id: 'g3_think_23_c',
          prompt: 'Name two different groups YOU belong to at the same time.',
          accept: ['family', 'class', 'team', 'school', 'club', 'my', 'i am'],
          sampleAnswer: 'My family and my soccer team.',
          teach: 'You live in many boxes at once: family, class, team, neighborhood. All true together.',
        },
        {
          kind: 'choice',
          id: 'g3_think_23_d',
          prompt: 'A bat has wings but feeds milk to its babies. Scientists call it...',
          options: ['A bird, because wings', 'A mammal, because milk is the deciding rule', 'A fish', 'Unsortable'],
          correct: 1,
          teach: 'Scientists pick ONE deciding rule (milk = mammal) so every animal gets exactly one home.',
        },
        {
          kind: 'choice',
          id: 'g3_think_23_e',
          prompt: 'Why do libraries sort books by topic instead of color?',
          options: ['Color is prettier', 'Topic-sorting helps people FIND what they need', 'Books have no color', 'No reason'],
          correct: 1,
          teach: 'Good categories serve their users. Sorting is design.',
        },
      ],
    },
  },
  {
    id: 'g3_think_24',
    subject: 'thinking',
    grade: 3,
    title: 'Small Change, Big Ending',
    blurb: 'Tiny causes can snowball. Watch them roll.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_24_a',
          prompt: 'One tiny pinch of salt per cup of river water became...',
          options: ['Nothing', 'The salty ocean, over billions of years', 'Fresh lakes', 'Rain'],
          correct: 1,
          teach: 'You read this one! Tiny plus forever equals enormous.',
        },
        {
          kind: 'choice',
          id: 'g3_think_24_b',
          prompt: 'Reading 10 minutes nightly for a year is about 60 hours. What is that like?',
          options: ['Barely anything', 'Dozens of finished books', 'A wasted year', 'One comic'],
          correct: 1,
          teach: 'Ten little minutes, compounded, becomes a shelf of books.',
        },
        {
          kind: 'speak',
          id: 'g3_think_24_c',
          prompt: 'A snowball rolling downhill grows. What everyday habit works like that?',
          accept: ['practice', 'saving', 'reading', 'exercise', 'kindness', 'learning', 'brushing'],
          sampleAnswer: 'Saving a little money every week.',
          teach: 'Habits are snowballs. Pick their direction carefully.',
        },
        {
          kind: 'choice',
          id: 'g3_think_24_d',
          prompt: 'One kid picks up litter daily; the neighbor copies; then five more. This is...',
          options: ['Coincidence', 'A ripple effect — actions spreading outward', 'Impossible', 'Littering'],
          correct: 1,
          teach: 'Wangari\'s seven trees became thirty million the same way.',
        },
        {
          kind: 'choice',
          id: 'g3_think_24_e',
          prompt: 'A leaking tank got painted instead of fixed. The lesson about small problems?',
          options: ['Paint works', 'Handle them early, before they compound into disasters', 'Ignore them', 'Tanks are bad'],
          correct: 1,
          teach: 'The molasses flood started as drips. Small and ignored grows large and unignorable.',
        },
      ],
    },
  },
  {
    id: 'g3_think_25',
    subject: 'thinking',
    grade: 3,
    title: 'The Question Forge',
    blurb: 'Great questions are tools. Learn to make sharp ones.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_25_a',
          prompt: 'Which question opens the BIGGEST conversation?',
          options: ['"Is your dog brown?"', '"What is the strangest thing your dog does?"', '"Dog?"', '"Is it Tuesday?"'],
          correct: 1,
          teach: 'Yes/no questions close doors; what/how/why questions open them.',
        },
        {
          kind: 'choice',
          id: 'g3_think_25_b',
          prompt: 'Your experiment: does sunlight help plants? Which question sharpens it?',
          options: ['"Are plants nice?"', '"How much taller grows a sunny plant than a shaded one in 2 weeks?"', '"Why is green?"', '"Do plants sleep?"'],
          correct: 1,
          teach: 'Sharp questions name what to measure and when. Vague in, vague out.',
        },
        {
          kind: 'speak',
          id: 'g3_think_25_c',
          prompt: 'Turn this dull question into a better one: "Was your day good?"',
          accept: ['what was', 'what happened', 'best part', 'favorite', 'tell me about', 'how did'],
          sampleAnswer: 'What was the best part of your day?',
          teach: 'You forged it sharper. Specific questions get real answers.',
        },
        {
          kind: 'choice',
          id: 'g3_think_25_d',
          prompt: 'A scientist\'s most useful question after ANY answer is...',
          options: ['"Can I go home?"', '"How do we know — and what would change our minds?"', '"Who agrees?"', '"Is it lunch?"'],
          correct: 1,
          teach: 'Evidence in, evidence out. Science is organized question-asking.',
        },
        {
          kind: 'speak',
          id: 'g3_think_25_e',
          prompt: 'Ask the most interesting question you can about the ocean.',
          accept: ['why', 'how', 'what', 'where', 'do', 'is', 'can'],
          sampleAnswer: 'How do deep-sea creatures find each other in total darkness?',
          teach: 'Questions like that have launched a thousand expeditions. Keep forging.',
        },
      ],
    },
  },
  {
    id: 'g3_think_26',
    subject: 'thinking',
    grade: 3,
    title: 'The Perspective Swap',
    blurb: 'Step into other shoes. The view changes everything.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_26_a',
          prompt: 'From orbit, Mae Jemison saw Earth without borders. Distance changed her...',
          options: ['Eyesight', 'Perspective — how she saw the whole world', 'Spacesuit', 'Nothing'],
          correct: 1,
          teach: 'Same planet, new vantage point, transformed understanding.',
        },
        {
          kind: 'choice',
          id: 'g3_think_26_b',
          prompt: 'The new kid stands alone at recess. From THEIR shoes, the playground probably feels...',
          options: ['Fun and easy', 'Big, loud, and lonely', 'Small', 'Familiar'],
          correct: 1,
          teach: 'Imagining their view is the first step of kindness.',
        },
        {
          kind: 'speak',
          id: 'g3_think_26_c',
          prompt: 'Your little cousin fears the vacuum cleaner. From their tiny view, why might it be scary?',
          accept: ['loud', 'big', 'it roars', 'huge', 'noisy', 'it chases'],
          sampleAnswer: 'It is huge and roaring and chases them.',
          teach: 'From two feet tall, a vacuum is a roaring monster. Perspective explains "silly" fears.',
        },
        {
          kind: 'choice',
          id: 'g3_think_26_d',
          prompt: 'In an argument, before answering, a strong thinker first...',
          options: ['Talks louder', 'Tries to state the OTHER side\'s view fairly', 'Walks away', 'Wins'],
          correct: 1,
          teach: 'If you can say their view so well they nod — now the real conversation begins.',
        },
        {
          kind: 'choice',
          id: 'g3_think_26_e',
          prompt: 'Sena painted what the mountain-painters could not see. Her secret was...',
          options: ['Better brushes', 'A different perspective — looking where no one looked', 'Luck', 'Bigger canvas'],
          correct: 1,
          teach: 'Forty saw the mountain. One turned around. Perspective is a choice.',
        },
      ],
    },
  },
  {
    id: 'g3_think_27',
    subject: 'thinking',
    grade: 3,
    title: 'The Improvement Loop',
    blurb: 'Try, observe, adjust, repeat. The engine of getting better.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g3_think_27_a',
          prompt: 'Order the improvement loop.',
          items: ['Try it', 'See what happened', 'Adjust one thing', 'Try again'],
          teach: 'Try, observe, adjust, repeat. Every skill you own came through this loop.',
        },
        {
          kind: 'choice',
          id: 'g3_think_27_b',
          prompt: 'Your paper airplane nose-dives. The loop says next you...',
          options: ['Quit airplanes', 'Change ONE thing — maybe the wing fold — and test', 'Change everything at once', 'Blame the paper'],
          correct: 1,
          teach: 'One change at a time — or you cannot tell which change mattered.',
        },
        {
          kind: 'choice',
          id: 'g3_think_27_c',
          prompt: 'Why did Amara\'s teacher want one hundred tries?',
          options: ['To waste time', 'Each try is one lap of the improvement loop', 'She was mean', 'Violins need warming'],
          correct: 1,
          teach: 'A hundred tries is a hundred loops. The bad notes were the road.',
        },
        {
          kind: 'speak',
          id: 'g3_think_27_d',
          prompt: 'Your sandcastle tower keeps collapsing. Using the loop, what ONE thing might you adjust first?',
          accept: ['wetter sand', 'water', 'wider base', 'pack it', 'smaller', 'base'],
          sampleAnswer: 'Make the base wider, like Ruby\'s bridge.',
          teach: 'One smart adjustment, then test. That is engineering in a sandbox.',
        },
        {
          kind: 'choice',
          id: 'g3_think_27_e',
          prompt: 'The loop never truly ends because...',
          options: ['Nothing works ever', 'There is always a next level of better', 'Loops are circles', 'Teachers say so'],
          correct: 1,
          teach: 'Masters still loop. That is what makes them masters.',
        },
      ],
    },
  },
  {
    id: 'g3_think_28',
    subject: 'thinking',
    grade: 3,
    title: 'The Emotion Decoder',
    blurb: 'Feelings carry information. Learn to read the signal.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_28_a',
          prompt: 'Feeling nervous before a performance usually means...',
          options: ['You will fail', 'You care about doing well', 'You should quit', 'Something is broken'],
          correct: 1,
          teach: 'Nerves are care wearing a scary mask. Even professionals feel them.',
        },
        {
          kind: 'choice',
          id: 'g3_think_28_b',
          prompt: 'You feel angry. The wise FIRST move is...',
          options: ['Yell immediately', 'Pause and breathe before choosing what to do', 'Break something', 'Hide forever'],
          correct: 1,
          teach: 'The pause puts YOU in charge of the anger instead of the reverse.',
        },
        {
          kind: 'speak',
          id: 'g3_think_28_c',
          prompt: 'Ivy was scared of the night sound but checked anyway. What is that called?',
          accept: ['brave', 'courage', 'being brave', 'bravery'],
          sampleAnswer: 'Being brave — scared and doing it anyway.',
          teach: 'Courage is not the absence of fear. It is action with fear aboard.',
        },
        {
          kind: 'choice',
          id: 'g3_think_28_d',
          prompt: 'Your friend is quiet and sitting alone, which is unusual. The signal might mean...',
          options: ['Nothing ever', 'Something may be wrong — worth gently asking', 'They hate you', 'Quiet is a rule'],
          correct: 1,
          teach: 'Changes in behavior are signals. Kind people read them and check in.',
        },
        {
          kind: 'choice',
          id: 'g3_think_28_e',
          prompt: 'Hazel felt hungry AND full at once — stomach empty, heart full. Feelings can...',
          options: ['Only come one at a time', 'Mix and even contradict, both true at once', 'Never mix', 'Be ignored'],
          correct: 1,
          teach: 'Two kinds of hungry, remember? People hold mixed feelings all the time. Naming both helps.',
        },
      ],
    },
  },
  {
    id: 'g3_think_29',
    subject: 'thinking',
    grade: 3,
    title: 'The Systems Safari',
    blurb: 'Everything connects to something. Follow the threads.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_29_a',
          prompt: 'Remove all the bees from a garden. What else changes?',
          options: ['Nothing', 'Fewer flowers get pollinated, so fewer seeds and fruits', 'More honey', 'Faster growth'],
          correct: 1,
          teach: 'Pull one thread, the web moves. Bees connect to flowers connect to fruit connect to us.',
        },
        {
          kind: 'choice',
          id: 'g3_think_29_b',
          prompt: 'A school is a system. If the bell breaks, what ripples?',
          options: ['Nothing', 'Classes run long, lunches collide, buses wait', 'School improves', 'Only silence'],
          correct: 1,
          teach: 'One small part, many connections. Systems thinking sees the ripples in advance.',
        },
        {
          kind: 'speak',
          id: 'g3_think_29_c',
          prompt: 'The forest\'s trees share food through fungus threads. What happens to seedlings if the threads are destroyed?',
          accept: ['they starve', 'no food', 'they die', 'they get weaker', 'no help from big trees'],
          sampleAnswer: 'Shaded seedlings lose their food deliveries and weaken.',
          teach: 'Hidden connections do real work. Breaking them breaks things you cannot see.',
        },
        {
          kind: 'choice',
          id: 'g3_think_29_d',
          prompt: 'Your body is a system. Skipping sleep affects...',
          options: ['Only nighttime', 'Focus, mood, memory, and energy the whole next day', 'Nothing', 'Only dreams'],
          correct: 1,
          teach: 'Sleep connects to everything downstream. Systems do not keep secrets forever.',
        },
        {
          kind: 'choice',
          id: 'g3_think_29_e',
          prompt: 'Before changing part of any system, wise people ask...',
          options: ['"What else does this touch?"', '"Who cares?"', '"Is it Friday?"', 'Nothing'],
          correct: 0,
          teach: 'The connections question. It has prevented a thousand disasters and could prevent more.',
        },
      ],
    },
  },
  {
    id: 'g3_think_30',
    subject: 'thinking',
    grade: 3,
    title: 'The Thinker\'s Summit',
    blurb: 'The final climb. Every tool on your belt, one last expedition.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_30_a',
          prompt: 'Three switches, one lamp upstairs: turn on switch 1 for a minute, turn it off, turn on switch 2, go up. The bulb is warm but off. Which switch works the lamp?',
          options: ['Switch 1 — warmth is its fingerprint', 'Switch 2', 'Switch 3', 'Impossible'],
          correct: 0,
          teach: 'The warm bulb remembers switch 1. Evidence outlives the event — detective physics!',
        },
        {
          kind: 'choice',
          id: 'g3_think_30_b',
          prompt: 'A claim, an ad, and an expert study disagree about a toy\'s safety. Weigh them:',
          options: ['Ad wins — loudest', 'Study wins — tested evidence beats selling and shouting', 'Claim wins — first heard', 'Coin flip'],
          correct: 1,
          teach: 'Source-checking, trade-offs, evidence — you just used three tools at once.',
        },
        {
          kind: 'order',
          id: 'g3_think_30_c',
          prompt: 'Order a full thinking journey.',
          items: ['Notice something odd', 'Ask a sharp question', 'Gather evidence', 'Draw a careful conclusion'],
          teach: 'Notice, question, gather, conclude. That is the whole scientific adventure in four steps.',
        },
        {
          kind: 'speak',
          id: 'g3_think_30_d',
          prompt: 'A riddle for the summit: the person who makes it sells it; the person who buys it never uses it; the person who uses it never sees it. What is it?',
          accept: ['coffin', 'a coffin', 'casket', 'a casket'],
          sampleAnswer: 'A coffin.',
          teach: 'The hardest riddle in all the stars — solved. Told you the climb was worth it.',
        },
        {
          kind: 'speak',
          id: 'g3_think_30_e',
          prompt: 'Thirty thinking stars, complete. Which tool will you actually use this week — and on what?',
          accept: ['i will', 'the', 'estimation', 'questions', 'evidence', 'perspective', 'loop', 'trade'],
          sampleAnswer: 'The improvement loop, on my free throws.',
          teach: 'Tools rust unused. You have a full belt now — build something with it. I am so proud of you.',
        },
      ],
    },
  },
];
