import type { Star } from '../../types';

/**
 * Grade 3 critical thinking — 10 stars.
 *
 * Deduction, fact versus opinion, analogies, estimation, and spotting bad
 * reasoning. Several stars deliberately include claims that sound convincing
 * and are wrong, because recognising that is the actual skill.
 */

export const grade3Thinking: Star[] = [
  {
    id: 'g3_think_01',
    subject: 'thinking',
    grade: 3,
    title: 'Working It Out',
    blurb: 'Every clue you need is in the words. Nothing is hidden.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_01_a',
          prompt: 'Mia is older than Priya. Priya is older than Zoe. Zoe is older than Ana. Who is the youngest?',
          options: ['Mia', 'Priya', 'Zoe', 'Ana'],
          correct: 3,
          teach: 'Ana. You put all four in order from one sentence at a time.',
          hint: 'Line them up oldest to youngest as you read.',
        },
        {
          kind: 'choice',
          id: 'g3_think_01_b',
          prompt: 'All the books on the top shelf are blue. This book is red. What do we know?',
          options: [
            'It is on the top shelf',
            'It is not on the top shelf',
            'It is the only red book',
            'We cannot know anything',
          ],
          correct: 1,
          teach: 'If every top-shelf book is blue, a red book cannot be up there. That is real logic.',
        },
        {
          kind: 'choice',
          id: 'g3_think_01_c',
          prompt: 'Three girls each have one pet: a cat, a dog, a bird. Naomi has no fur on her clothes. Clara\'s pet barks. Who has the bird?',
          options: ['Naomi', 'Clara', 'The third girl', 'Cannot tell'],
          correct: 0,
          teach: 'Clara has the dog. Naomi has no fur, so not the cat — she has the bird.',
          hint: 'Start with the clue that names an animal directly.',
        },
        {
          kind: 'speak',
          id: 'g3_think_01_d',
          prompt: 'Every student who finished the project got a sticker. Esther did not get a sticker. What can we conclude?',
          accept: [
            'she did not finish', 'esther did not finish', 'she did not finish the project',
            'she didnt finish', 'she has not finished', 'she did not finish it',
          ],
          sampleAnswer: 'Esther did not finish the project.',
          teach: 'Exactly right. And notice — we know nothing about WHY. Logic tells us what, not why.',
        },
        {
          kind: 'choice',
          id: 'g3_think_01_e',
          prompt: 'The window is open and the papers are on the floor. What is the most reasonable conclusion?',
          options: [
            'Someone threw the papers down',
            'Wind from the window blew them off',
            'The papers fell by themselves',
            'A bird came in',
          ],
          correct: 1,
          teach: 'The most reasonable, given both facts together. Not the only possible one — the most reasonable.',
        },
        {
          kind: 'speak',
          id: 'g3_think_01_f',
          prompt: 'The ground is wet, but the sky is clear and the roof is completely dry. What might explain it?',
          accept: [
            'sprinkler', 'a sprinkler', 'someone watered', 'a hose', 'watering',
            'someone washed', 'a sprinkler was on', 'it was watered',
          ],
          sampleAnswer: 'A sprinkler or hose, because rain would have wet the roof too.',
          hint: 'Why does the dry roof matter?',
          teach: 'The dry roof rules out rain. Noticing what is MISSING is often the sharpest move.',
        },
      ],
    },
  },
  {
    id: 'g3_think_02',
    subject: 'thinking',
    grade: 3,
    title: 'Fact or Opinion',
    blurb: 'One of these can be checked. The other can only be argued.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_02_a',
          prompt: 'Fact or opinion? "The Pacific is the largest ocean on Earth."',
          options: ['Fact', 'Opinion'],
          correct: 0,
          teach: 'Fact. You can measure it and check.',
        },
        {
          kind: 'choice',
          id: 'g3_think_02_b',
          prompt: 'Fact or opinion? "The ocean is the most beautiful place in the world."',
          options: ['Fact', 'Opinion'],
          correct: 1,
          teach: 'Opinion. There is no measuring instrument for beautiful.',
        },
        {
          kind: 'choice',
          id: 'g3_think_02_c',
          prompt: 'Fact or opinion? "Everyone should learn to type."',
          options: ['Fact', 'Opinion'],
          correct: 1,
          teach: 'Opinion — a reasonable one, but the word "should" is the giveaway.',
        },
        {
          kind: 'choice',
          id: 'g3_think_02_d',
          prompt: 'Fact or opinion? "Water freezes at zero degrees Celsius."',
          options: ['Fact', 'Opinion'],
          correct: 0,
          teach: 'Fact. Anyone can test it and get the same result.',
        },
        {
          kind: 'speak',
          id: 'g3_think_02_e',
          prompt: 'Say a fact about yourself — something anyone could check.',
          accept: ['i am', 'i have', 'my', 'i live', 'im'],
          sampleAnswer: 'I am in third grade.',
          teach: 'That is checkable, so it is a fact.',
        },
        {
          kind: 'speak',
          id: 'g3_think_02_f',
          prompt: 'Now say an opinion you hold — something someone could disagree with.',
          accept: ['i think', 'i like', 'i love', 'the best', 'i believe', 'is better', 'i prefer'],
          sampleAnswer: 'I think summer is the best season.',
          teach: 'Opinions are not weaker than facts. They are just a different kind of claim.',
        },
      ],
    },
  },
  {
    id: 'g3_think_03',
    subject: 'thinking',
    grade: 3,
    title: 'That Argument Has a Hole',
    blurb: 'These all sound convincing. Every one of them is broken. Find the crack.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_03_a',
          prompt: '"Everyone in my class has a scooter, so scooters must be the most popular toy in the country." What is wrong?',
          options: [
            'Nothing, it is correct',
            'One class is too small to speak for the whole country',
            'Scooters are not toys',
            'Classes do not have opinions',
          ],
          correct: 1,
          teach: 'A small group cannot stand in for everyone. That is called a hasty generalization.',
        },
        {
          kind: 'choice',
          id: 'g3_think_03_b',
          prompt: '"I wore my red socks and we won the game. My socks made us win." What is wrong?',
          options: [
            'Red is not a lucky color',
            'Two things happening together does not mean one caused the other',
            'The socks were not clean',
            'Nothing is wrong',
          ],
          correct: 1,
          teach: 'Together in time is not the same as one causing the other. Adults get this wrong constantly.',
        },
        {
          kind: 'choice',
          id: 'g3_think_03_c',
          prompt: '"You either love math or you hate it." What is wrong?',
          options: [
            'Math is not lovable',
            'It ignores everything in between',
            'Nobody hates math',
            'It is too short',
          ],
          correct: 1,
          teach: 'Only two options offered when there are many. You can find math interesting and hard at once.',
        },
        {
          kind: 'speak',
          id: 'g3_think_03_d',
          prompt: '"My older sister says the moon is made of ice, and she is eleven, so it must be true." What is wrong with that reasoning?',
          accept: [
            'being older does not make you right', 'age does not mean correct',
            'she could be wrong', 'older does not mean right', 'she might be wrong',
            'that is not evidence', 'being eleven does not prove it',
            'you need evidence',
          ],
          sampleAnswer: 'Being older does not make someone right. You need evidence, not just age.',
          teach: 'Who said it is not evidence for whether it is true. Ask how they know.',
        },
        {
          kind: 'choice',
          id: 'g3_think_03_e',
          prompt: '"This cereal is the healthiest, because the box says so." What is wrong?',
          options: [
            'The box wants to sell you cereal, so it is not a neutral source',
            'Cereal is never healthy',
            'Boxes cannot have writing',
            'Nothing is wrong',
          ],
          correct: 0,
          teach: 'Always ask who benefits from you believing a claim.',
        },
        {
          kind: 'speak',
          id: 'g3_think_03_f',
          prompt: '"It rained the last three Saturdays, so it will definitely rain this Saturday." What is the problem?',
          accept: [
            'it might not', 'that does not mean it will', 'three times is not proof',
            'you cannot know', 'the past does not decide', 'it is not definite',
            'weather changes', 'that is not proof',
          ],
          sampleAnswer: 'Three times in a row does not guarantee the next one.',
          teach: 'A pattern can be a good hint. The word "definitely" is what breaks this one.',
        },
      ],
    },
  },
  {
    id: 'g3_think_04',
    subject: 'thinking',
    grade: 3,
    title: 'This Is Like That',
    blurb: 'Analogies. Find the relationship first, then apply it.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_04_a',
          prompt: 'Bird is to nest as bee is to ___?',
          options: ['Flower', 'Hive', 'Honey', 'Sky'],
          correct: 1,
          teach: 'Hive. The relationship is "creature to the home it builds."',
        },
        {
          kind: 'choice',
          id: 'g3_think_04_b',
          prompt: 'Hot is to cold as day is to ___?',
          options: ['Sun', 'Morning', 'Night', 'Week'],
          correct: 2,
          teach: 'Night. The relationship is opposites.',
        },
        {
          kind: 'choice',
          id: 'g3_think_04_c',
          prompt: 'Author is to book as composer is to ___?',
          options: ['Piano', 'Music', 'Orchestra', 'Concert'],
          correct: 1,
          teach: 'Music. The relationship is "maker to the thing they make."',
          hint: 'A piano is a tool, not the creation.',
        },
        {
          kind: 'choice',
          id: 'g3_think_04_d',
          prompt: 'Petal is to flower as ___ is to book?',
          options: ['Page', 'Library', 'Reader', 'Story'],
          correct: 0,
          teach: 'Page. The relationship is "one part to the whole."',
        },
        {
          kind: 'speak',
          id: 'g3_think_04_e',
          prompt: 'Telescope is to far away as microscope is to what?',
          accept: ['small', 'tiny', 'close', 'very small', 'little things', 'small things'],
          sampleAnswer: 'Very small things.',
          teach: 'Each tool makes visible what our eyes cannot reach — one by distance, one by size.',
        },
        {
          kind: 'speak',
          id: 'g3_think_04_f',
          prompt: 'Practice is to skill as water is to what?',
          accept: ['plant', 'a plant', 'growth', 'flower', 'plants', 'growing'],
          sampleAnswer: 'A plant.',
          hint: 'What does the first thing make possible in the second?',
          teach: 'Both are the thing you supply steadily so something else can grow.',
        },
      ],
    },
  },
  {
    id: 'g3_think_05',
    subject: 'thinking',
    grade: 3,
    title: 'About How Many',
    blurb: 'Estimation is not guessing. It is reasoning with numbers you already have.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_05_a',
          prompt: 'About how many days are in three years?',
          options: ['About 100', 'About 400', 'About 1,100', 'About 5,000'],
          correct: 2,
          teach: 'About 1,100. Three lots of 365 is a bit under 1,100.',
          hint: 'Round 365 to 400 and multiply, then adjust down.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_b',
          prompt: 'Is 48 + 51 closer to 50 or to 100?',
          options: ['50', '100'],
          correct: 1,
          teach: '100. Both numbers are near 50, and two 50s make 100.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_c',
          prompt: 'A book has 12 chapters, each about 10 pages. About how long is it?',
          options: ['About 22 pages', 'About 120 pages', 'About 1,200 pages', 'About 60 pages'],
          correct: 1,
          teach: '120 pages. Twelve tens.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_d',
          prompt: 'Which is the best estimate for how tall a classroom door is?',
          options: ['1 meter', '2 meters', '5 meters', '10 meters'],
          correct: 1,
          teach: 'About 2 meters — a bit taller than a grown-up.',
        },
        {
          kind: 'speak',
          id: 'g3_think_05_e',
          prompt: 'Without adding exactly: is 19 + 22 + 18 more or less than 60?',
          accept: ['less', 'less than 60', 'under', 'under 60', 'no', 'less than sixty'],
          sampleAnswer: 'Less than 60.',
          hint: 'Round each one to the nearest ten first.',
          teach: 'Less — about 59. Rounding to 20 + 20 + 20 gets you there in your head.',
        },
        {
          kind: 'choice',
          id: 'g3_think_05_f',
          prompt: 'Someone says a cat weighs 400 kilograms. What should you think?',
          options: [
            'That sounds about right',
            'That cannot be right — that is heavier than a horse',
            'Cats cannot be weighed',
            'It depends on the cat',
          ],
          correct: 1,
          teach: 'Estimation is a lie detector. When a number feels impossible, check it.',
        },
      ],
    },
  },
  {
    id: 'g3_think_06',
    subject: 'thinking',
    grade: 3,
    title: 'What Is Missing',
    blurb: 'Sometimes the most important information is the information you were not given.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_06_a',
          prompt: '"Buy this bike — nine out of ten riders recommend it!" What would you want to know?',
          options: [
            'The color of the bike',
            'How many riders were asked, and who asked them',
            'The name of the shop',
            'Nothing else',
          ],
          correct: 1,
          teach: 'Nine out of ten sounds strong until you learn only ten people were asked — by the seller.',
        },
        {
          kind: 'choice',
          id: 'g3_think_06_b',
          prompt: '"Our team scored more goals this season than last." What is missing?',
          options: [
            'How many games were played each season',
            'The color of the uniforms',
            'The name of the coach',
            'Nothing',
          ],
          correct: 0,
          teach: 'More goals across twice as many games is not an improvement at all.',
        },
        {
          kind: 'speak',
          id: 'g3_think_06_c',
          prompt: 'A sign says "Now 50% off!" What would you need to know to tell if it is a good deal?',
          accept: [
            'the original price', 'the price before', 'what it cost before',
            'the old price', 'how much it was', 'the regular price', 'the first price',
          ],
          sampleAnswer: 'The original price, before the discount.',
          teach: 'Half off a price they just doubled is not a discount. Always ask "off what?"',
        },
        {
          kind: 'choice',
          id: 'g3_think_06_d',
          prompt: 'A friend says "the movie was terrible, do not watch it." What is worth asking?',
          options: [
            'What they usually like, and why they disliked it',
            'How long the movie was',
            'Where they watched it',
            'Nothing — just trust them',
          ],
          correct: 0,
          teach: 'A review tells you about the reviewer as much as the thing reviewed.',
        },
        {
          kind: 'speak',
          id: 'g3_think_06_e',
          prompt: '"Most students at our school prefer pizza." How could you check whether that is true?',
          accept: [
            'ask them', 'ask everyone', 'a survey', 'take a vote', 'ask the students',
            'ask a lot of people', 'count', 'survey', 'ask lots of students',
          ],
          sampleAnswer: 'Ask a lot of students, not just your friends.',
          teach: 'And ask a spread of them. Asking only your own table gives you your table\'s answer.',
        },
      ],
    },
  },
  {
    id: 'g3_think_07',
    subject: 'thinking',
    grade: 3,
    title: 'Puzzles That Bite Back',
    blurb: 'Read each of these twice. The obvious answer is wrong on purpose.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g3_think_07_a',
          prompt: 'A farmer has 17 sheep. All but 9 run away. How many are left?',
          accept: ['9', 'nine'],
          sampleAnswer: '9',
          hint: 'Read "all but 9" very carefully.',
          teach: 'Nine. "All but 9 ran away" means 9 stayed. Most people say 8.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_b',
          prompt: 'You are in a race and you pass the person in second place. What place are you in now?',
          accept: ['second', '2nd', 'second place', '2'],
          sampleAnswer: 'Second place.',
          hint: 'You took their spot, not the spot ahead of them.',
          teach: 'Second. If you pass the person in second, you become second.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_c',
          prompt: 'A doctor gives you 3 pills and says take one every half hour. How long until they are gone?',
          accept: ['1 hour', 'one hour', '60 minutes', 'an hour', '60'],
          sampleAnswer: 'One hour.',
          hint: 'When do you take the first one?',
          teach: 'One hour. Take the first immediately — only two gaps of half an hour follow.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_d',
          prompt: 'Some months have 31 days. Some have 30. How many have 28 days?',
          accept: ['12', 'twelve', 'all', 'all of them', 'all twelve'],
          sampleAnswer: 'All twelve.',
          hint: 'The question does not say "only 28 days."',
          teach: 'All twelve. Every month has 28 days, and most have a few more.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_e',
          prompt: 'If a red house is made of red bricks and a blue house of blue bricks, what is a greenhouse made of?',
          accept: ['glass', 'made of glass'],
          sampleAnswer: 'Glass.',
          teach: 'Glass. The pattern set you up, and the last one does not follow it.',
        },
        {
          kind: 'speak',
          id: 'g3_think_07_f',
          prompt: 'Which weighs more: a kilogram of feathers or a kilogram of stones?',
          accept: ['same', 'the same', 'equal', 'neither', 'they weigh the same', 'both the same'],
          sampleAnswer: 'They weigh the same.',
          teach: 'The same. A kilogram is a kilogram. Feathers just take up far more space.',
        },
      ],
    },
  },
  {
    id: 'g3_think_08',
    subject: 'thinking',
    grade: 3,
    title: 'Breaking It Down',
    blurb: 'Big problems are just small problems stacked up.',
    minutes: 13,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g3_think_08_a',
          prompt: 'Put these steps in order for planning a birthday party.',
          items: [
            'Decide the date and who to invite',
            'Send the invitations',
            'Buy the food and decorations',
            'Set up on the day',
          ],
          teach: 'You cannot invite people before you pick a date. Order is part of the plan.',
        },
        {
          kind: 'order',
          id: 'g3_think_08_b',
          prompt: 'Put these in order for writing a report about penguins.',
          items: [
            'Decide what you want to find out',
            'Read and take notes',
            'Organise notes into topics',
            'Write the report',
            'Check it for mistakes',
          ],
          teach: 'Notice that writing is fourth, not first. Most of the work happens before the writing.',
        },
        {
          kind: 'choice',
          id: 'g3_think_08_c',
          prompt: 'You have one hour to clean a very messy room. What is the best first step?',
          options: [
            'Start scrubbing the floor',
            'Look around and decide what makes the biggest difference',
            'Organise the bookshelf perfectly',
            'Clean one small corner completely',
          ],
          correct: 1,
          teach: 'Plan before you act. With limited time, choosing what matters most is the real work.',
        },
        {
          kind: 'speak',
          id: 'g3_think_08_d',
          prompt: 'You need 100 cookies for a bake sale and each batch makes 12. About how many batches?',
          accept: ['9', 'nine', '8', 'eight', '8 or 9', 'about 9', 'nine batches'],
          sampleAnswer: 'About 9 batches.',
          hint: '12 times 8 is 96 — is that enough?',
          teach: 'Nine. Eight batches gives 96, which is short, so you round up. Real problems often round up.',
        },
        {
          kind: 'choice',
          id: 'g3_think_08_e',
          prompt: 'Your math homework is very hard. What is the most useful first move?',
          options: [
            'Give up and do something else',
            'Find the easiest problem and start there',
            'Copy someone else\'s answers',
            'Do them in order no matter what',
          ],
          correct: 1,
          teach: 'Starting where you can build momentum is a real strategy, not a shortcut.',
        },
      ],
    },
  },
  {
    id: 'g3_think_09',
    subject: 'thinking',
    grade: 3,
    title: 'Patterns and Rules',
    blurb: 'Find the rule, then use it. The rule is always simpler than it looks.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g3_think_09_a',
          prompt: '2, 4, 8, 16, ... what comes next?',
          accept: ['32', 'thirty two', 'thirty-two'],
          sampleAnswer: '32',
          hint: 'What are you doing to each number to get the next?',
          teach: '32. Each number doubles.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_b',
          prompt: '1, 4, 9, 16, 25, ... what comes next?',
          accept: ['36', 'thirty six', 'thirty-six'],
          sampleAnswer: '36',
          hint: 'Try one times one, two times two, three times three...',
          teach: '36. These are square numbers: 6 times 6.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_c',
          prompt: '100, 90, 81, 73, ... what comes next?',
          accept: ['66', 'sixty six', 'sixty-six'],
          sampleAnswer: '66',
          hint: 'How much is taken away each time? Is it the same amount?',
          teach: '66. The gaps shrink: minus 10, minus 9, minus 8, then minus 7.',
        },
        {
          kind: 'choice',
          id: 'g3_think_09_d',
          prompt: 'A, C, E, G, ... what comes next?',
          options: ['H', 'I', 'J', 'K'],
          correct: 1,
          teach: 'I. The pattern skips a letter each time.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_e',
          prompt: 'A machine turns 3 into 7, and 5 into 11, and 6 into 13. What is the rule?',
          accept: [
            'double plus one', 'times 2 plus 1', 'multiply by 2 and add 1',
            'double it and add one', 'x2 plus 1', 'twice plus one', 'double and add 1',
          ],
          sampleAnswer: 'Double it and add one.',
          hint: 'Try doubling first and see how far off you are.',
          teach: 'Double and add one. Three doubled is six, plus one is seven. It works for all three.',
        },
        {
          kind: 'speak',
          id: 'g3_think_09_f',
          prompt: 'Using that same rule, what does the machine turn 10 into?',
          accept: ['21', 'twenty one', 'twenty-one'],
          sampleAnswer: '21',
          teach: '21. You found a rule and then used it on something new. That is exactly what mathematicians do.',
        },
      ],
    },
  },
  {
    id: 'g3_think_10',
    subject: 'thinking',
    grade: 3,
    title: 'The Puzzle Weaver',
    blurb: 'The last star here. Everything at once, and no hints about which kind is which.',
    minutes: 14,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g3_think_10_a',
          prompt: 'Fact or opinion? "This is the hardest star in the whole app."',
          options: ['Fact', 'Opinion'],
          correct: 1,
          teach: 'Opinion — even when I am the one saying it.',
        },
        {
          kind: 'speak',
          id: 'g3_think_10_b',
          prompt: 'Clara is not the tallest. Naomi is taller than Clara but shorter than Ruby. Who is tallest?',
          accept: ['ruby'],
          sampleAnswer: 'Ruby',
          teach: 'Ruby. The first sentence was a distraction — the second gave you everything.',
        },
        {
          kind: 'choice',
          id: 'g3_think_10_c',
          prompt: 'Pen is to write as ___ is to cut.',
          options: ['Paper', 'Scissors', 'Glue', 'Ruler'],
          correct: 1,
          teach: 'Scissors. Tool to the action it performs.',
        },
        {
          kind: 'speak',
          id: 'g3_think_10_d',
          prompt: 'A shelf holds 6 rows with 8 books in each. About how many books?',
          accept: ['48', 'forty eight', 'forty-eight', 'about 50', '50'],
          sampleAnswer: '48',
          teach: '48. Six eights.',
        },
        {
          kind: 'choice',
          id: 'g3_think_10_e',
          prompt: '"Everyone I asked agreed with me, so I must be right." What is wrong?',
          options: [
            'Nothing is wrong',
            'They may all have been people who already agreed with you',
            'You should ask more loudly',
            'Agreement is impossible',
          ],
          correct: 1,
          teach: 'Who you ask decides what you hear. Seek out someone likely to disagree — that is the real test.',
        },
        {
          kind: 'speak',
          id: 'g3_think_10_f',
          prompt: 'Last one. What is the most useful question to ask when someone tells you something surprising?',
          accept: [
            'how do you know', 'why', 'how do they know', 'what is the evidence',
            'are you sure', 'how do you know that', 'whats the proof', 'where did you hear that',
            'how',
          ],
          sampleAnswer: 'How do you know?',
          teach: '"How do you know?" It is polite, it is short, and it works on almost everything. Carry it with you.',
        },
      ],
    },
  },
];
