import type { Star } from '../../types';
import { buildFlashcardStar, buildVocabStar, type VocabStarSpec } from '../vocabBuilder';

/**
 * Grade 3 vocabulary — 10 stars, 6 words each. Tier-two words: the ones that
 * show up across every subject rather than belonging to just one, which is
 * where vocabulary instruction gives the most return at this age.
 */

const specs: VocabStarSpec[] = [
  {
    id: 'g3_vocab_01',
    grade: 3,
    title: 'Words for Thinking',
    blurb: 'Words that describe what your mind is doing.',
    minutes: 12,
    words: [
      {
        word: 'analyze',
        meaning: 'to look at something closely, piece by piece, to understand it',
        cloze: 'Let us ____ this problem before we try to solve it.',
        decoys: ['to ignore something completely', 'to build something quickly', 'to memorize word for word'],
      },
      {
        word: 'assume',
        meaning: 'to believe something is true without checking it',
        cloze: 'Do not ____ she is upset — go and ask her.',
        decoys: ['to prove with evidence', 'to write down carefully', 'to ask a direct question'],
        note: 'Assuming is not the same as knowing. That gap causes most arguments.',
      },
      {
        word: 'evidence',
        meaning: 'facts that show whether something is true',
        cloze: 'What ____ do you have for that claim?',
        decoys: ['a strong feeling', 'a popular opinion', 'a good guess'],
      },
      {
        word: 'conclude',
        meaning: 'to decide something after thinking it through',
        cloze: 'From the tracks in the snow, we can ____ a deer walked past.',
        decoys: ['to begin an experiment', 'to forget on purpose', 'to ask for help'],
      },
      {
        word: 'perspective',
        meaning: 'the particular way one person sees a thing',
        cloze: 'From her ____, the number looked like a nine.',
        decoys: ['a type of measuring tool', 'a written rule', 'the middle of a story'],
      },
      {
        word: 'reasonable',
        meaning: 'sensible and fair, based on good thinking',
        cloze: 'That is a ____ explanation for the noise.',
        decoys: ['wildly unlikely', 'extremely expensive', 'completely silent'],
      },
    ],
  },
  {
    id: 'g3_vocab_02',
    grade: 3,
    title: 'Words for Describing People',
    blurb: 'Precise words beat vague ones. "Nice" tells me almost nothing.',
    minutes: 12,
    words: [
      {
        word: 'considerate',
        meaning: 'careful about how your actions affect other people',
        cloze: 'It was ____ of her to keep her voice down while he slept.',
        decoys: ['loud and careless', 'good at sports', 'quick to anger'],
      },
      {
        word: 'stubborn',
        meaning: 'refusing to change your mind, even with good reason',
        cloze: 'He was too ____ to admit he had taken a wrong turn.',
        decoys: ['easily convinced', 'always cheerful', 'very forgetful'],
      },
      {
        word: 'determined',
        meaning: 'refusing to give up on something you have decided to do',
        cloze: 'She was ____ to finish the whole book that week.',
        decoys: ['quick to quit', 'unsure of everything', 'happy to be lazy'],
        note: 'Determined and stubborn look similar from outside. The difference is whether you are right.',
      },
      {
        word: 'sincere',
        meaning: 'honest and real in what you say and feel',
        cloze: 'Her apology was ____, and he could tell.',
        decoys: ['fake and pretend', 'shouted loudly', 'written down'],
      },
      {
        word: 'humble',
        meaning: 'not thinking you are better than other people',
        cloze: 'She won every race and stayed ____ about it.',
        decoys: ['bragging constantly', 'very wealthy', 'physically small'],
      },
      {
        word: 'reliable',
        meaning: 'able to be counted on to do what you said',
        cloze: 'He is ____ — if he says he will be there, he will.',
        decoys: ['always changing plans', 'often late', 'good at telling jokes'],
      },
    ],
  },
  {
    id: 'g3_vocab_03',
    grade: 3,
    title: 'Science Words',
    blurb: 'Words that show up in every science book you will ever read.',
    minutes: 12,
    words: [
      {
        word: 'observe',
        meaning: 'to watch carefully and notice details',
        cloze: 'Scientists ____ what happens before they explain why.',
        decoys: ['to guess without looking', 'to build a machine', 'to write a story'],
      },
      {
        word: 'experiment',
        meaning: 'a careful test to find out whether an idea is true',
        cloze: 'They ran an ____ with seeds in space.',
        decoys: ['a firm conclusion', 'a type of report', 'a set of instructions'],
      },
      {
        word: 'predict',
        meaning: 'to say what you think will happen before it does',
        cloze: 'Can you ____ what will happen when we add the water?',
        decoys: ['to describe the past', 'to measure exactly', 'to repeat an action'],
      },
      {
        word: 'absorb',
        meaning: 'to soak something up and take it in',
        cloze: 'The roots ____ water from the soil.',
        decoys: ['to push something away', 'to reflect back', 'to break into pieces'],
      },
      {
        word: 'gradual',
        meaning: 'happening slowly, a little at a time',
        cloze: 'The change in the seasons is ____.',
        decoys: ['instant and sudden', 'never happening', 'happening backwards'],
      },
      {
        word: 'reaction',
        meaning: 'what happens in response to something else',
        cloze: 'Mixing those two caused a bubbling ____.',
        decoys: ['a careful plan', 'a type of container', 'a written record'],
      },
    ],
  },
  {
    id: 'g3_vocab_04',
    grade: 3,
    title: 'Words About Words',
    blurb: 'The words you need to talk about reading and writing.',
    minutes: 12,
    words: [
      {
        word: 'theme',
        meaning: 'the big idea or lesson underneath a story',
        cloze: 'The ____ of that story is that kindness costs something.',
        decoys: ['the name of the main character', 'the number of pages', 'where the story happens'],
      },
      {
        word: 'summarize',
        meaning: 'to tell the main points briefly in your own words',
        cloze: 'Can you ____ the chapter in three sentences?',
        decoys: ['to retell every detail', 'to read it aloud', 'to copy it exactly'],
      },
      {
        word: 'persuade',
        meaning: 'to convince someone to agree with you',
        cloze: 'She wrote a letter to ____ the class to recycle.',
        decoys: ['to describe neutrally', 'to argue with yourself', 'to ask a question'],
      },
      {
        word: 'describe',
        meaning: 'to tell what something is like using details',
        cloze: 'Can you ____ the room you walked into?',
        decoys: ['to argue against it', 'to count it up', 'to hide it'],
      },
      {
        word: 'opinion',
        meaning: 'what someone thinks or believes, which others might disagree with',
        cloze: 'That the book is boring is an ____, not a fact.',
        decoys: ['something proven true', 'a measurement', 'a scientific law'],
        note: 'Facts can be checked. Opinions can be argued. Knowing which is which is a superpower.',
      },
      {
        word: 'quotation',
        meaning: 'the exact words someone said, copied word for word',
        cloze: 'She used a ____ from the passage to prove her point.',
        decoys: ['a summary in your own words', 'a made-up example', 'a page number'],
      },
    ],
  },
  {
    id: 'g3_vocab_05',
    grade: 3,
    title: 'Words for Difficulty',
    blurb: 'Precise words for when things are hard.',
    minutes: 12,
    words: [
      {
        word: 'obstacle',
        meaning: 'something in the way that makes progress harder',
        cloze: 'The fallen tree was the only ____ on the trail.',
        decoys: ['a clear open road', 'a helpful friend', 'a finished project'],
      },
      {
        word: 'persist',
        meaning: 'to keep going even when it is hard',
        cloze: 'She chose to ____ until the bridge finally held.',
        decoys: ['to give up quickly', 'to start over from scratch', 'to ask someone else'],
      },
      {
        word: 'frustrated',
        meaning: 'upset because something is not working',
        cloze: 'He was ____ after the third try failed.',
        decoys: ['calm and satisfied', 'sleepy and slow', 'proud of a success'],
      },
      {
        word: 'complicated',
        meaning: 'having many parts that are hard to keep track of',
        cloze: 'The instructions were too ____ to follow at first.',
        decoys: ['extremely simple', 'very short', 'brightly colored'],
      },
      {
        word: 'overcome',
        meaning: 'to succeed against something that was blocking you',
        cloze: 'She worked all winter to ____ her fear of the water.',
        decoys: ['to be defeated by', 'to avoid entirely', 'to forget about'],
      },
      {
        word: 'patience',
        meaning: 'the ability to wait or keep trying without getting upset',
        cloze: 'Growing anything from seed takes ____.',
        decoys: ['a need for speed', 'a bad temper', 'a lot of money'],
      },
    ],
  },
  {
    id: 'g3_vocab_06',
    grade: 3,
    title: 'Space and Distance',
    blurb: 'Words for the very large and the very far.',
    minutes: 12,
    words: [
      {
        word: 'galaxy',
        meaning: 'a huge group of billions of stars held together by gravity',
        cloze: 'Our sun is one star in a ____ called the Milky Way.',
        decoys: ['a single bright star', 'a small moon', 'the space between planets'],
      },
      {
        word: 'gravity',
        meaning: 'the force that pulls objects toward each other',
        cloze: '____ keeps the moon circling the Earth.',
        decoys: ['the heat from the sun', 'the speed of light', 'the color of a star'],
      },
      {
        word: 'atmosphere',
        meaning: 'the layer of gases surrounding a planet',
        cloze: 'Earth\'s ____ protects us from most falling rocks.',
        decoys: ['the rocky core inside', 'the water on the surface', 'a planet\'s moon'],
      },
      {
        word: 'astronomer',
        meaning: 'a scientist who studies stars, planets, and space',
        cloze: 'An ____ discovered the comet last year.',
        decoys: ['a person who flies to space', 'someone who predicts the future', 'a maker of telescopes'],
        note: 'An astronomer studies space from here. An astronaut goes there.',
      },
      {
        word: 'immense',
        meaning: 'enormously large',
        cloze: 'The distance between stars is ____.',
        decoys: ['barely noticeable', 'exactly average', 'shrinking quickly'],
      },
      {
        word: 'rotate',
        meaning: 'to spin around a center point',
        cloze: 'Earth takes twenty-four hours to ____ once.',
        decoys: ['to travel in a straight line', 'to stop completely', 'to grow larger'],
      },
    ],
  },
  {
    id: 'g3_vocab_07',
    grade: 3,
    title: 'Words for Groups and Amounts',
    blurb: 'How much, how many, and how they fit together.',
    minutes: 12,
    words: [
      {
        word: 'majority',
        meaning: 'more than half of a group',
        cloze: 'The ____ of the class voted for the museum trip.',
        decoys: ['exactly one person', 'less than half', 'nobody at all'],
      },
      {
        word: 'estimate',
        meaning: 'a careful guess about an amount',
        cloze: 'Can you ____ how many beans are in the jar?',
        decoys: ['an exact count', 'a perfect measurement', 'a written receipt'],
      },
      {
        word: 'sufficient',
        meaning: 'enough for what is needed',
        cloze: 'We have ____ paint to finish the wall.',
        decoys: ['far too little', 'wildly too much', 'completely used up'],
      },
      {
        word: 'various',
        meaning: 'several different kinds',
        cloze: 'The shelf held ____ books about space.',
        decoys: ['all exactly the same', 'only one', 'none at all'],
      },
      {
        word: 'entire',
        meaning: 'the whole thing, with nothing left out',
        cloze: 'She read the ____ book in one weekend.',
        decoys: ['a small piece of', 'about half of', 'the outside of'],
      },
      {
        word: 'gather',
        meaning: 'to collect things into one place',
        cloze: 'Let us ____ the evidence before deciding.',
        decoys: ['to scatter widely', 'to throw away', 'to break apart'],
      },
    ],
  },
  {
    id: 'g3_vocab_08',
    grade: 3,
    title: 'Words That Connect Ideas',
    blurb: 'Small words that do enormous work in a sentence.',
    minutes: 12,
    words: [
      {
        word: 'however',
        meaning: 'used to show the next idea goes against the one before',
        cloze: 'She practiced daily. ____, the race did not go as planned.',
        decoys: ['used to add a similar idea', 'used to give an example', 'used to show time passing'],
      },
      {
        word: 'therefore',
        meaning: 'used to show something is the result of what came before',
        cloze: 'The tracks led to the river. ____, the deer went that way.',
        decoys: ['used to show a contrast', 'used to change the subject', 'used to ask a question'],
      },
      {
        word: 'although',
        meaning: 'used to admit something before saying the opposite',
        cloze: '____ she was frightened, she looked out the window anyway.',
        decoys: ['used to state a result', 'used to list items', 'used to show agreement'],
      },
      {
        word: 'instead',
        meaning: 'in place of something else',
        cloze: 'She did not shout. ____, she waited quietly.',
        decoys: ['in addition to that', 'because of that', 'at the same time'],
      },
      {
        word: 'meanwhile',
        meaning: 'at the same time as something else',
        cloze: 'Amara counted seconds. ____, her grandmother searched for candles.',
        decoys: ['much later on', 'long before', 'as a result'],
      },
      {
        word: 'finally',
        meaning: 'after a long time or as the last step',
        cloze: 'She thought hard, and ____ found a simpler way to say it.',
        decoys: ['at the very start', 'immediately', 'by accident'],
      },
    ],
  },
  {
    id: 'g3_vocab_09',
    grade: 3,
    title: 'Words for Change',
    blurb: 'Precise words for things becoming different.',
    minutes: 12,
    words: [
      {
        word: 'transform',
        meaning: 'to change completely into something different',
        cloze: 'A caterpillar will ____ into a butterfly.',
        decoys: ['to stay exactly the same', 'to move to a new place', 'to grow slightly larger'],
      },
      {
        word: 'increase',
        meaning: 'to become greater in amount',
        cloze: 'The salt in the ocean continues to ____.',
        decoys: ['to become smaller', 'to disappear entirely', 'to stay level'],
      },
      {
        word: 'reduce',
        meaning: 'to make smaller in amount',
        cloze: 'We can ____ waste by using both sides of the paper.',
        decoys: ['to make much larger', 'to keep unchanged', 'to buy more of'],
      },
      {
        word: 'develop',
        meaning: 'to grow or improve over time',
        cloze: 'Her handwriting will ____ with practice.',
        decoys: ['to shrink away', 'to happen instantly', 'to break down'],
      },
      {
        word: 'replace',
        meaning: 'to put something new where the old one was',
        cloze: 'We had to ____ the broken window.',
        decoys: ['to keep the old one', 'to add a second one', 'to remove entirely'],
      },
      {
        word: 'permanent',
        meaning: 'lasting forever, not meant to change',
        cloze: 'Use pencil first — pen is ____.',
        decoys: ['lasting a short time', 'easily undone', 'changing constantly'],
      },
    ],
  },
  {
    id: 'g3_vocab_10',
    grade: 3,
    title: 'Words Worth Knowing',
    blurb: 'The last word star. These six are the ones I would most want you to keep.',
    minutes: 12,
    words: [
      {
        word: 'curiosity',
        meaning: 'the strong desire to find out and understand',
        cloze: 'Her ____ led her to ask the question nobody else asked.',
        decoys: ['a lack of interest', 'a fear of new things', 'a need for quiet'],
      },
      {
        word: 'integrity',
        meaning: 'doing the right thing even when nobody is watching',
        cloze: 'Telling the truth when no one saw takes ____.',
        decoys: ['being good at sports', 'having many friends', 'winning an argument'],
      },
      {
        word: 'empathy',
        meaning: 'understanding how someone else feels',
        cloze: 'Walking around the fence gave her ____ for the other view.',
        decoys: ['feeling sorry for yourself', 'ignoring other people', 'being very clever'],
      },
      {
        word: 'resilient',
        meaning: 'able to recover and keep going after something hard',
        cloze: 'The bridge fell, but the engineers were ____ and rebuilt better.',
        decoys: ['easily broken forever', 'unwilling to try', 'afraid of everything'],
      },
      {
        word: 'wisdom',
        meaning: 'knowing not just facts, but what to do with them',
        cloze: 'Knowing many words is knowledge. Knowing which to use is ____.',
        decoys: ['remembering many facts', 'reading very quickly', 'being the oldest'],
        note: 'Knowledge is having the pieces. Wisdom is knowing how they fit.',
      },
      {
        word: 'humility',
        meaning: 'being willing to admit you might be wrong',
        cloze: 'It takes ____ to say "I do not know, let us find out."',
        decoys: ['being certain always', 'refusing to listen', 'talking the loudest'],
      },
    ],
  },
  {
    id: 'g3_vocab_11',
    grade: 3,
    title: 'Words for Feelings',
    blurb: 'Precise words for what happens inside people.',
    minutes: 12,
    words: [
      {
        word: 'anxious',
        meaning: 'worried and uneasy about what might happen',
        cloze: 'She felt ____ the night before the big test.',
        decoys: ['completely calm', 'very sleepy', 'extremely proud'],
      },
      {
        word: 'relieved',
        meaning: 'glad because a worry has gone away',
        cloze: 'He was ____ when the lost dog trotted home.',
        decoys: ['still worried', 'newly frightened', 'slightly bored'],
      },
      {
        word: 'envious',
        meaning: 'wanting what someone else has',
        cloze: 'She was ____ of her friend\'s new bike.',
        decoys: ['generous with gifts', 'afraid of heights', 'proud of a friend'],
      },
      {
        word: 'content',
        meaning: 'quietly happy with what you have',
        cloze: 'The cat looked ____ in the warm windowsill.',
        decoys: ['restless and wanting more', 'angry about the past', 'confused by a question'],
        note: 'Content is a calm kind of happy — no fireworks, just enough.',
      },
      {
        word: 'frustrated',
        meaning: 'upset because something keeps not working',
        cloze: 'He grew ____ when the knot would not untie.',
        decoys: ['delighted by success', 'sleepy after lunch', 'curious about insects'],
      },
      {
        word: 'sympathetic',
        meaning: 'understanding and caring about someone\'s trouble',
        cloze: 'The nurse gave her a ____ smile.',
        decoys: ['cold and uncaring', 'confused and lost', 'jealous and bitter'],
      },
    ],
  },
  {
    id: 'g3_vocab_12',
    grade: 3,
    title: 'Words for How Things Happen',
    blurb: 'Adverbs of manner — the how of every action.',
    minutes: 12,
    words: [
      {
        word: 'gradually',
        meaning: 'slowly, a little at a time',
        cloze: 'The sky ____ turned from black to blue.',
        decoys: ['all at once', 'never at all', 'backwards'],
      },
      {
        word: 'abruptly',
        meaning: 'suddenly and without warning',
        cloze: 'The music stopped ____, mid-song.',
        decoys: ['slowly and gently', 'after a long warning', 'quietly over hours'],
      },
      {
        word: 'deliberately',
        meaning: 'on purpose, after thinking about it',
        cloze: 'She ____ chose the hardest puzzle.',
        decoys: ['by accident', 'without noticing', 'while asleep'],
      },
      {
        word: 'cautiously',
        meaning: 'carefully, watching out for danger',
        cloze: 'He stepped ____ onto the frozen pond.',
        decoys: ['recklessly and fast', 'loudly and proudly', 'without looking'],
      },
      {
        word: 'thoroughly',
        meaning: 'completely, missing nothing',
        cloze: 'Wash your hands ____ before dinner.',
        decoys: ['partly and quickly', 'once a year', 'only if watched'],
      },
      {
        word: 'reluctantly',
        meaning: 'unwillingly, wishing you did not have to',
        cloze: 'He ____ handed back the borrowed game.',
        decoys: ['eagerly and gladly', 'twice in a row', 'without being asked'],
      },
    ],
  },
  {
    id: 'g3_vocab_13',
    grade: 3,
    title: 'Words From Stories',
    blurb: 'The words that make books worth reading.',
    minutes: 12,
    words: [
      {
        word: 'character',
        meaning: 'a person or animal in a story',
        cloze: 'My favorite ____ in the book is the clever fox.',
        decoys: ['the paper it is printed on', 'the price of the book', 'the author\'s house'],
      },
      {
        word: 'setting',
        meaning: 'where and when a story happens',
        cloze: 'The ____ of the tale is a lighthouse in winter.',
        decoys: ['the main problem', 'the last page', 'the title font'],
      },
      {
        word: 'conflict',
        meaning: 'the problem or struggle in a story',
        cloze: 'The ____ began when both girls wanted the same prize.',
        decoys: ['the happy ending', 'the book cover', 'the chapter numbers'],
      },
      {
        word: 'dialogue',
        meaning: 'the words characters say to each other',
        cloze: 'You can tell they are friends from their playful ____.',
        decoys: ['the pictures', 'the page numbers', 'the silence'],
      },
      {
        word: 'narrator',
        meaning: 'the voice that tells the story',
        cloze: 'The ____ knows what every character is thinking.',
        decoys: ['the reader', 'the villain only', 'the printer'],
      },
      {
        word: 'moral',
        meaning: 'the lesson a story teaches',
        cloze: 'The ____ of the fable is that slow and steady wins.',
        decoys: ['the funniest joke', 'the longest chapter', 'the main character\'s name'],
      },
    ],
  },
  {
    id: 'g3_vocab_14',
    grade: 3,
    title: 'Words for the Natural World',
    blurb: 'The vocabulary of forests, rivers, and weather.',
    minutes: 12,
    words: [
      {
        word: 'habitat',
        meaning: 'the natural home of a plant or animal',
        cloze: 'A pond is the perfect ____ for frogs.',
        decoys: ['a kind of food', 'an animal\'s enemy', 'a zoo cage'],
      },
      {
        word: 'predator',
        meaning: 'an animal that hunts other animals for food',
        cloze: 'The hawk is a ____ that hunts from the sky.',
        decoys: ['an animal that only eats plants', 'a baby animal', 'a farm animal'],
      },
      {
        word: 'camouflage',
        meaning: 'colors or patterns that help an animal hide',
        cloze: 'The moth\'s ____ makes it vanish against tree bark.',
        decoys: ['a loud warning call', 'a way of flying', 'a type of nest'],
      },
      {
        word: 'migration',
        meaning: 'a long journey animals make with the seasons',
        cloze: 'The geese begin their ____ south every autumn.',
        decoys: ['a deep winter sleep', 'a fight over territory', 'a way of hunting'],
      },
      {
        word: 'ecosystem',
        meaning: 'all the living and non-living things in a place, working together',
        cloze: 'The tide pool is a tiny ____ full of connected life.',
        decoys: ['a single animal', 'a kind of rock', 'a weather pattern'],
      },
      {
        word: 'drought',
        meaning: 'a long period with too little rain',
        cloze: 'During the ____, the riverbed cracked like old paint.',
        decoys: ['a sudden flood', 'a heavy snowstorm', 'a season of plenty'],
      },
    ],
  },
  {
    id: 'g3_vocab_15',
    grade: 3,
    title: 'Words for Making Things',
    blurb: 'Builder words, inventor words, maker words.',
    minutes: 12,
    words: [
      {
        word: 'design',
        meaning: 'to plan how something will look and work',
        cloze: 'First we ____ the treehouse on paper, then we build.',
        decoys: ['to destroy carefully', 'to buy ready-made', 'to hide away'],
      },
      {
        word: 'construct',
        meaning: 'to build something piece by piece',
        cloze: 'It took a week to ____ the model bridge.',
        decoys: ['to knock down', 'to imagine only', 'to lose track of'],
      },
      {
        word: 'adjust',
        meaning: 'to change something a little to make it work better',
        cloze: '____ the strap so the helmet fits snugly.',
        decoys: ['to leave exactly alone', 'to throw away', 'to double in size'],
      },
      {
        word: 'sturdy',
        meaning: 'strong and not easily broken',
        cloze: 'The ____ table held all forty books.',
        decoys: ['wobbly and weak', 'invisible', 'soft as a pillow'],
      },
      {
        word: 'flexible',
        meaning: 'able to bend without breaking',
        cloze: 'The ____ branch bent in the wind and sprang back.',
        decoys: ['stiff and brittle', 'heavy as stone', 'sharp at the edges'],
      },
      {
        word: 'prototype',
        meaning: 'a first test version of an invention',
        cloze: 'Her first ____ of the feeder lasted one afternoon.',
        decoys: ['the final perfect product', 'a written story', 'an old antique'],
        note: 'Every great invention started as a wobbly prototype. The wobble is part of the process.',
      },
    ],
  },
  {
    id: 'g3_vocab_16',
    grade: 3,
    title: 'Words for Time',
    blurb: 'Words that put events in their place.',
    minutes: 12,
    words: [
      {
        word: 'ancient',
        meaning: 'from a very long time ago',
        cloze: 'The ____ coin was two thousand years old.',
        decoys: ['made yesterday', 'still to come', 'brand new'],
      },
      {
        word: 'modern',
        meaning: 'belonging to the present time',
        cloze: 'The castle now has ____ lights inside its old walls.',
        decoys: ['from the distant past', 'imaginary', 'broken down'],
      },
      {
        word: 'decade',
        meaning: 'a period of ten years',
        cloze: 'Grandpa has driven that truck for a whole ____.',
        decoys: ['a hundred years', 'a single week', 'one thousand years'],
      },
      {
        word: 'century',
        meaning: 'a period of one hundred years',
        cloze: 'The letter in the wall waited more than a ____.',
        decoys: ['ten years', 'one year', 'a million years'],
      },
      {
        word: 'temporary',
        meaning: 'lasting only a short time',
        cloze: 'The bandage is ____ — it comes off tomorrow.',
        decoys: ['lasting forever', 'invisible', 'extremely important'],
      },
      {
        word: 'permanent',
        meaning: 'lasting forever, or a very long time',
        cloze: 'The marker made a ____ mark on the desk.',
        decoys: ['washable and brief', 'imaginary', 'very quiet'],
      },
    ],
  },
  {
    id: 'g3_vocab_17',
    grade: 3,
    title: 'Words for Community',
    blurb: 'Words about people living and working together.',
    minutes: 12,
    words: [
      {
        word: 'citizen',
        meaning: 'a member of a town or country',
        cloze: 'Every ____ can help keep the park clean.',
        decoys: ['a visitor passing through', 'a kind of building', 'an elected king'],
      },
      {
        word: 'volunteer',
        meaning: 'someone who helps without being paid',
        cloze: 'Each ____ planted ten trees on Saturday.',
        decoys: ['a paid worker', 'a lazy watcher', 'a famous singer'],
      },
      {
        word: 'cooperate',
        meaning: 'to work together toward one goal',
        cloze: 'The classes had to ____ to finish the mural.',
        decoys: ['to compete fiercely', 'to work alone', 'to argue loudly'],
      },
      {
        word: 'contribute',
        meaning: 'to give something to a shared effort',
        cloze: 'Everyone can ____ one can of food to the drive.',
        decoys: ['to take something away', 'to watch from far off', 'to forget entirely'],
      },
      {
        word: 'tradition',
        meaning: 'something a group has done the same way for a long time',
        cloze: 'Pancakes on Sunday is our family ____.',
        decoys: ['a brand-new invention', 'a broken promise', 'a strict law'],
      },
      {
        word: 'generation',
        meaning: 'all the people born around the same time',
        cloze: 'Three ____ live in that house: kids, parents, and grandparents.',
        decoys: ['a single person', 'a type of house', 'a school subject'],
      },
    ],
  },
  {
    id: 'g3_vocab_18',
    grade: 3,
    title: 'Words for Evidence and Proof',
    blurb: 'Detective words for careful thinkers.',
    minutes: 12,
    words: [
      {
        word: 'observe',
        meaning: 'to watch carefully and notice details',
        cloze: 'Sit quietly and ____ what the ants actually do.',
        decoys: ['to guess wildly', 'to look away', 'to make up a story'],
      },
      {
        word: 'clue',
        meaning: 'a small piece of information that helps solve a mystery',
        cloze: 'The muddy footprint was the first ____.',
        decoys: ['the final answer', 'a wrong idea', 'a kind of lock'],
      },
      {
        word: 'suspect',
        meaning: 'to think something might be true without being sure',
        cloze: 'I ____ the cat knocked over the vase.',
        decoys: ['to know absolutely', 'to prove completely', 'to forgive instantly'],
      },
      {
        word: 'verify',
        meaning: 'to check whether something is really true',
        cloze: 'Let us ____ that fact before we repeat it.',
        decoys: ['to spread without checking', 'to erase quickly', 'to doubt forever'],
        note: 'Verify before you share. True thinkers check.',
      },
      {
        word: 'genuine',
        meaning: 'real and true, not fake',
        cloze: 'The expert said the old map was ____.',
        decoys: ['a clever fake', 'brand new', 'imaginary'],
      },
      {
        word: 'accurate',
        meaning: 'exactly correct, with no mistakes',
        cloze: 'Her measurement was ____ to the millimeter.',
        decoys: ['roughly guessed', 'completely wrong', 'beautifully drawn'],
      },
    ],
  },
  {
    id: 'g3_vocab_19',
    grade: 3,
    title: 'Words for Courage and Effort',
    blurb: 'The vocabulary of not giving up.',
    minutes: 12,
    words: [
      {
        word: 'persevere',
        meaning: 'to keep trying even when it is hard',
        cloze: 'She chose to ____ through all one hundred violin tries.',
        decoys: ['to quit at the first trouble', 'to complain loudly', 'to wait for luck'],
      },
      {
        word: 'determined',
        meaning: 'firmly decided to do something, no matter what',
        cloze: 'He was ____ to finish the race, even walking.',
        decoys: ['easily talked out of it', 'unsure and drifting', 'afraid to start'],
      },
      {
        word: 'attempt',
        meaning: 'a try at doing something',
        cloze: 'Her third ____ at the cartwheel was the best yet.',
        decoys: ['a guaranteed success', 'a refusal', 'a long rest'],
      },
      {
        word: 'obstacle',
        meaning: 'something that stands in your way',
        cloze: 'The fallen tree was an ____ on the path.',
        decoys: ['a helpful shortcut', 'a kind of reward', 'a cheering friend'],
      },
      {
        word: 'achieve',
        meaning: 'to succeed at something through effort',
        cloze: 'With daily practice, you can ____ your reading goal.',
        decoys: ['to receive without trying', 'to give up on', 'to forget about'],
      },
      {
        word: 'resilient',
        meaning: 'able to bounce back after something hard',
        cloze: 'The ____ town rebuilt after the flood.',
        decoys: ['easily crushed forever', 'never challenged', 'always lucky'],
        note: 'Resilient does not mean nothing hurts. It means you rise anyway.',
      },
    ],
  },
  {
    id: 'g3_vocab_20',
    grade: 3,
    title: 'Words Worth Carrying',
    blurb: 'The final set — rich words for a rich life.',
    minutes: 12,
    words: [
      {
        word: 'gratitude',
        meaning: 'the feeling of being thankful',
        cloze: 'She felt deep ____ for her teacher\'s patience.',
        decoys: ['a feeling of anger', 'a kind of payment', 'a sense of boredom'],
      },
      {
        word: 'curiosity',
        meaning: 'the strong wish to learn and know',
        cloze: '____ pulled her to the very last page.',
        decoys: ['the wish to sleep', 'a fear of questions', 'a type of test'],
      },
      {
        word: 'integrity',
        meaning: 'doing the right thing even when no one is watching',
        cloze: 'Returning the extra change showed real ____.',
        decoys: ['doing right only for praise', 'clever trickery', 'physical strength'],
        note: 'The Falcons\' flooded-field day was integrity. No referee needed.',
      },
      {
        word: 'compassion',
        meaning: 'noticing someone\'s pain and wanting to help',
        cloze: 'Her ____ for the new student showed in one saved seat.',
        decoys: ['ignoring others\' trouble', 'a competitive streak', 'a fear of strangers'],
      },
      {
        word: 'wisdom',
        meaning: 'knowing how to use what you know, gained from experience',
        cloze: 'Grandmother\'s ____ came from eighty years of paying attention.',
        decoys: ['memorized facts only', 'quick guessing', 'loud opinions'],
      },
      {
        word: 'wonder',
        meaning: 'amazed curiosity at something great or beautiful',
        cloze: 'They watched the northern lights in silent ____.',
        decoys: ['complete boredom', 'angry confusion', 'sleepy fog'],
      },
    ],
  },
];

/**
 * Each word set is immediately followed by its own flash-card review star —
 * learn the six words, then straight away say what each one means out loud,
 * while it is still fresh. Interleaving beats teaching all ten sets first and
 * reviewing afterward, where the first set would be half-forgotten by the
 * time review finally arrived.
 */
export const grade3Vocabulary: Star[] = specs.flatMap((spec) => [
  buildVocabStar(spec),
  buildFlashcardStar(spec),
]);
