import type { BsfWeek } from './bsf';

/**
 * ============================================================================
 * BSF ROMANS — LESSONS 1 THROUGH 14
 * ============================================================================
 *
 * The children's study of Paul's letter to the Romans, one star per lesson.
 * Lesson summaries (main truth, God's attribute, doctrine, gospel connection)
 * and the NIV memory verses follow the BSF Romans children's material.
 *
 * Passage text and memory verses are the New International Version (NIV),
 * supplied by the family for their own study, matching the BSF lesson cards.
 * Scripture taken from the Holy Bible, New International Version® NIV®,
 * Copyright © 1973, 1978, 1984, 2011 by Biblica, Inc. Used by permission.
 *
 * A few readings are shortened for the six-to-nine audience, following the
 * children's-material practice of leaving adult matters for later years:
 * Lesson 2 reads Romans 1:18-23 and 25; Lesson 3 skips 2:22-27; Lesson 4
 * skips the 3:13-18 quotations; Lesson 7 skips 4:9-12 and 14-15; Lesson 12
 * reads selections from Romans 7:7-25; Lesson 13 skips 8:7-8. Every
 * lesson's truth is taught in full.
 * ============================================================================
 */

export const BSF_WEEKS: BsfWeek[] = [
  {
    week: 1,
    title: 'Our Need for the Gospel',
    reference: 'Romans 1:1-17',
    summary:
      'Welcome to the letter to the Romans! A man named Paul wrote this letter long ago to believers in the great city of Rome. He starts with the most important news in the world.',
    art: 'scroll',
    minutes: 18,
    passage: [
      "Paul, a servant of Christ Jesus, called to be an apostle and set apart for the gospel of God— the gospel he promised beforehand through his prophets in the Holy Scriptures regarding his Son, who as to his earthly life was a descendant of David,",
      "and who through the Spirit of holiness was appointed the Son of God in power by his resurrection from the dead: Jesus Christ our Lord. Through him we received grace and apostleship to call all the Gentiles to the obedience that comes from faith for his name’s sake. And you also are among those Gentiles who are called to belong to Jesus Christ.",
      "To all in Rome who are loved by God and called to be his holy people: Grace and peace to you from God our Father and from the Lord Jesus Christ. First, I thank my God through Jesus Christ for all of you, because your faith is being reported all over the world. God, whom I serve in my spirit in preaching the gospel of his Son, is my witness how constantly I remember you",
      "in my prayers at all times; and I pray that now at last by God’s will the way may be opened for me to come to you. I long to see you so that I may impart to you some spiritual gift to make you strong— that is, that you and I may be mutually encouraged by each other’s faith.",
      "I do not want you to be unaware, brothers and sisters, that I planned many times to come to you (but have been prevented from doing so until now) in order that I might have a harvest among you, just as I have had among the other Gentiles. I am obligated both to Greeks and non-Greeks, both to the wise and the foolish. That is why I am so eager to preach the gospel also to you who are in Rome.",
      "For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes: first to the Jew, then to the Gentile. For in the gospel the righteousness of God is revealed—a righteousness that is by faith from first to last, just as it is written: “The righteous will live by faith.”",
    ],
    memoryVerse: {
      text: 'For in the gospel the righteousness of God is revealed—a righteousness that is by faith from first to last.',
      reference: 'Romans 1:17a',
    },
    truth: 'The gospel is the power of God that saves sinners.',
    attribute: { name: 'Righteous', meaning: 'God is right in all He does.' },
    doctrine: { term: 'Righteousness', meaning: 'being completely right and good, the way God is' },
    gospel: 'When we believe in Jesus, God gives us Jesus’s perfect righteousness.',
    questions: [
      {
        ask: 'Who wrote this letter to the Romans?',
        options: ['Paul', 'Peter', 'David', 'Moses'],
        correct: 0,
        teach: 'Paul — he calls himself a servant of Jesus Christ in the very first line.',
      },
      {
        ask: 'Paul says he is NOT ashamed of the Good News. Why not?',
        options: [
          'Because it is the power of God for salvation',
          'Because it made him famous',
          'Because it was easy to say',
          'Because everyone already believed it',
        ],
        correct: 0,
        teach: 'It is the power of God for salvation for everyone who believes. That is nothing to be shy about.',
      },
      {
        ask: 'The gospel is for everyone who believes. Who does that include?',
        accept: ['everyone', 'me', 'us', 'all people', 'anyone', 'the whole world', 'jews and greeks'],
        sample: 'Everyone — including me.',
        teach: 'Everyone. The Jew first, and also the Greek — Paul means the whole world gets invited.',
      },
      {
        ask: 'What does "gospel" mean?',
        options: ['Good news', 'A long letter', 'A kind of song', 'A city in Rome'],
        correct: 0,
        teach: 'Good News. The best news there is: God saves sinners through Jesus.',
        grades: [1],
      },
      {
        ask: 'Paul wanted to visit Rome so he and the believers could encourage each other by their faith. What does it mean to encourage someone?',
        accept: ['help', 'cheer', 'make them strong', 'build them up', 'make them brave', 'lift them up'],
        sample: 'To help them feel strong and brave.',
        teach: 'To put courage into someone. Faith grows stronger when friends share it.',
        grades: [3],
      },
    ],
  },
  {
    week: 2,
    title: 'God’s Wrath Against Sinful Humanity',
    reference: 'Romans 1:18-32',
    summary:
      'This lesson is serious, but important. Paul explains that everyone can see God’s power in the world He made — and what happens when people refuse to thank Him.',
    art: 'storm',
    minutes: 17,
    passage: [
      "The wrath of God is being revealed from heaven against all the godlessness and wickedness of people, who suppress the truth by their wickedness, since what may be known about God is plain to them, because God has made it plain to them. For since the creation of the world God’s invisible qualities—his eternal power and divine nature—have been clearly seen, being understood from what has been made, so that people are without excuse.",
      "For although they knew God, they neither glorified him as God nor gave thanks to him, but their thinking became futile and their foolish hearts were darkened. Although they claimed to be wise, they became fools and exchanged the glory of the immortal God for images made to look like a mortal human being and birds and animals and reptiles.",
      "They exchanged the truth about God for a lie, and worshiped and served created things rather than the Creator—who is forever praised. Amen.",
    ],
    memoryVerse: {
      text: 'For since the creation of the world God’s invisible qualities—his eternal power and divine nature—have been clearly seen, being understood from what has been made, so that people are without excuse.',
      reference: 'Romans 1:20',
    },
    truth: 'People who refuse to turn away from their sin will face God’s wrath.',
    attribute: { name: 'Creator', meaning: 'God made everything.' },
    doctrine: { term: 'Wrath of God', meaning: 'God’s holy anger against sin' },
    gospel: 'No one can be saved from God’s wrath except through faith in Jesus.',
    questions: [
      {
        ask: 'How can everyone see that God is real and powerful?',
        options: [
          'Through the things He has made — creation',
          'Only by reading books',
          'Only in dreams',
          'No one can see it',
        ],
        correct: 0,
        teach: 'Creation shows Him. Stars, oceans, animals, you — the Maker’s power is on display everywhere.',
      },
      {
        ask: 'What did people trade the glory of God for?',
        options: [
          'Images of people, birds, and animals',
          'Gold and silver',
          'Nothing at all',
          'Books of wisdom',
        ],
        correct: 0,
        teach: 'They swapped the real, living God for statues of made things. A terrible trade.',
      },
      {
        ask: 'The passage says people knew God but did not give thanks. Why do you think thanking God matters?',
        accept: ['he made everything', 'he deserves it', 'it shows love', 'he gives us everything', 'because he is good'],
        sample: 'Because He made everything and deserves our thanks.',
        teach: 'Thanking God is how we honor Him as the Giver. Forgetting to thank Him is where the trouble began.',
      },
      {
        ask: 'Name one thing in creation that shows you how powerful God is.',
        accept: ['stars', 'ocean', 'mountains', 'sun', 'animals', 'sky', 'trees', 'the sea', 'people'],
        sample: 'The ocean — it is so huge and strong.',
        teach: 'Yes. Every one of those is a signpost pointing to its Maker.',
        grades: [1],
      },
      {
        ask: 'The passage says people are "without excuse." What does that mean here?',
        options: [
          'No one can say "I never knew about God" — creation already showed Him',
          'People are not allowed to talk',
          'Everyone gets excused',
          'Excuses are always fine',
        ],
        correct: 0,
        teach: 'Creation is evidence everyone has seen. No one can claim they had no clue.',
        grades: [3],
      },
    ],
  },
  {
    week: 3,
    title: 'No Excuse for Anyone',
    reference: 'Romans 2',
    summary:
      'Have you ever pointed out someone else’s mistake while making the same one yourself? Paul says God sees it all — and judges everyone completely fairly.',
    art: 'scales',
    minutes: 19,
    passage: [
      "You, therefore, have no excuse, you who pass judgment on someone else, for at whatever point you judge another, you are condemning yourself, because you who pass judgment do the same things. Now we know that God’s judgment against those who do such things is based on truth. So when you, a mere human being, pass judgment on them and yet do the same things, do you think you will escape God’s judgment? Or do you show contempt for the riches of his kindness, forbearance and patience, not realizing that God’s kindness is intended to lead you to repentance?",
      "But because of your stubbornness and your unrepentant heart, you are storing up wrath against yourself for the day of God’s wrath, when his righteous judgment will be revealed. God “will repay each person according to what they have done.” To those who by persistence in doing good seek glory, honor and immortality, he will give eternal life. But for those who are self-seeking and who reject the truth and follow evil, there will be wrath and anger.",
      "There will be trouble and distress for every human being who does evil: first for the Jew, then for the Gentile; but glory, honor and peace for everyone who does good: first for the Jew, then for the Gentile. For God does not show favoritism.",
      "All who sin apart from the law will also perish apart from the law, and all who sin under the law will be judged by the law. For it is not those who hear the law who are righteous in God’s sight, but it is those who obey the law who will be declared righteous.",
      "(Indeed, when Gentiles, who do not have the law, do by nature things required by the law, they are a law for themselves, even though they do not have the law. They show that the requirements of the law are written on their hearts, their consciences also bearing witness, and their thoughts sometimes accusing them and at other times even defending them.) This will take place on the day when God judges people’s secrets through Jesus Christ, as my gospel declares.",
      "Now you, if you call yourself a Jew; if you rely on the law and boast in God; if you know his will and approve of what is superior because you are instructed by the law; if you are convinced that you are a guide for the blind, a light for those who are in the dark, an instructor of the foolish, a teacher of little children, because you have in the law the embodiment of knowledge and truth— you, then, who teach others, do you not teach yourself? You who preach against stealing, do you steal?",
      "A person is not a Jew who is one only outwardly, nor is circumcision merely outward and physical. No, a person is a Jew who is one inwardly; and circumcision is circumcision of the heart, by the Spirit, not by the written code. Such a person’s praise is not from other people, but from God.",
    ],
    memoryVerse: {
      text: 'For God does not show favoritism.',
      reference: 'Romans 2:11',
    },
    truth: 'God will judge every person.',
    attribute: { name: 'Just', meaning: 'All God’s judgments are perfect.' },
    doctrine: { term: 'Judgment', meaning: 'God looking at every life completely fairly' },
    gospel: 'God’s kindness leads people to repent, believe in Jesus, and be saved.',
    questions: [
      {
        ask: 'When we judge someone else for doing wrong things we also do, what does Paul say about us?',
        options: [
          'We condemn ourselves',
          'We are being helpful',
          'We are always right',
          'Nothing happens',
        ],
        correct: 0,
        teach: 'We condemn ourselves — pointing a finger while doing the same thing.',
      },
      {
        ask: 'What does God’s goodness and patience lead us toward?',
        options: ['Repentance — turning away from sin', 'More toys', 'Being famous', 'Nothing'],
        correct: 0,
        teach: 'Repentance. God is patient because He is giving people time to turn around.',
      },
      {
        ask: 'What does "God does not show favoritism" mean?',
        accept: ['he is fair', 'no favorites', 'he treats everyone the same', 'everyone equal', 'fair to all'],
        sample: 'God treats everyone fairly — no favorites.',
        teach: 'Perfectly fair, to every person, always. Our memory verse in five words.',
      },
      {
        ask: 'Does God only care about what people do on the outside, or what is in their heart?',
        options: ['What is in their heart too', 'Only the outside', 'Only on Sundays', 'Neither'],
        correct: 0,
        teach: 'The heart. Paul says real belonging to God is "of the heart" — inside, where only God sees.',
        grades: [1],
      },
      {
        ask: 'Paul asks teachers: "You who teach others, do you not teach yourself?" What is he warning about?',
        accept: ['hypocrisy', 'saying one thing doing another', 'not following your own words', 'being fake', 'do what you say'],
        sample: 'Saying the right thing but not doing it yourself.',
        teach: 'That is called hypocrisy — and God sees through it every time.',
        grades: [3],
      },
    ],
  },
  {
    week: 4,
    title: 'No One Righteous',
    reference: 'Romans 3:1-20',
    summary:
      'If God is perfectly fair, here is the hard question: is anyone good enough on their own? Paul answers with words that include every single person.',
    art: 'mirror',
    minutes: 18,
    passage: [
      "What advantage, then, is there in being a Jew, or what value is there in circumcision? Much in every way! First of all, the Jews have been entrusted with the very words of God.",
      "What if some were unfaithful? Will their unfaithfulness nullify God’s faithfulness? Not at all! Let God be true, and every human being a liar. As it is written: “So that you may be proved right when you speak and prevail when you judge.” But if our unrighteousness brings out God’s righteousness more clearly, what shall we say? That God is unjust in bringing his wrath on us? (I am using a human argument.) Certainly not! If that were so, how could God judge the world?",
      "Someone might argue, “If my falsehood enhances God’s truthfulness and so increases his glory, why am I still condemned as a sinner?” Why not say—as some slanderously claim that we say—“Let us do evil that good may result”? Their condemnation is just! What shall we conclude then? Do we have any advantage? Not at all! For we have already made the charge that Jews and Gentiles alike are all under the power of sin.",
      "As it is written: “There is no one righteous, not even one; there is no one who understands; there is no one who seeks God. All have turned away, they have together become worthless; there is no one who does good, not even one.”",
      "Now we know that whatever the law says, it says to those who are under the law, so that every mouth may be silenced and the whole world held accountable to God. Therefore no one will be declared righteous in God’s sight by the works of the law; rather, through the law we become conscious of our sin.",
    ],
    memoryVerse: {
      text: 'As it is written: ‘There is no one righteous, not even one.’',
      reference: 'Romans 3:10',
    },
    truth: 'Without Jesus, everyone is guilty before God.',
    attribute: { name: 'Holy', meaning: 'God’s perfect goodness sets Him apart from His creation.' },
    doctrine: { term: 'Sin', meaning: 'doing wrong against God — and everyone everywhere has done it' },
    gospel: 'All people are born as sinners and choose to sin against God.',
    questions: [
      {
        ask: 'How many people does the passage say are righteous on their own?',
        options: ['Not even one', 'A few very good ones', 'About half', 'Most people'],
        correct: 0,
        teach: 'Not even one. Not the best kid in class, not the kindest grown-up. Everyone needs help.',
      },
      {
        ask: 'What does the law help us know?',
        options: ['Our sin', 'How to get rich', 'The future', 'Nothing at all'],
        correct: 0,
        teach: 'Through the law comes the knowledge of sin — like a mirror showing us the smudges on our face.',
      },
      {
        ask: 'The law is like a mirror. What can a mirror do, and what can it NOT do?',
        accept: ['show', 'it shows dirt but cannot clean', 'it cannot wash you', 'shows the problem', 'cannot fix'],
        sample: 'A mirror shows the dirt on your face, but it cannot wash it off.',
        teach: 'Exactly. The law shows sin but cannot remove it. Something else must do the washing.',
        grades: [3],
      },
      {
        ask: 'Is anyone too good to need Jesus?',
        options: ['No — everyone needs Him', 'Yes, very good people', 'Only grown-ups need Him', 'Only kids need Him'],
        correct: 0,
        teach: 'No one is too good. That is why this lesson matters before next week’s good news.',
        grades: [1],
      },
      {
        ask: 'Why do you think Paul wants "every mouth to be closed" before God?',
        accept: ['no excuses', 'no one can brag', 'no boasting', 'everyone is guilty', 'we cannot argue'],
        sample: 'So no one can make excuses or brag about being good enough.',
        teach: 'When every excuse goes quiet, we are finally ready to hear about rescue.',
        grades: [3],
      },
    ],
  },
  {
    week: 5,
    title: 'How God Saves Sinners',
    reference: 'Romans 3:21-26',
    summary:
      'Last week ended with everyone guilty and no way out. This week is the turning point of the whole letter — the great BUT NOW. God Himself made the way.',
    art: 'cross',
    minutes: 17,
    passage: [
      "But now apart from the law the righteousness of God has been made known, to which the Law and the Prophets testify. This righteousness is given through faith in Jesus Christ to all who believe. There is no difference between Jew and Gentile, for all have sinned and fall short of the glory of God,",
      "and all are justified freely by his grace through the redemption that came by Christ Jesus. God presented Christ as a sacrifice of atonement, through the shedding of his blood—to be received by faith. He did this to demonstrate his righteousness, because in his forbearance he had left the sins committed beforehand unpunished— he did it to demonstrate his righteousness at the present time, so as to be just and the one who justifies those who have faith in Jesus.",
    ],
    memoryVerse: {
      text: 'And all are justified freely by his grace through the redemption that came by Christ Jesus.',
      reference: 'Romans 3:24',
    },
    truth: 'God has made the way for sinners to be forgiven.',
    attribute: { name: 'Savior', meaning: 'Jesus Christ, the Son of God, is the only Savior from sin.' },
    doctrine: { term: 'Salvation', meaning: 'being rescued by God from sin' },
    gospel: 'God sent His only Son, Jesus, to save people from sin.',
    questions: [
      {
        ask: 'The passage begins "But now..." What changed?',
        options: [
          'God revealed a righteousness apart from the law — through faith in Jesus',
          'The law got easier',
          'People stopped sinning',
          'Nothing changed',
        ],
        correct: 0,
        teach: 'God opened a way the law never could: righteousness through faith in Jesus.',
      },
      {
        ask: 'Who has sinned and falls short of the glory of God?',
        options: ['All people', 'Only the worst people', 'Only people long ago', 'Nobody'],
        correct: 0,
        teach: 'All. The same "all" who sinned are the "all" who are offered rescue. No one left out either way.',
      },
      {
        ask: 'Our verse says we are justified FREELY by his grace. What does freely mean?',
        accept: ['free', 'no cost', 'we do not pay', 'a gift', 'without paying', 'for nothing'],
        sample: 'It costs us nothing — it is a gift.',
        teach: 'Free for us — because Jesus paid the whole cost Himself.',
      },
      {
        ask: 'Who did God send to save people from sin?',
        options: ['Jesus, His Son', 'An angel', 'Moses', 'A king'],
        correct: 0,
        teach: 'His own Son. That is how much God wanted to save sinners.',
        grades: [1],
      },
      {
        ask: 'God is called both "just" and "the justifier." How can He punish sin fairly AND forgive sinners?',
        accept: ['jesus took the punishment', 'jesus paid', 'the cross', 'jesus died for us', 'sin was punished on jesus'],
        sample: 'Jesus took the punishment, so sin was paid for and sinners go free.',
        teach: 'The cross is where perfect fairness and perfect love meet. Sin punished; sinners freed.',
        grades: [3],
      },
    ],
  },
  {
    week: 6,
    title: 'Justification by Faith, Part 1',
    reference: 'Romans 3:27-31',
    summary:
      'If God saves us as a free gift, is there anything left to brag about? Paul answers with a question of his own — and the answer is wonderful news for everyone.',
    art: 'gift_hands',
    minutes: 16,
    passage: [
      "Where, then, is boasting? It is excluded. Because of what law? The law that requires works? No, because of the law that requires faith. For we maintain that a person is justified by faith apart from the works of the law.",
      "Or is God the God of Jews only? Is he not the God of Gentiles too? Yes, of Gentiles too, since there is only one God, who will justify the circumcised by faith and the uncircumcised through that same faith. Do we, then, nullify the law by this faith? Not at all! Rather, we uphold the law.",
    ],
    memoryVerse: {
      text: 'For we maintain that a person is justified by faith apart from the works of the law.',
      reference: 'Romans 3:28',
    },
    truth: 'God justifies people through faith in Jesus alone.',
    attribute: { name: 'Impartial', meaning: 'God gives eternal life to anyone who trusts in Jesus.' },
    doctrine: { term: 'Faith', meaning: 'trusting Jesus with your whole heart' },
    gospel: 'Jesus gives eternal life to those who trust in Him to save them.',
    questions: [
      {
        ask: 'Where is the boasting, now that God saves by faith?',
        options: ['It is excluded — shut out', 'It is allowed on Sundays', 'Only heroes may boast', 'Everywhere'],
        correct: 0,
        teach: 'Shut out completely. A gift you did not earn leaves nothing to brag about.',
      },
      {
        ask: 'Is a person justified by doing good works, or by faith?',
        options: ['By faith', 'By works', 'By being born lucky', 'By waiting'],
        correct: 0,
        teach: 'By faith, apart from works. Trusting Jesus, not earning points.',
      },
      {
        ask: 'Is God the God of just one group of people?',
        options: ['No — He is God of all peoples', 'Yes, one country only', 'Only of grown-ups', 'Only of long ago'],
        correct: 0,
        teach: 'One God, for Jews and Gentiles alike — every nation, every language, every child.',
      },
      {
        ask: 'What is faith?',
        accept: ['trusting', 'trusting jesus', 'believing', 'trusting god', 'believing in jesus'],
        sample: 'Trusting Jesus with my whole heart.',
        teach: 'Trusting Jesus — leaning your whole weight on Him, like sitting down on a chair you believe will hold you.',
        grades: [1],
      },
      {
        ask: 'If salvation cannot be earned, why do believers still do good works?',
        accept: ['love', 'to thank god', 'because they love god', 'gratitude', 'not to earn', 'because they are saved'],
        sample: 'Out of love and thankfulness — not to earn what is already given.',
        teach: 'Good works become a thank-you instead of a payment. Same actions, whole new reason.',
        grades: [3],
      },
    ],
  },
  {
    week: 7,
    title: 'Justification by Faith, Part 2',
    reference: 'Romans 4',
    summary:
      'To show that faith has always been the way, Paul tells the story of Abraham — an old man, a huge promise, and a sky full of stars.',
    art: 'stars_promise',
    minutes: 19,
    passage: [
      "What then shall we say that Abraham, our forefather according to the flesh, discovered in this matter? If, in fact, Abraham was justified by works, he had something to boast about—but not before God. What does Scripture say? “Abraham believed God, and it was credited to him as righteousness.”",
      "Now to the one who works, wages are not credited as a gift but as an obligation. However, to the one who does not work but trusts God who justifies the ungodly, their faith is credited as righteousness. David says the same thing when he speaks of the blessedness of the one to whom God credits righteousness apart from works: “Blessed are those whose transgressions are forgiven, whose sins are covered. Blessed is the one whose sin the Lord will never count against them.”",
      "It was not through the law that Abraham and his offspring received the promise that he would be heir of the world, but through the righteousness that comes by faith.",
      "Therefore, the promise comes by faith, so that it may be by grace and may be guaranteed to all Abraham’s offspring—not only to those who are of the law but also to those who have the faith of Abraham. He is the father of us all. As it is written: “I have made you a father of many nations.” He is our father in the sight of God, in whom he believed—the God who gives life to the dead and calls into being things that were not. Against all hope, Abraham in hope believed and so became the father of many nations, just as it had been said to him, “So shall your offspring be.”",
      "Without weakening in his faith, he faced the fact that his body was as good as dead—since he was about a hundred years old—and that Sarah’s womb was also dead. Yet he did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God, being fully persuaded that God had power to do what he had promised.",
      "This is why “it was credited to him as righteousness.” The words “it was credited to him” were written not for him alone, but also for us, to whom God will credit righteousness—for us who believe in him who raised Jesus our Lord from the dead. He was delivered over to death for our sins and was raised to life for our justification.",
    ],
    memoryVerse: {
      text: 'Yet he did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God, being fully persuaded that God had power to do what he had promised.',
      reference: 'Romans 4:20-21',
    },
    truth: 'God gives Jesus’s righteousness to those who believe in Him.',
    attribute: { name: 'Faithful', meaning: 'God always keeps His promises.' },
    doctrine: { term: 'Justification', meaning: 'God declaring a sinner not guilty because of Jesus' },
    gospel: 'God declares sinners righteous forever when they trust in Jesus for salvation.',
    questions: [
      {
        ask: 'What did Abraham do that God counted as righteousness?',
        options: ['He believed God', 'He built a tower', 'He gave money', 'He fought a battle'],
        correct: 0,
        teach: '"Abraham believed God, and it was accounted to him for righteousness." Faith, not works.',
      },
      {
        ask: 'How old was Abraham when he trusted God’s promise of a child?',
        options: ['About one hundred years old', 'Twenty', 'Forty', 'Ten'],
        correct: 0,
        teach: 'About a hundred! The promise looked impossible — and he believed God anyway.',
      },
      {
        ask: 'Abraham was "fully persuaded that God had power to do what he had promised." What does fully persuaded mean?',
        accept: ['completely sure', 'totally sure', 'no doubt', 'certain', 'really believed', 'sure'],
        sample: 'Completely sure, with no doubt left.',
        teach: 'Sure all the way through. That is the faith our memory verse describes.',
      },
      {
        ask: 'God promised Abraham as many children as the stars. Did God keep His promise?',
        options: ['Yes — God always keeps His promises', 'No', 'Only partly', 'Nobody knows'],
        correct: 0,
        teach: 'Yes. Abraham became the father of many nations, just as God said. God is faithful.',
        grades: [1],
      },
      {
        ask: 'Paul says Abraham’s story was written down "for our sake also." How is our faith like Abraham’s?',
        accept: ['we believe god too', 'we trust the promise', 'we believe in jesus', 'trusting what god says', 'same kind of faith'],
        sample: 'We trust God’s promise too — that Jesus was raised for us.',
        teach: 'Same trust, same faithful God. Abraham looked forward to the promise; we look back at the cross.',
        grades: [3],
      },
    ],
  },
  {
    week: 8,
    title: 'Peace with God',
    reference: 'Romans 5:1-11',
    summary:
      'What do believers get when God declares them righteous? Paul opens this chapter with the answer: peace with God — a peace that holds even on the hardest days.',
    art: 'dove',
    minutes: 17,
    passage: [
      "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ, through whom we have gained access by faith into this grace in which we now stand. And we boast in the hope of the glory of God.",
      "Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope. And hope does not put us to shame, because God’s love has been poured out into our hearts through the Holy Spirit, who has been given to us.",
      "You see, at just the right time, when we were still powerless, Christ died for the ungodly. Very rarely will anyone die for a righteous person, though for a good person someone might possibly dare to die. But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
      "Since we have now been justified by his blood, how much more shall we be saved from God’s wrath through him! For if, while we were God’s enemies, we were reconciled to him through the death of his Son, how much more, having been reconciled, shall we be saved through his life! Not only is this so, but we also boast in God through our Lord Jesus Christ, through whom we have now received reconciliation.",
    ],
    memoryVerse: {
      text: 'Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.',
      reference: 'Romans 5:1',
    },
    truth: 'Believers have peace with God that gives hope at all times.',
    attribute: { name: 'Love', meaning: 'God proved His love for us when Jesus died on the cross.' },
    doctrine: { term: 'Reconciliation', meaning: 'becoming friends with God again' },
    gospel: 'Jesus is the only way to have peace with God.',
    questions: [
      {
        ask: 'What do believers have with God, now that they are justified by faith?',
        options: ['Peace', 'A contest', 'A long list of chores', 'Nothing'],
        correct: 0,
        teach: 'Peace with God, through our Lord Jesus Christ. The war is over.',
      },
      {
        ask: 'The passage builds a chain: suffering produces perseverance, perseverance produces character, and character produces...',
        options: ['Hope', 'Money', 'Sleep', 'Worry'],
        correct: 0,
        teach: 'Hope — and hope does not disappoint, because God’s love is already poured into our hearts.',
      },
      {
        ask: 'When did Christ die for us — after we became good, or while we were still sinners?',
        options: ['While we were still sinners', 'After we became good', 'Only for perfect people', 'The passage does not say'],
        correct: 0,
        teach: 'While we were still sinners. That is how God proves His love — He did not wait for us to deserve it.',
      },
      {
        ask: 'What does it mean to be reconciled with someone?',
        accept: ['friends again', 'make up', 'peace again', 'become friends', 'not enemies anymore'],
        sample: 'To become friends again after being apart.',
        teach: 'Friends again. We were far from God, and Jesus brought us near.',
        grades: [1],
      },
      {
        ask: 'How can believers "rejoice in sufferings"? What do hard times produce, according to this passage?',
        accept: ['perseverance', 'character', 'hope', 'they make us stronger', 'endurance', 'patience'],
        sample: 'Hard times build perseverance, then character, then hope.',
        teach: 'God wastes nothing — even suffering becomes a workshop where hope is built.',
        grades: [3],
      },
    ],
  },
  {
    week: 9,
    title: 'God’s Gift of Righteousness',
    reference: 'Romans 5:12-21',
    summary:
      'One man’s choice brought sin into the world. One Man’s obedience brought the free gift of life. This week Paul sets Adam and Jesus side by side.',
    art: 'gift',
    minutes: 17,
    passage: [
      "Therefore, just as sin entered the world through one man, and death through sin, and in this way death came to all people, because all sinned— To be sure, sin was in the world before the law was given, but sin is not charged against anyone’s account where there is no law. Nevertheless, death reigned from the time of Adam to the time of Moses, even over those who did not sin by breaking a command, as did Adam, who is a pattern of the one to come.",
      "But the gift is not like the trespass. For if the many died by the trespass of the one man, how much more did God’s grace and the gift that came by the grace of the one man, Jesus Christ, overflow to the many! Nor can the gift of God be compared with the result of one man’s sin: The judgment followed one sin and brought condemnation, but the gift followed many trespasses and brought justification. For if, by the trespass of the one man, death reigned through that one man, how much more will those who receive God’s abundant provision of grace and of the gift of righteousness reign in life through the one man, Jesus Christ!",
      "Consequently, just as one trespass resulted in condemnation for all people, so also one righteous act resulted in justification and life for all people. For just as through the disobedience of the one man the many were made sinners, so also through the obedience of the one man the many will be made righteous.",
      "The law was brought in so that the trespass might increase. But where sin increased, grace increased all the more, so that, just as sin reigned in death, so also grace might reign through righteousness to bring eternal life through Jesus Christ our Lord.",
    ],
    memoryVerse: {
      text: 'Consequently, just as one trespass resulted in condemnation for all people, so also one righteous act resulted in justification and life for all people.',
      reference: 'Romans 5:18',
    },
    truth: 'Jesus’s righteousness defeated sin.',
    attribute: { name: 'Gracious', meaning: 'God shows kindness to people who deserve His wrath.' },
    doctrine: { term: 'Grace', meaning: 'God’s kindness that we did not earn' },
    gospel: 'Salvation is given by God’s grace through faith in Jesus.',
    questions: [
      {
        ask: 'Through which man did sin enter the world?',
        options: ['Adam', 'Abraham', 'Moses', 'David'],
        correct: 0,
        teach: 'Adam — one man’s disobedience, and sin spread to everyone after him.',
      },
      {
        ask: 'Paul compares Adam and Jesus. What did each one bring?',
        options: [
          'Adam brought sin and death; Jesus brought righteousness and life',
          'They both brought the same thing',
          'Adam brought life; Jesus brought rules',
          'Neither brought anything',
        ],
        correct: 0,
        teach: 'One trespass brought condemnation; one righteous act brought justification and life.',
      },
      {
        ask: 'Where sin abounded, what abounded even more?',
        options: ['Grace', 'Rules', 'Sadness', 'Silence'],
        correct: 0,
        teach: 'Grace abounded more exceedingly. However big sin grew, grace grew bigger.',
      },
      {
        ask: 'What is grace?',
        accept: ['kindness we did not earn', 'a free gift', 'god being kind', 'kindness', 'undeserved kindness'],
        sample: 'God’s kindness that we did not earn.',
        teach: 'Kindness we never earned and could never buy. That is grace.',
        grades: [1],
      },
      {
        ask: 'Why does Paul call righteousness a GIFT and not a wage?',
        accept: ['we did not earn it', 'gifts are free', 'wages are earned', 'it is free', 'jesus earned it'],
        sample: 'A wage is earned; a gift is free. Jesus earned it and gives it away.',
        teach: 'Wages you work for. Gifts you simply receive. Righteousness comes wrapped, not paid.',
        grades: [3],
      },
    ],
  },
  {
    week: 10,
    title: 'Death to Sin',
    reference: 'Romans 6:1-11',
    summary:
      'If grace covers sin, should we just keep sinning? Paul answers with the strongest no in the whole letter — because believers have been set free.',
    art: 'chains',
    minutes: 17,
    passage: [
      "What shall we say, then? Shall we go on sinning so that grace may increase? By no means! We are those who have died to sin; how can we live in it any longer?",
      "Or don’t you know that all of us who were baptized into Christ Jesus were baptized into his death? We were therefore buried with him through baptism into death in order that, just as Christ was raised from the dead through the glory of the Father, we too may live a new life.",
      "For if we have been united with him in a death like his, we will certainly also be united with him in a resurrection like his. For we know that our old self was crucified with him so that the body ruled by sin might be done away with, that we should no longer be slaves to sin— because anyone who has died has been set free from sin.",
      "Now if we died with Christ, we believe that we will also live with him. For we know that since Christ was raised from the dead, he cannot die again; death no longer has mastery over him. The death he died, he died to sin once for all; but the life he lives, he lives to God. In the same way, count yourselves dead to sin but alive to God in Christ Jesus.",
    ],
    memoryVerse: {
      text: 'In the same way, count yourselves dead to sin but alive to God in Christ Jesus.',
      reference: 'Romans 6:11',
    },
    truth: 'Jesus frees believers from sin’s power.',
    attribute: { name: 'Omnipotent', meaning: 'God can do anything.' },
    doctrine: { term: 'Freedom from Sin', meaning: 'being set free from sin’s penalty and power' },
    gospel: 'Everyone who trusts in Jesus for salvation is set free from sin’s penalty and power.',
    questions: [
      {
        ask: 'Paul asks: "Shall we continue in sin, that grace may abound?" What is his answer?',
        options: ['May it never be!', 'Yes, a little', 'Only on weekends', 'He does not answer'],
        correct: 0,
        teach: 'May it never be! Grace is freedom FROM sin, never permission FOR it.',
      },
      {
        ask: 'Believers walk in newness of life because Christ was...',
        options: ['Raised from the dead', 'Very famous', 'A good teacher only', 'Always traveling'],
        correct: 0,
        teach: 'Raised from the dead. His new life becomes our new life.',
      },
      {
        ask: 'How many times did Christ die to sin?',
        options: ['One time — once for all', 'Every year', 'Seven times', 'It never happened'],
        correct: 0,
        teach: 'Once, for all. The work is finished and never needs repeating.',
      },
      {
        ask: 'A prisoner whose chains fall off does not keep sitting in the cell. What should someone freed from sin do?',
        accept: ['walk out', 'live free', 'leave the cell', 'live for god', 'stop sinning', 'walk in new life'],
        sample: 'Walk out and live free — alive to God.',
        teach: 'Freedom is for walking in. Dead to sin, alive to God.',
        grades: [3],
      },
      {
        ask: 'Our verse says believers are "alive to God." Who makes that possible?',
        options: ['Jesus', 'Ourselves', 'Teachers', 'No one'],
        correct: 0,
        teach: 'Jesus — in Christ Jesus our Lord, says the verse. He is the one who sets people free.',
        grades: [1],
      },
    ],
  },
  {
    week: 11,
    title: 'Alive to God',
    reference: 'Romans 6:12-23',
    summary:
      'Free people still choose whom they will serve. Paul says our hands, feet, and words can be tools for wrong — or instruments for God.',
    art: 'sunrise',
    minutes: 17,
    passage: [
      "Therefore do not let sin reign in your mortal body so that you obey its evil desires. Do not offer any part of yourself to sin as an instrument of wickedness, but rather offer yourselves to God as those who have been brought from death to life; and offer every part of yourself to him as an instrument of righteousness. For sin shall no longer be your master, because you are not under the law, but under grace.",
      "What then? Shall we sin because we are not under the law but under grace? By no means! Don’t you know that when you offer yourselves to someone as obedient slaves, you are slaves of the one you obey—whether you are slaves to sin, which leads to death, or to obedience, which leads to righteousness? But thanks be to God that, though you used to be slaves to sin, you have come to obey from your heart the pattern of teaching that has now claimed your allegiance. You have been set free from sin and have become slaves to righteousness.",
      "When you were slaves to sin, you were free from the control of righteousness. What benefit did you reap at that time from the things you are now ashamed of? Those things result in death! But now that you have been set free from sin and have become slaves of God, the benefit you reap leads to holiness, and the result is eternal life. For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.",
    ],
    memoryVerse: {
      text: 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.',
      reference: 'Romans 6:23',
    },
    truth: 'Jesus frees believers to live holy lives.',
    attribute: { name: 'Good', meaning: 'God is perfectly loving and always does what is right.' },
    doctrine: { term: 'Redemption', meaning: 'being bought back and set free' },
    gospel: 'The Holy Spirit helps believers live to please God.',
    questions: [
      {
        ask: 'What are the wages of sin?',
        options: ['Death', 'Gold', 'A day off', 'Candy'],
        correct: 0,
        teach: 'The wages of sin is death — that is what sin pays out in the end.',
      },
      {
        ask: 'What is the GIFT of God?',
        options: ['Eternal life in Christ Jesus our Lord', 'A new house', 'Long summers', 'Silver coins'],
        correct: 0,
        teach: 'Eternal life. Sin pays wages; God gives gifts. Our whole verse in one contrast.',
      },
      {
        ask: 'Paul says to offer our bodies as instruments of righteousness. Name one way your hands or words could be an instrument for good this week.',
        accept: ['help', 'kind words', 'share', 'hug', 'encourage', 'clean up', 'pray', 'i can'],
        sample: 'My hands can help carry things, and my words can encourage my sister.',
        teach: 'Yes — the same hands and words, pointed at goodness. That is what instruments of righteousness means.',
      },
      {
        ask: 'Everyone serves something. According to Paul, what are the two choices?',
        options: ['Sin, or obedience to God', 'Work or play', 'School or home', 'There are no choices'],
        correct: 0,
        teach: 'Sin leading to death, or obedience leading to righteousness. Every heart serves one or the other.',
        grades: [3],
      },
      {
        ask: 'Is eternal life something we buy or something God gives?',
        options: ['God gives it as a free gift', 'We buy it', 'We win it in a race', 'We find it'],
        correct: 0,
        teach: 'A free gift, in Christ Jesus our Lord.',
        grades: [1],
      },
    ],
  },
  {
    week: 12,
    title: 'The Law and the Believer',
    reference: 'Romans 7',
    summary:
      'Paul gets very honest this week: even people who love God still struggle with sin. If you have ever done the wrong thing you did not want to do, this chapter understands you.',
    art: 'tablets_heart',
    minutes: 18,
    passage: [
      "What shall we say, then? Is the law sinful? Certainly not! Nevertheless, I would not have known what sin was had it not been for the law. For I would not have known what coveting really was if the law had not said, “You shall not covet.”",
      "So then, the law is holy, and the commandment is holy, righteous and good.",
      "We know that the law is spiritual; but I am unspiritual, sold as a slave to sin. I do not understand what I do. For what I want to do I do not do, but what I hate I do.",
      "For I know that good itself does not dwell in me, that is, in my sinful nature. For I have the desire to do what is good, but I cannot carry it out. For I do not do the good I want to do, but the evil I do not want to do—this I keep on doing.",
      "So I find this law at work: Although I want to do good, evil is right there with me. For in my inner being I delight in God’s law; but I see another law at work in me, waging war against the law of my mind and making me a prisoner of the law of sin at work within me. What a wretched man I am! Who will rescue me from this body that is subject to death? Thanks be to God, who delivers me through Jesus Christ our Lord! So then, I myself in my mind am a slave to God’s law, but in my sinful nature a slave to the law of sin.",
    ],
    memoryVerse: {
      text: 'Thanks be to God, who delivers me through Jesus Christ our Lord!',
      reference: 'Romans 7:25a',
    },
    truth: 'Believers belong to God even though they still sin.',
    attribute: { name: 'Father', meaning: 'God has a loving relationship with every believer that lasts forever.' },
    doctrine: { term: 'Sanctification', meaning: 'God making a believer more like Jesus, little by little' },
    gospel: 'Jesus frees believers from sin’s power.',
    questions: [
      {
        ask: 'Is the law sin, according to Paul?',
        options: ['No — the law is holy, righteous, and good', 'Yes, the law is bad', 'The law is a secret', 'Paul does not say'],
        correct: 0,
        teach: 'Never! The law is good — it shows us sin the way light shows dust.',
      },
      {
        ask: 'What honest struggle does Paul describe?',
        options: [
          'He does the wrong he hates instead of the good he wants',
          'He cannot read',
          'He is afraid of Rome',
          'He has no struggles',
        ],
        correct: 0,
        teach: 'The good he wants, he does not do; the wrong he hates, he does. Even apostles know that fight.',
      },
      {
        ask: 'Paul cries, "Who will deliver me?" What is his answer?',
        options: ['Thanks be to God — through Jesus Christ our Lord!', 'No one can', 'He must try harder', 'The law will'],
        correct: 0,
        teach: 'The cry becomes our memory verse: God delivers, through Jesus.',
      },
      {
        ask: 'Have you ever done something wrong even though you knew better? How did it feel?',
        accept: ['yes', 'bad', 'sorry', 'sad', 'guilty', 'i felt'],
        sample: 'Yes — I felt sorry afterward.',
        teach: 'That feeling is what Paul describes. And his rescue is ours too: Jesus, not trying harder alone.',
        grades: [1],
      },
      {
        ask: 'Believers still sin, yet still belong to God. Why is that comforting rather than an excuse to sin?',
        accept: ['god keeps us', 'we are still his', 'he forgives', 'we keep fighting sin', 'his love does not quit', 'not an excuse'],
        sample: 'God does not give up on us — so we keep fighting sin without fear of losing His love.',
        teach: 'A child who stumbles is still in the family. That security is fuel for the fight, not a pass from it.',
        grades: [3],
      },
    ],
  },
  {
    week: 13,
    title: 'Life Through the Spirit',
    reference: 'Romans 8:1-17',
    summary:
      'After the struggle of chapter seven comes the most freeing sentence in the letter: no condemnation. And God does not leave believers to try alone — His own Spirit moves in.',
    art: 'flame',
    minutes: 18,
    passage: [
      "Therefore, there is now no condemnation for those who are in Christ Jesus, because through Christ Jesus the law of the Spirit who gives life has set you free from the law of sin and death. For what the law was powerless to do because it was weakened by the flesh, God did by sending his own Son in the likeness of sinful flesh to be a sin offering. And so he condemned sin in the flesh, in order that the righteous requirement of the law might be fully met in us, who do not live according to the flesh but according to the Spirit.",
      "Those who live according to the flesh have their minds set on what the flesh desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires. The mind governed by the flesh is death, but the mind governed by the Spirit is life and peace.",
      "You, however, are not in the realm of the flesh but are in the realm of the Spirit, if indeed the Spirit of God lives in you. And if anyone does not have the Spirit of Christ, they do not belong to Christ. But if Christ is in you, then even though your body is subject to death because of sin, the Spirit gives life because of righteousness. And if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies because of his Spirit who lives in you.",
      "Therefore, brothers and sisters, we have an obligation—but it is not to the flesh, to live according to it. For if you live according to the flesh, you will die; but if by the Spirit you put to death the misdeeds of the body, you will live. For those who are led by the Spirit of God are the children of God. The Spirit you received does not make you slaves, so that you live in fear again; rather, the Spirit you received brought about your adoption to sonship. And by him we cry, “Abba, Father.”",
      "The Spirit himself testifies with our spirit that we are God’s children. Now if we are children, then we are heirs—heirs of God and co-heirs with Christ, if indeed we share in his sufferings in order that we may also share in his glory.",
    ],
    memoryVerse: {
      text: 'Therefore, there is now no condemnation for those who are in Christ Jesus.',
      reference: 'Romans 8:1',
    },
    truth: 'The Holy Spirit gives believers power to live for God.',
    attribute: { name: 'Guide', meaning: 'The Holy Spirit leads believers to live for God.' },
    doctrine: { term: 'The Holy Spirit', meaning: 'God living in believers to help them' },
    gospel: 'Believers receive the Holy Spirit through faith in Christ.',
    questions: [
      {
        ask: 'What is there NONE of for those who are in Christ Jesus?',
        options: ['Condemnation', 'Homework', 'Weather', 'Waiting'],
        correct: 0,
        teach: 'No condemnation. Not less — none. That is our memory verse.',
      },
      {
        ask: 'Who comes to live inside believers?',
        options: ['The Spirit of God', 'An angel', 'Nobody', 'A prophet'],
        correct: 0,
        teach: 'God’s own Spirit dwells in believers — a helper closer than breath.',
      },
      {
        ask: 'What special name do God’s children get to call Him?',
        options: ['Abba — Father', 'Sir', 'Judge only', 'Stranger'],
        correct: 0,
        teach: '"Abba! Father!" — the warm word a child uses for a dad who is near.',
      },
      {
        ask: 'The Spirit tells our hearts something wonderful. What are believers called?',
        accept: ['children of god', 'children', 'gods children', 'his kids', 'heirs'],
        sample: 'Children of God.',
        teach: 'Children of God — and if children, then heirs, sharing everything with Jesus.',
        grades: [1],
      },
      {
        ask: 'The law was weak to save us. What did God do that the law could not?',
        accept: ['sent his son', 'sent jesus', 'god did it himself', 'jesus condemned sin', 'the cross'],
        sample: 'God sent His own Son to do what the law never could.',
        teach: 'Rules could point the way but not carry us there. So God came Himself.',
        grades: [3],
      },
    ],
  },
  {
    week: 14,
    title: 'Suffering and Glory',
    reference: 'Romans 8:18-27',
    summary:
      'Our last lesson looks at hard days with honest eyes — and then looks up. What is coming, Paul says, will outshine every suffering. And until then, the Spirit helps us pray.',
    art: 'crown',
    minutes: 18,
    passage: [
      "I consider that our present sufferings are not worth comparing with the glory that will be revealed in us. For the creation waits in eager expectation for the children of God to be revealed. For the creation was subjected to frustration, not by its own choice, but by the will of the one who subjected it, in hope that the creation itself will be liberated from its bondage to decay and brought into the freedom and glory of the children of God.",
      "We know that the whole creation has been groaning as in the pains of childbirth right up to the present time. Not only so, but we ourselves, who have the firstfruits of the Spirit, groan inwardly as we wait eagerly for our adoption to sonship, the redemption of our bodies.",
      "For in this hope we were saved. But hope that is seen is no hope at all. Who hopes for what they already have? But if we hope for what we do not yet have, we wait for it patiently.",
      "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans. And he who searches our hearts knows the mind of the Spirit, because the Spirit intercedes for God’s people in accordance with the will of God.",
    ],
    memoryVerse: {
      text: 'I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.',
      reference: 'Romans 8:18',
    },
    truth: 'Believers eagerly wait for God’s promised future glory.',
    attribute: { name: 'Glory', meaning: 'God’s glory is the total of all His attributes.' },
    doctrine: { term: 'Suffering', meaning: 'hard times, which God promises to one day end' },
    gospel: 'One day God will remove all suffering from the lives of His children.',
    questions: [
      {
        ask: 'How do today’s sufferings compare with the glory that is coming?',
        options: [
          'They are not worth comparing — the glory is far greater',
          'They are about equal',
          'Suffering is greater',
          'Paul does not say',
        ],
        correct: 0,
        teach: 'Not worth comparing. Put them on a scale and glory outweighs everything.',
      },
      {
        ask: 'What is the whole creation doing while it waits?',
        options: ['Groaning, like waiting in pain for something better', 'Sleeping', 'Celebrating', 'Nothing'],
        correct: 0,
        teach: 'Groaning — the whole world aches for the day God makes everything new.',
      },
      {
        ask: 'When we do not know how to pray, who helps us?',
        options: ['The Spirit himself', 'Nobody', 'Only pastors', 'The weather'],
        correct: 0,
        teach: 'The Spirit himself prays for us, deeper than words. You are never praying alone.',
      },
      {
        ask: 'Hope means waiting for something we cannot see yet. What is something you hope for?',
        accept: ['i hope', 'heaven', 'to see', 'one day', 'that'],
        sample: 'I hope for the day when nothing hurts anymore.',
        teach: 'Hold that hope. Waiting with patience is what hope looks like on ordinary days.',
        grades: [1],
      },
      {
        ask: 'You finished all fourteen lessons of Romans! What is one thing from this whole letter you want to remember?',
        accept: ['grace', 'faith', 'jesus', 'no condemnation', 'peace', 'the gospel', 'god', 'i want to remember'],
        sample: 'That there is now no condemnation for those in Christ Jesus.',
        teach: 'Carry it with you. Paul wrote this letter so it would travel — and now it travels with you.',
        grades: [3],
      },
    ],
  },
];
