import type { Star } from '../../types';

/**
 * Grade 1 reading comprehension.
 *
 * Passages run 60–120 words at a first-grade decodable level, and every star
 * mixes literal recall ("what did she find?") with inference ("why do you think
 * she was worried?"). The passage stays on screen throughout — this is
 * comprehension practice, not a memory test. Open questions are answered by
 * voice or typing, and accept a range of phrasings.
 */

export const grade1Reading: Star[] = [
  {
    id: 'g1_read_01',
    subject: 'reading',
    grade: 1,
    title: 'The Lost Mitten',
    blurb: 'Our first story is about a girl who loses something small and finds something better.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Lost Mitten',
        preview: [
          { word: 'mitten', meaning: 'a warm cover for your hand' },
          { word: 'branch', meaning: 'the arm of a tree' },
        ],
        paragraphs: [
          'Mia lost her red mitten in the snow. She looked and looked. She could not find it.',
          'Then she saw something red up in a tree. A bird had taken her mitten! The bird had put it on a branch.',
          'Inside the mitten were four tiny blue eggs. The bird had made a nest.',
          'Mia did not take her mitten back. She ran home and got a warm sock for the other hand. "The bird needs it more," she said.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_01_c1',
          prompt: 'What did Mia lose?',
          options: ['Her red mitten', 'Her blue hat', 'Her school bag', 'Her boot'],
          correct: 0,
          teach: 'Yes. The very first sentence tells us she lost her red mitten.',
        },
        {
          kind: 'choice',
          id: 'g1_read_01_c2',
          prompt: 'Where did Mia find the mitten?',
          options: ['Under the snow', 'In a tree', 'At school', 'In her house'],
          correct: 1,
          teach: 'Right. She saw something red up in a tree.',
        },
        {
          kind: 'choice',
          id: 'g1_read_01_c3',
          prompt: 'What was inside the mitten?',
          options: ['Snow', 'A letter', 'Four tiny blue eggs', 'Her other mitten'],
          correct: 2,
          teach: 'Four tiny blue eggs. The bird made the mitten into a nest.',
        },
        {
          kind: 'speak',
          id: 'g1_read_01_s1',
          prompt: 'Why did Mia leave her mitten in the tree? Tell me in your own words.',
          accept: [
            'the bird needed it', 'for the eggs', 'the bird made a nest',
            'the bird needs it more', 'to keep the eggs warm', 'because of the babies',
          ],
          sampleAnswer: 'Because the bird needed it for a nest.',
          hint: 'Look at the last thing Mia says.',
          teach: 'Exactly. She gave it up so the eggs would stay warm. That was kind.',
        },
        {
          kind: 'choice',
          id: 'g1_read_01_c4',
          prompt: 'What did Mia use to keep her other hand warm?',
          options: ['A sock', 'A towel', 'A glove', 'A blanket'],
          correct: 0,
          teach: 'A warm sock. She solved her own problem.',
        },
        {
          kind: 'speak',
          id: 'g1_read_01_s2',
          prompt: 'Would you have left your mitten? Tell me why or why not.',
          accept: ['yes', 'no', 'maybe', 'i would', 'i would not'],
          sampleAnswer: 'Yes, because the baby birds needed it.',
          teach: 'There is no wrong answer to that one. Thank you for thinking it through.',
        },
      ],
    },
  },
  {
    id: 'g1_read_02',
    subject: 'reading',
    grade: 1,
    title: 'A Seed in the Dark',
    blurb: 'Some things grow where you cannot see them yet.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'A Seed in the Dark',
        preview: [
          { word: 'soil', meaning: 'the dirt that plants grow in' },
          { word: 'sprout', meaning: 'the first small green part of a plant' },
        ],
        paragraphs: [
          'Ana put one small seed in a cup of soil. She gave it water. Then she waited.',
          'On day one, nothing. On day two, nothing. On day three, still nothing.',
          '"It is not working," she said. But her grandmother smiled. "It is working," she said. "You just cannot see it yet."',
          'On day six, a tiny green sprout came up. It was smaller than Ana\'s little finger. She was so happy she clapped.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_02_c1',
          prompt: 'What did Ana put in the cup?',
          options: ['A rock', 'One small seed', 'A flower', 'Some water only'],
          correct: 1,
          teach: 'One small seed, in a cup of soil.',
        },
        {
          kind: 'choice',
          id: 'g1_read_02_c2',
          prompt: 'On which day did the sprout come up?',
          options: ['Day one', 'Day three', 'Day six', 'Day ten'],
          correct: 2,
          teach: 'Day six. She had to wait a long time.',
        },
        {
          kind: 'speak',
          id: 'g1_read_02_s1',
          prompt: 'Grandmother said, "You just cannot see it yet." What did she mean?',
          accept: [
            'it was growing under the soil', 'it was growing', 'growing underground',
            'it was working under the dirt', 'the seed was growing where she could not see',
            'it is growing in the dirt',
          ],
          sampleAnswer: 'The seed was growing under the soil where Ana could not see it.',
          hint: 'Where was the seed hiding?',
          teach: 'Yes. The roots grow down first, before anything shows on top.',
        },
        {
          kind: 'choice',
          id: 'g1_read_02_c3',
          prompt: 'How big was the sprout?',
          options: [
            'Bigger than Ana',
            'As big as a tree',
            'Smaller than her little finger',
            'The size of the cup',
          ],
          correct: 2,
          teach: 'Smaller than her little finger. Very tiny, but very alive.',
        },
        {
          kind: 'speak',
          id: 'g1_read_02_s2',
          prompt: 'What is something you had to wait a long time for?',
          accept: ['birthday', 'christmas', 'a trip', 'my tooth', 'a present', 'growing'],
          sampleAnswer: 'I waited a long time for my birthday.',
          teach: 'Waiting is hard. You are learning to do a hard thing.',
        },
      ],
    },
  },
  {
    id: 'g1_read_03',
    subject: 'reading',
    grade: 1,
    title: 'The Moon Follows Me',
    blurb: 'A story about a big question and a good answer.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Moon Follows Me',
        preview: [{ word: 'follow', meaning: 'to come along behind' }],
        paragraphs: [
          'In the car at night, Zoe looked out the window. The moon was there.',
          'They drove past the shop. The moon was still there. They drove past the trees. The moon was still there.',
          '"Dad!" she said. "The moon is following us!"',
          'Her dad laughed. "The moon is very, very far away," he said. "So far that it does not move much when we do. It looks like it is following you."',
          'Zoe waved at the moon anyway. Just in case.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_03_c1',
          prompt: 'Where was Zoe?',
          options: ['In the car', 'In bed', 'At school', 'On a boat'],
          correct: 0,
          teach: 'In the car at night, looking out the window.',
        },
        {
          kind: 'choice',
          id: 'g1_read_03_c2',
          prompt: 'Why does the moon look like it is following us?',
          options: [
            'It really is following us',
            'It is very, very far away',
            'It is stuck to the car',
            'It is made of light',
          ],
          correct: 1,
          teach: 'Because it is so far away, it barely seems to move when we do.',
        },
        {
          kind: 'speak',
          id: 'g1_read_03_s1',
          prompt: 'What did Zoe do at the end of the story?',
          accept: ['waved', 'she waved at the moon', 'waved at the moon', 'wave'],
          sampleAnswer: 'She waved at the moon.',
          teach: 'She waved. Just in case. I like her very much.',
        },
        {
          kind: 'choice',
          id: 'g1_read_03_c3',
          prompt: 'How do you think Zoe felt about the moon?',
          options: ['Scared of it', 'Bored by it', 'Curious about it', 'Angry at it'],
          correct: 2,
          teach: 'Curious. She noticed something and asked about it. That is how learning starts.',
        },
        {
          kind: 'speak',
          id: 'g1_read_03_s2',
          prompt: 'Ask me a question about the moon. Any question you want.',
          accept: ['why', 'what', 'how', 'where', 'when', 'is', 'does', 'can'],
          sampleAnswer: 'Why does the moon change shape?',
          teach: 'That is a real question, and real questions are the best kind.',
        },
      ],
    },
  },
  {
    id: 'g1_read_04',
    subject: 'reading',
    grade: 1,
    title: 'Sofia Shares the Swing',
    blurb: 'This one is about a hard choice on the playground.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Sofia Shares the Swing',
        preview: [{ word: 'recess', meaning: 'play time at school' }],
        paragraphs: [
          'There was only one swing left at recess. Sofia got there first.',
          'A new girl stood close by. She did not say anything. She just looked at the swing.',
          'Sofia wanted to swing. She had waited all day. But she looked at the new girl again.',
          '"Do you want to go first?" Sofia asked. "Then me. Then you. We can take turns."',
          'The new girl smiled. Her name was Nora. By the end of recess, they were friends.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_04_c1',
          prompt: 'How many swings were left?',
          options: ['None', 'One', 'Two', 'Many'],
          correct: 1,
          teach: 'Only one. That is what made it a hard choice.',
        },
        {
          kind: 'speak',
          id: 'g1_read_04_s1',
          prompt: 'Sofia had waited all day for that swing. Why did she offer it to Nora anyway?',
          accept: [
            'to be kind', 'she was being nice', 'she wanted to share',
            'the girl was new', 'to make a friend', 'because she is kind',
            'to be nice', 'sharing',
          ],
          sampleAnswer: 'She wanted to be kind to the new girl.',
          hint: 'Think about how the new girl was feeling.',
          teach: 'She gave up something she wanted. That is what makes it kind and not just easy.',
        },
        {
          kind: 'choice',
          id: 'g1_read_04_c2',
          prompt: 'What was the new girl\'s name?',
          options: ['Sofia', 'Mia', 'Nora', 'Ana'],
          correct: 2,
          teach: 'Nora. We learn her name only after Sofia is kind to her.',
        },
        {
          kind: 'choice',
          id: 'g1_read_04_c3',
          prompt: 'What happened at the end?',
          options: [
            'They became friends',
            'They argued',
            'The swing broke',
            'Recess was cancelled',
          ],
          correct: 0,
          teach: 'They became friends by the end of recess.',
        },
        {
          kind: 'speak',
          id: 'g1_read_04_s2',
          prompt: 'Tell me about a time you shared something that was hard to share.',
          accept: ['toy', 'my', 'i shared', 'snack', 'book', 'i gave', 'sister', 'brother'],
          sampleAnswer: 'I shared my snack with my sister even though I wanted it.',
          teach: 'Thank you for telling me. That took honesty.',
        },
      ],
    },
  },
  {
    id: 'g1_read_05',
    subject: 'reading',
    grade: 1,
    title: 'Why the Sky Is Not Empty',
    blurb: 'A little bit of true science, told like a story.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'Why the Sky Is Not Empty',
        preview: [
          { word: 'empty', meaning: 'having nothing inside' },
          { word: 'air', meaning: 'what we breathe, even though we cannot see it' },
        ],
        paragraphs: [
          'Look up. The sky can seem empty. But it is not.',
          'The sky is full of air. You cannot see air, but you can feel it. When the wind blows your hair, that is air moving.',
          'The sky is full of water too. Clouds are made of tiny drops of water. So many drops that we can see them.',
          'And past all of that, far past the clouds, the sky is full of stars. They are up there in the daytime as well. The sun is just so bright that we cannot see them.',
          'The sky is one of the fullest places there is.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_05_c1',
          prompt: 'What are clouds made of?',
          options: ['Cotton', 'Tiny drops of water', 'Smoke', 'Snow only'],
          correct: 1,
          teach: 'Tiny drops of water, so many that we can see them together.',
        },
        {
          kind: 'choice',
          id: 'g1_read_05_c2',
          prompt: 'Why can we not see the stars in the daytime?',
          options: [
            'They go away',
            'They turn off',
            'The sun is too bright',
            'Clouds cover them',
          ],
          correct: 2,
          teach: 'The stars are still there. The sun is just too bright for our eyes.',
        },
        {
          kind: 'speak',
          id: 'g1_read_05_s1',
          prompt: 'The story says you cannot see air, but you can feel it. When can you feel air?',
          accept: [
            'wind', 'when the wind blows', 'when it is windy', 'blowing',
            'when i blow', 'a fan', 'breeze',
          ],
          sampleAnswer: 'When the wind blows my hair.',
          teach: 'Yes. You cannot see it, and it is still real. That is worth remembering.',
        },
        {
          kind: 'choice',
          id: 'g1_read_05_c3',
          prompt: 'What is the big idea of this story?',
          options: [
            'The sky is boring',
            'The sky is full of things',
            'Clouds are the best',
            'You should not look up',
          ],
          correct: 1,
          teach: 'The whole story builds to that last line: the sky is one of the fullest places there is.',
        },
        {
          kind: 'speak',
          id: 'g1_read_05_s2',
          prompt: 'Name one thing the story says is up in the sky.',
          accept: ['air', 'water', 'clouds', 'stars', 'sun', 'wind'],
          sampleAnswer: 'Stars.',
          teach: 'That is right. Air, water, clouds, and stars — all up there at once.',
        },
      ],
    },
  },
  {
    id: 'g1_read_06',
    subject: 'reading',
    grade: 1,
    title: 'The Dog Who Would Not Bark',
    blurb: 'Everyone thought something was wrong. They were looking at it the wrong way.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Dog Who Would Not Bark',
        preview: [{ word: 'shelter', meaning: 'a safe place where lost animals wait for a home' }],
        paragraphs: [
          'At the shelter there was a small brown dog. She did not bark. Not once.',
          'People came and looked at her. "Is she sick?" they asked. Then they walked on to the loud, happy dogs.',
          'Lily sat down by the cage. She did not talk. She just sat.',
          'After a long time, the small brown dog came close. She put her nose through the wire and touched Lily\'s hand.',
          '"She was not sick," Lily told her mom. "She was just waiting for someone quiet."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_06_c1',
          prompt: 'What was strange about the small brown dog?',
          options: ['She was very big', 'She did not bark', 'She could not walk', 'She was blue'],
          correct: 1,
          teach: 'She did not bark. Not once.',
        },
        {
          kind: 'choice',
          id: 'g1_read_06_c2',
          prompt: 'What did Lily do that the other people did not do?',
          options: [
            'She sat quietly and waited',
            'She shouted at the dog',
            'She opened the cage',
            'She gave her food',
          ],
          correct: 0,
          teach: 'She sat down and waited. She let the dog come to her.',
        },
        {
          kind: 'speak',
          id: 'g1_read_06_s1',
          prompt: 'Why do you think the other people walked away?',
          accept: [
            'they thought she was sick', 'she was quiet', 'they wanted a loud dog',
            'they wanted happy dogs', 'they did not wait', 'they thought something was wrong',
          ],
          sampleAnswer: 'They thought something was wrong with her because she was quiet.',
          hint: 'What did they ask before they walked on?',
          teach: 'They decided too fast. Lily waited long enough to find out the truth.',
        },
        {
          kind: 'speak',
          id: 'g1_read_06_s2',
          prompt: 'What did the dog do when she finally came close?',
          accept: [
            'touched her hand', 'put her nose through', 'touched lily',
            'she touched her hand with her nose', 'nose',
          ],
          sampleAnswer: 'She touched Lily\'s hand with her nose.',
          teach: 'A very small thing. And it was the whole story.',
        },
        {
          kind: 'choice',
          id: 'g1_read_06_c3',
          prompt: 'What is the lesson of this story?',
          options: [
            'Loud is better',
            'Some good things take waiting',
            'Dogs are scary',
            'Never go to a shelter',
          ],
          correct: 1,
          teach: 'Some good things only show up if you are patient enough to wait for them.',
        },
      ],
    },
  },
  {
    id: 'g1_read_07',
    subject: 'reading',
    grade: 1,
    title: 'Ruby Builds a Bridge',
    blurb: 'What do you do when the first try falls down?',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Ruby Builds a Bridge',
        preview: [{ word: 'strong', meaning: 'able to hold a lot without breaking' }],
        paragraphs: [
          'Ruby wanted to build a bridge from blocks. She put two tall stacks down and laid one long block on top.',
          'It fell.',
          'She built it again. It fell again.',
          'Ruby stopped and looked hard at the blocks. The tall stacks were wobbly. So she made them shorter and wider.',
          'This time the bridge held. She rolled a toy car right across it. "It fell twice," she said, "and then it did not."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_07_c1',
          prompt: 'How many times did the bridge fall?',
          options: ['One time', 'Two times', 'Three times', 'It never fell'],
          correct: 1,
          teach: 'Twice. And she said so herself at the end.',
        },
        {
          kind: 'speak',
          id: 'g1_read_07_s1',
          prompt: 'What did Ruby change to make the bridge work?',
          accept: [
            'shorter and wider', 'she made them shorter', 'made the stacks wider',
            'shorter', 'wider', 'she made the stacks shorter and wider', 'the stacks',
          ],
          sampleAnswer: 'She made the stacks shorter and wider.',
          hint: 'What was wrong with the tall stacks?',
          teach: 'Shorter and wider. She did not try harder — she tried differently.',
        },
        {
          kind: 'choice',
          id: 'g1_read_07_c2',
          prompt: 'What did Ruby do before she built it the third time?',
          options: [
            'She stopped and looked hard at the blocks',
            'She gave up',
            'She asked for new blocks',
            'She cried',
          ],
          correct: 0,
          teach: 'She stopped and looked. Thinking first is part of the work.',
        },
        {
          kind: 'choice',
          id: 'g1_read_07_c3',
          prompt: 'How do you think Ruby felt at the end?',
          options: ['Proud', 'Angry', 'Bored', 'Sleepy'],
          correct: 0,
          teach: 'Proud. And she earned it, because it was hard.',
        },
        {
          kind: 'speak',
          id: 'g1_read_07_s2',
          prompt: 'Tell me about something you had to try more than once.',
          accept: ['i tried', 'riding', 'bike', 'writing', 'i could not', 'jumping', 'it was hard'],
          sampleAnswer: 'I tried to ride my bike many times before I could do it.',
          teach: 'That is exactly what Ruby did. You are already good at the hardest part.',
        },
      ],
    },
  },
  {
    id: 'g1_read_08',
    subject: 'reading',
    grade: 1,
    title: 'The Sound at Night',
    blurb: 'A story about being brave when you are still a little scared.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Sound at Night',
        preview: [{ word: 'brave', meaning: 'doing a thing even when you feel afraid' }],
        paragraphs: [
          'Ivy heard a sound in the night. Tap. Tap. Tap.',
          'She pulled the blanket up over her head. The sound kept going. Tap. Tap.',
          'Ivy took a big breath. She got out of bed and walked to the window. Her legs felt shaky.',
          'Outside, a branch was tapping on the glass. That was all. Just a branch and the wind.',
          'Ivy went back to bed. She was still a little scared. But she had looked anyway, and that felt good.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_08_c1',
          prompt: 'What was making the sound?',
          options: ['A bird', 'A branch on the window', 'Her sister', 'The rain'],
          correct: 1,
          teach: 'Just a branch tapping in the wind.',
        },
        {
          kind: 'choice',
          id: 'g1_read_08_c2',
          prompt: 'What did Ivy do first when she heard the sound?',
          options: [
            'Pulled the blanket over her head',
            'Ran to her mom',
            'Opened the window',
            'Went back to sleep',
          ],
          correct: 0,
          teach: 'She hid first. That is a very normal thing to do.',
        },
        {
          kind: 'speak',
          id: 'g1_read_08_s1',
          prompt: 'The story says Ivy was still a little scared at the end. So why did it feel good?',
          accept: [
            'she looked anyway', 'she was brave', 'because she checked',
            'she did it anyway', 'she got up', 'she was brave anyway',
            'because she was brave',
          ],
          sampleAnswer: 'Because she looked anyway, even though she was scared.',
          hint: 'What is brave: not being scared, or doing it while you are scared?',
          teach: 'Brave does not mean not scared. Brave means scared and doing it anyway.',
        },
        {
          kind: 'choice',
          id: 'g1_read_08_c3',
          prompt: 'How did Ivy\'s legs feel when she walked to the window?',
          options: ['Strong', 'Shaky', 'Cold', 'Fast'],
          correct: 1,
          teach: 'Shaky. The story tells us that on purpose, so we know it was hard.',
        },
        {
          kind: 'speak',
          id: 'g1_read_08_s2',
          prompt: 'What is something that feels a little scary to you?',
          accept: ['dark', 'the dark', 'noises', 'spiders', 'being alone', 'thunder', 'i am scared'],
          sampleAnswer: 'The dark feels a little scary to me.',
          teach: 'Thank you for saying it out loud. Saying it is its own kind of brave.',
        },
      ],
    },
  },
  {
    id: 'g1_read_09',
    subject: 'reading',
    grade: 1,
    title: 'Two Kinds of Hungry',
    blurb: 'A short story with a surprise at the end.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Two Kinds of Hungry',
        preview: [{ word: 'share', meaning: 'to give part of what you have' }],
        paragraphs: [
          'Hazel had one apple in her bag. She was very hungry.',
          'A boy at the next table had no lunch at all. He was looking at the table, not at anyone.',
          'Hazel looked at her apple. Then she looked at the boy. Then she looked at her apple again.',
          'She cut the apple in half with her hands. It was hard to do. She gave him the bigger half.',
          'She was still a bit hungry after. But something else in her felt full.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_09_c1',
          prompt: 'What did Hazel have in her bag?',
          options: ['A sandwich', 'One apple', 'Two cookies', 'Nothing'],
          correct: 1,
          teach: 'One apple. Only one.',
        },
        {
          kind: 'choice',
          id: 'g1_read_09_c2',
          prompt: 'Which half did Hazel give away?',
          options: ['The bigger half', 'The smaller half', 'Both halves', 'Neither'],
          correct: 0,
          teach: 'The bigger half. She could have given the smaller one, and she did not.',
        },
        {
          kind: 'speak',
          id: 'g1_read_09_s1',
          prompt: 'The last line says something in her felt full. What do you think that means?',
          accept: [
            'her heart', 'she felt happy', 'she felt good', 'she felt good inside',
            'her heart was full', 'happy', 'she was glad', 'she felt nice',
          ],
          sampleAnswer: 'Her heart felt full because she did something kind.',
          hint: 'Her tummy was still hungry. What part of her was not?',
          teach: 'That is the two kinds of hungry in the title. Her stomach and her heart.',
        },
        {
          kind: 'choice',
          id: 'g1_read_09_c3',
          prompt: 'How do we know the boy was uncomfortable?',
          options: [
            'He was crying',
            'He was looking at the table, not at anyone',
            'He asked for food',
            'He left the room',
          ],
          correct: 1,
          teach: 'The story shows us instead of telling us. He would not look up.',
        },
        {
          kind: 'speak',
          id: 'g1_read_09_s2',
          prompt: 'Why was it hard for Hazel to share?',
          accept: [
            'she was hungry', 'she was very hungry', 'she only had one',
            'because she wanted it', 'she wanted to eat it',
          ],
          sampleAnswer: 'Because she was very hungry and only had one apple.',
          teach: 'Right. Sharing when you have plenty is easy. This was the other kind.',
        },
      ],
    },
  },
  {
    id: 'g1_read_10',
    subject: 'reading',
    grade: 1,
    title: 'The Girl Who Asked Why',
    blurb: 'Our last story in this constellation is about the best question there is.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Girl Who Asked Why',
        preview: [
          { word: 'question', meaning: 'something you ask when you want to know' },
          { word: 'answer', meaning: 'what you say back to a question' },
        ],
        paragraphs: [
          'June asked a lot of questions. Why is grass green? Why do we sleep? Why is the ocean salty?',
          'Sometimes people said, "That is just how it is."',
          'June did not like that answer. It did not tell her anything.',
          'One day her teacher said something different. "I do not know," she said. "Let us find out together."',
          'They looked it up. They read about it. And June learned something nobody in her house had known that morning.',
          'That was the day June found out that "I do not know" can be the start of something, not the end.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_10_c1',
          prompt: 'What did June do a lot?',
          options: ['Sleep', 'Ask questions', 'Run', 'Draw'],
          correct: 1,
          teach: 'She asked questions. Lots and lots of them.',
        },
        {
          kind: 'speak',
          id: 'g1_read_10_s1',
          prompt: 'Why did June not like the answer "That is just how it is"?',
          accept: [
            'it did not tell her anything', 'it was not an answer',
            'it did not help', 'it told her nothing', 'because it did not explain',
            'it does not tell her anything',
          ],
          sampleAnswer: 'Because it did not tell her anything.',
          hint: 'The story says it right after.',
          teach: 'It sounds like an answer, but it does not explain anything at all.',
        },
        {
          kind: 'choice',
          id: 'g1_read_10_c2',
          prompt: 'What did the teacher say that was different?',
          options: [
            '"I do not know. Let us find out together."',
            '"Stop asking questions."',
            '"That is just how it is."',
            '"Ask your mother."',
          ],
          correct: 0,
          teach: 'She admitted she did not know, and then she helped June find out.',
        },
        {
          kind: 'choice',
          id: 'g1_read_10_c3',
          prompt: 'What did June learn that day?',
          options: [
            'Not to ask questions',
            'That "I do not know" can be a beginning',
            'That teachers know everything',
            'That grass is blue',
          ],
          correct: 1,
          teach: 'That is the last line, and it is the whole point of the story.',
        },
        {
          kind: 'speak',
          id: 'g1_read_10_s2',
          prompt: 'What is a question you have wondered about?',
          accept: ['why', 'what', 'how', 'where', 'when', 'who', 'i wonder', 'does', 'is'],
          sampleAnswer: 'I wonder why the sky is blue.',
          teach: 'Hold on to that one. We can go find out together, just like June did.',
        },
      ],
    },
  },
];
