import type { Star } from '../../types';

/**
 * Grade 1 reading comprehension.
 *
 * Passages run 60–120 words at a first-grade decodable level, and every star
 * mixes literal recall ("what did she find?") with inference ("why do you think
 * she was worried?"). The passage stays on screen throughout — this is
 * comprehension practice, not a memory test. Open questions are answered by
 * voice or typing, and accept a range of phrasings.
 */

export const grade1Reading: Star[] = [
  {
    id: 'g1_read_01',
    subject: 'reading',
    grade: 1,
    title: 'The Lost Mitten',
    blurb: 'Our first story is about a girl who loses something small and finds something better.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Lost Mitten',
        preview: [
          { word: 'mitten', meaning: 'a warm cover for your hand' },
          { word: 'branch', meaning: 'the arm of a tree' },
        ],
        paragraphs: [
          'Mia lost her red mitten in the snow. She looked and looked. She could not find it.',
          'Then she saw something red up in a tree. A bird had taken her mitten! The bird had put it on a branch.',
          'Inside the mitten were four tiny blue eggs. The bird had made a nest.',
          'Mia did not take her mitten back. She ran home and got a warm sock for the other hand. "The bird needs it more," she said.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_01_c1',
          prompt: 'What did Mia lose?',
          options: ['Her red mitten', 'Her blue hat', 'Her school bag', 'Her boot'],
          correct: 0,
          teach: 'Yes. The very first sentence tells us she lost her red mitten.',
        },
        {
          kind: 'choice',
          id: 'g1_read_01_c2',
          prompt: 'Where did Mia find the mitten?',
          options: ['Under the snow', 'In a tree', 'At school', 'In her house'],
          correct: 1,
          teach: 'Right. She saw something red up in a tree.',
        },
        {
          kind: 'choice',
          id: 'g1_read_01_c3',
          prompt: 'What was inside the mitten?',
          options: ['Snow', 'A letter', 'Four tiny blue eggs', 'Her other mitten'],
          correct: 2,
          teach: 'Four tiny blue eggs. The bird made the mitten into a nest.',
        },
        {
          kind: 'speak',
          id: 'g1_read_01_s1',
          prompt: 'Why did Mia leave her mitten in the tree? Tell me in your own words.',
          accept: [
            'the bird needed it', 'for the eggs', 'the bird made a nest',
            'the bird needs it more', 'to keep the eggs warm', 'because of the babies',
          ],
          sampleAnswer: 'Because the bird needed it for a nest.',
          hint: 'Look at the last thing Mia says.',
          teach: 'Exactly. She gave it up so the eggs would stay warm. That was kind.',
        },
        {
          kind: 'choice',
          id: 'g1_read_01_c4',
          prompt: 'What did Mia use to keep her other hand warm?',
          options: ['A sock', 'A towel', 'A glove', 'A blanket'],
          correct: 0,
          teach: 'A warm sock. She solved her own problem.',
        },
        {
          kind: 'speak',
          id: 'g1_read_01_s2',
          prompt: 'Would you have left your mitten? Tell me why or why not.',
          accept: ['yes', 'no', 'maybe', 'i would', 'i would not'],
          sampleAnswer: 'Yes, because the baby birds needed it.',
          teach: 'There is no wrong answer to that one. Thank you for thinking it through.',
        },
      ],
    },
  },
  {
    id: 'g1_read_02',
    subject: 'reading',
    grade: 1,
    title: 'A Seed in the Dark',
    blurb: 'Some things grow where you cannot see them yet.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'A Seed in the Dark',
        preview: [
          { word: 'soil', meaning: 'the dirt that plants grow in' },
          { word: 'sprout', meaning: 'the first small green part of a plant' },
        ],
        paragraphs: [
          'Ana put one small seed in a cup of soil. She gave it water. Then she waited.',
          'On day one, nothing. On day two, nothing. On day three, still nothing.',
          '"It is not working," she said. But her grandmother smiled. "It is working," she said. "You just cannot see it yet."',
          'On day six, a tiny green sprout came up. It was smaller than Ana\'s little finger. She was so happy she clapped.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_02_c1',
          prompt: 'What did Ana put in the cup?',
          options: ['A rock', 'One small seed', 'A flower', 'Some water only'],
          correct: 1,
          teach: 'One small seed, in a cup of soil.',
        },
        {
          kind: 'choice',
          id: 'g1_read_02_c2',
          prompt: 'On which day did the sprout come up?',
          options: ['Day one', 'Day three', 'Day six', 'Day ten'],
          correct: 2,
          teach: 'Day six. She had to wait a long time.',
        },
        {
          kind: 'speak',
          id: 'g1_read_02_s1',
          prompt: 'Grandmother said, "You just cannot see it yet." What did she mean?',
          accept: [
            'it was growing under the soil', 'it was growing', 'growing underground',
            'it was working under the dirt', 'the seed was growing where she could not see',
            'it is growing in the dirt',
          ],
          sampleAnswer: 'The seed was growing under the soil where Ana could not see it.',
          hint: 'Where was the seed hiding?',
          teach: 'Yes. The roots grow down first, before anything shows on top.',
        },
        {
          kind: 'choice',
          id: 'g1_read_02_c3',
          prompt: 'How big was the sprout?',
          options: [
            'Bigger than Ana',
            'As big as a tree',
            'Smaller than her little finger',
            'The size of the cup',
          ],
          correct: 2,
          teach: 'Smaller than her little finger. Very tiny, but very alive.',
        },
        {
          kind: 'speak',
          id: 'g1_read_02_s2',
          prompt: 'What is something you had to wait a long time for?',
          accept: ['birthday', 'christmas', 'a trip', 'my tooth', 'a present', 'growing'],
          sampleAnswer: 'I waited a long time for my birthday.',
          teach: 'Waiting is hard. You are learning to do a hard thing.',
        },
      ],
    },
  },
  {
    id: 'g1_read_03',
    subject: 'reading',
    grade: 1,
    title: 'The Moon Follows Me',
    blurb: 'A story about a big question and a good answer.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Moon Follows Me',
        preview: [{ word: 'follow', meaning: 'to come along behind' }],
        paragraphs: [
          'In the car at night, Zoe looked out the window. The moon was there.',
          'They drove past the shop. The moon was still there. They drove past the trees. The moon was still there.',
          '"Dad!" she said. "The moon is following us!"',
          'Her dad laughed. "The moon is very, very far away," he said. "So far that it does not move much when we do. It looks like it is following you."',
          'Zoe waved at the moon anyway. Just in case.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_03_c1',
          prompt: 'Where was Zoe?',
          options: ['In the car', 'In bed', 'At school', 'On a boat'],
          correct: 0,
          teach: 'In the car at night, looking out the window.',
        },
        {
          kind: 'choice',
          id: 'g1_read_03_c2',
          prompt: 'Why does the moon look like it is following us?',
          options: [
            'It really is following us',
            'It is very, very far away',
            'It is stuck to the car',
            'It is made of light',
          ],
          correct: 1,
          teach: 'Because it is so far away, it barely seems to move when we do.',
        },
        {
          kind: 'speak',
          id: 'g1_read_03_s1',
          prompt: 'What did Zoe do at the end of the story?',
          accept: ['waved', 'she waved at the moon', 'waved at the moon', 'wave'],
          sampleAnswer: 'She waved at the moon.',
          teach: 'She waved. Just in case. I like her very much.',
        },
        {
          kind: 'choice',
          id: 'g1_read_03_c3',
          prompt: 'How do you think Zoe felt about the moon?',
          options: ['Scared of it', 'Bored by it', 'Curious about it', 'Angry at it'],
          correct: 2,
          teach: 'Curious. She noticed something and asked about it. That is how learning starts.',
        },
        {
          kind: 'speak',
          id: 'g1_read_03_s2',
          prompt: 'Ask me a question about the moon. Any question you want.',
          accept: ['why', 'what', 'how', 'where', 'when', 'is', 'does', 'can'],
          sampleAnswer: 'Why does the moon change shape?',
          teach: 'That is a real question, and real questions are the best kind.',
        },
      ],
    },
  },
  {
    id: 'g1_read_04',
    subject: 'reading',
    grade: 1,
    title: 'Sofia Shares the Swing',
    blurb: 'This one is about a hard choice on the playground.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Sofia Shares the Swing',
        preview: [{ word: 'recess', meaning: 'play time at school' }],
        paragraphs: [
          'There was only one swing left at recess. Sofia got there first.',
          'A new girl stood close by. She did not say anything. She just looked at the swing.',
          'Sofia wanted to swing. She had waited all day. But she looked at the new girl again.',
          '"Do you want to go first?" Sofia asked. "Then me. Then you. We can take turns."',
          'The new girl smiled. Her name was Nora. By the end of recess, they were friends.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_04_c1',
          prompt: 'How many swings were left?',
          options: ['None', 'One', 'Two', 'Many'],
          correct: 1,
          teach: 'Only one. That is what made it a hard choice.',
        },
        {
          kind: 'speak',
          id: 'g1_read_04_s1',
          prompt: 'Sofia had waited all day for that swing. Why did she offer it to Nora anyway?',
          accept: [
            'to be kind', 'she was being nice', 'she wanted to share',
            'the girl was new', 'to make a friend', 'because she is kind',
            'to be nice', 'sharing',
          ],
          sampleAnswer: 'She wanted to be kind to the new girl.',
          hint: 'Think about how the new girl was feeling.',
          teach: 'She gave up something she wanted. That is what makes it kind and not just easy.',
        },
        {
          kind: 'choice',
          id: 'g1_read_04_c2',
          prompt: 'What was the new girl\'s name?',
          options: ['Sofia', 'Mia', 'Nora', 'Ana'],
          correct: 2,
          teach: 'Nora. We learn her name only after Sofia is kind to her.',
        },
        {
          kind: 'choice',
          id: 'g1_read_04_c3',
          prompt: 'What happened at the end?',
          options: [
            'They became friends',
            'They argued',
            'The swing broke',
            'Recess was cancelled',
          ],
          correct: 0,
          teach: 'They became friends by the end of recess.',
        },
        {
          kind: 'speak',
          id: 'g1_read_04_s2',
          prompt: 'Tell me about a time you shared something that was hard to share.',
          accept: ['toy', 'my', 'i shared', 'snack', 'book', 'i gave', 'sister', 'brother'],
          sampleAnswer: 'I shared my snack with my sister even though I wanted it.',
          teach: 'Thank you for telling me. That took honesty.',
        },
      ],
    },
  },
  {
    id: 'g1_read_05',
    subject: 'reading',
    grade: 1,
    title: 'Why the Sky Is Not Empty',
    blurb: 'A little bit of true science, told like a story.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'Why the Sky Is Not Empty',
        preview: [
          { word: 'empty', meaning: 'having nothing inside' },
          { word: 'air', meaning: 'what we breathe, even though we cannot see it' },
        ],
        paragraphs: [
          'Look up. The sky can seem empty. But it is not.',
          'The sky is full of air. You cannot see air, but you can feel it. When the wind blows your hair, that is air moving.',
          'The sky is full of water too. Clouds are made of tiny drops of water. So many drops that we can see them.',
          'And past all of that, far past the clouds, the sky is full of stars. They are up there in the daytime as well. The sun is just so bright that we cannot see them.',
          'The sky is one of the fullest places there is.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_05_c1',
          prompt: 'What are clouds made of?',
          options: ['Cotton', 'Tiny drops of water', 'Smoke', 'Snow only'],
          correct: 1,
          teach: 'Tiny drops of water, so many that we can see them together.',
        },
        {
          kind: 'choice',
          id: 'g1_read_05_c2',
          prompt: 'Why can we not see the stars in the daytime?',
          options: [
            'They go away',
            'They turn off',
            'The sun is too bright',
            'Clouds cover them',
          ],
          correct: 2,
          teach: 'The stars are still there. The sun is just too bright for our eyes.',
        },
        {
          kind: 'speak',
          id: 'g1_read_05_s1',
          prompt: 'The story says you cannot see air, but you can feel it. When can you feel air?',
          accept: [
            'wind', 'when the wind blows', 'when it is windy', 'blowing',
            'when i blow', 'a fan', 'breeze',
          ],
          sampleAnswer: 'When the wind blows my hair.',
          teach: 'Yes. You cannot see it, and it is still real. That is worth remembering.',
        },
        {
          kind: 'choice',
          id: 'g1_read_05_c3',
          prompt: 'What is the big idea of this story?',
          options: [
            'The sky is boring',
            'The sky is full of things',
            'Clouds are the best',
            'You should not look up',
          ],
          correct: 1,
          teach: 'The whole story builds to that last line: the sky is one of the fullest places there is.',
        },
        {
          kind: 'speak',
          id: 'g1_read_05_s2',
          prompt: 'Name one thing the story says is up in the sky.',
          accept: ['air', 'water', 'clouds', 'stars', 'sun', 'wind'],
          sampleAnswer: 'Stars.',
          teach: 'That is right. Air, water, clouds, and stars — all up there at once.',
        },
      ],
    },
  },
  {
    id: 'g1_read_06',
    subject: 'reading',
    grade: 1,
    title: 'The Dog Who Would Not Bark',
    blurb: 'Everyone thought something was wrong. They were looking at it the wrong way.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Dog Who Would Not Bark',
        preview: [{ word: 'shelter', meaning: 'a safe place where lost animals wait for a home' }],
        paragraphs: [
          'At the shelter there was a small brown dog. She did not bark. Not once.',
          'People came and looked at her. "Is she sick?" they asked. Then they walked on to the loud, happy dogs.',
          'Lily sat down by the cage. She did not talk. She just sat.',
          'After a long time, the small brown dog came close. She put her nose through the wire and touched Lily\'s hand.',
          '"She was not sick," Lily told her mom. "She was just waiting for someone quiet."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_06_c1',
          prompt: 'What was strange about the small brown dog?',
          options: ['She was very big', 'She did not bark', 'She could not walk', 'She was blue'],
          correct: 1,
          teach: 'She did not bark. Not once.',
        },
        {
          kind: 'choice',
          id: 'g1_read_06_c2',
          prompt: 'What did Lily do that the other people did not do?',
          options: [
            'She sat quietly and waited',
            'She shouted at the dog',
            'She opened the cage',
            'She gave her food',
          ],
          correct: 0,
          teach: 'She sat down and waited. She let the dog come to her.',
        },
        {
          kind: 'speak',
          id: 'g1_read_06_s1',
          prompt: 'Why do you think the other people walked away?',
          accept: [
            'they thought she was sick', 'she was quiet', 'they wanted a loud dog',
            'they wanted happy dogs', 'they did not wait', 'they thought something was wrong',
          ],
          sampleAnswer: 'They thought something was wrong with her because she was quiet.',
          hint: 'What did they ask before they walked on?',
          teach: 'They decided too fast. Lily waited long enough to find out the truth.',
        },
        {
          kind: 'speak',
          id: 'g1_read_06_s2',
          prompt: 'What did the dog do when she finally came close?',
          accept: [
            'touched her hand', 'put her nose through', 'touched lily',
            'she touched her hand with her nose', 'nose',
          ],
          sampleAnswer: 'She touched Lily\'s hand with her nose.',
          teach: 'A very small thing. And it was the whole story.',
        },
        {
          kind: 'choice',
          id: 'g1_read_06_c3',
          prompt: 'What is the lesson of this story?',
          options: [
            'Loud is better',
            'Some good things take waiting',
            'Dogs are scary',
            'Never go to a shelter',
          ],
          correct: 1,
          teach: 'Some good things only show up if you are patient enough to wait for them.',
        },
      ],
    },
  },
  {
    id: 'g1_read_07',
    subject: 'reading',
    grade: 1,
    title: 'Ruby Builds a Bridge',
    blurb: 'What do you do when the first try falls down?',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Ruby Builds a Bridge',
        preview: [{ word: 'strong', meaning: 'able to hold a lot without breaking' }],
        paragraphs: [
          'Ruby wanted to build a bridge from blocks. She put two tall stacks down and laid one long block on top.',
          'It fell.',
          'She built it again. It fell again.',
          'Ruby stopped and looked hard at the blocks. The tall stacks were wobbly. So she made them shorter and wider.',
          'This time the bridge held. She rolled a toy car right across it. "It fell twice," she said, "and then it did not."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_07_c1',
          prompt: 'How many times did the bridge fall?',
          options: ['One time', 'Two times', 'Three times', 'It never fell'],
          correct: 1,
          teach: 'Twice. And she said so herself at the end.',
        },
        {
          kind: 'speak',
          id: 'g1_read_07_s1',
          prompt: 'What did Ruby change to make the bridge work?',
          accept: [
            'shorter and wider', 'she made them shorter', 'made the stacks wider',
            'shorter', 'wider', 'she made the stacks shorter and wider', 'the stacks',
          ],
          sampleAnswer: 'She made the stacks shorter and wider.',
          hint: 'What was wrong with the tall stacks?',
          teach: 'Shorter and wider. She did not try harder — she tried differently.',
        },
        {
          kind: 'choice',
          id: 'g1_read_07_c2',
          prompt: 'What did Ruby do before she built it the third time?',
          options: [
            'She stopped and looked hard at the blocks',
            'She gave up',
            'She asked for new blocks',
            'She cried',
          ],
          correct: 0,
          teach: 'She stopped and looked. Thinking first is part of the work.',
        },
        {
          kind: 'choice',
          id: 'g1_read_07_c3',
          prompt: 'How do you think Ruby felt at the end?',
          options: ['Proud', 'Angry', 'Bored', 'Sleepy'],
          correct: 0,
          teach: 'Proud. And she earned it, because it was hard.',
        },
        {
          kind: 'speak',
          id: 'g1_read_07_s2',
          prompt: 'Tell me about something you had to try more than once.',
          accept: ['i tried', 'riding', 'bike', 'writing', 'i could not', 'jumping', 'it was hard'],
          sampleAnswer: 'I tried to ride my bike many times before I could do it.',
          teach: 'That is exactly what Ruby did. You are already good at the hardest part.',
        },
      ],
    },
  },
  {
    id: 'g1_read_08',
    subject: 'reading',
    grade: 1,
    title: 'The Sound at Night',
    blurb: 'A story about being brave when you are still a little scared.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Sound at Night',
        preview: [{ word: 'brave', meaning: 'doing a thing even when you feel afraid' }],
        paragraphs: [
          'Ivy heard a sound in the night. Tap. Tap. Tap.',
          'She pulled the blanket up over her head. The sound kept going. Tap. Tap.',
          'Ivy took a big breath. She got out of bed and walked to the window. Her legs felt shaky.',
          'Outside, a branch was tapping on the glass. That was all. Just a branch and the wind.',
          'Ivy went back to bed. She was still a little scared. But she had looked anyway, and that felt good.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_08_c1',
          prompt: 'What was making the sound?',
          options: ['A bird', 'A branch on the window', 'Her sister', 'The rain'],
          correct: 1,
          teach: 'Just a branch tapping in the wind.',
        },
        {
          kind: 'choice',
          id: 'g1_read_08_c2',
          prompt: 'What did Ivy do first when she heard the sound?',
          options: [
            'Pulled the blanket over her head',
            'Ran to her mom',
            'Opened the window',
            'Went back to sleep',
          ],
          correct: 0,
          teach: 'She hid first. That is a very normal thing to do.',
        },
        {
          kind: 'speak',
          id: 'g1_read_08_s1',
          prompt: 'The story says Ivy was still a little scared at the end. So why did it feel good?',
          accept: [
            'she looked anyway', 'she was brave', 'because she checked',
            'she did it anyway', 'she got up', 'she was brave anyway',
            'because she was brave',
          ],
          sampleAnswer: 'Because she looked anyway, even though she was scared.',
          hint: 'What is brave: not being scared, or doing it while you are scared?',
          teach: 'Brave does not mean not scared. Brave means scared and doing it anyway.',
        },
        {
          kind: 'choice',
          id: 'g1_read_08_c3',
          prompt: 'How did Ivy\'s legs feel when she walked to the window?',
          options: ['Strong', 'Shaky', 'Cold', 'Fast'],
          correct: 1,
          teach: 'Shaky. The story tells us that on purpose, so we know it was hard.',
        },
        {
          kind: 'speak',
          id: 'g1_read_08_s2',
          prompt: 'What is something that feels a little scary to you?',
          accept: ['dark', 'the dark', 'noises', 'spiders', 'being alone', 'thunder', 'i am scared'],
          sampleAnswer: 'The dark feels a little scary to me.',
          teach: 'Thank you for saying it out loud. Saying it is its own kind of brave.',
        },
      ],
    },
  },
  {
    id: 'g1_read_09',
    subject: 'reading',
    grade: 1,
    title: 'Two Kinds of Hungry',
    blurb: 'A short story with a surprise at the end.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Two Kinds of Hungry',
        preview: [{ word: 'share', meaning: 'to give part of what you have' }],
        paragraphs: [
          'Hazel had one apple in her bag. She was very hungry.',
          'A boy at the next table had no lunch at all. He was looking at the table, not at anyone.',
          'Hazel looked at her apple. Then she looked at the boy. Then she looked at her apple again.',
          'She cut the apple in half with her hands. It was hard to do. She gave him the bigger half.',
          'She was still a bit hungry after. But something else in her felt full.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_09_c1',
          prompt: 'What did Hazel have in her bag?',
          options: ['A sandwich', 'One apple', 'Two cookies', 'Nothing'],
          correct: 1,
          teach: 'One apple. Only one.',
        },
        {
          kind: 'choice',
          id: 'g1_read_09_c2',
          prompt: 'Which half did Hazel give away?',
          options: ['The bigger half', 'The smaller half', 'Both halves', 'Neither'],
          correct: 0,
          teach: 'The bigger half. She could have given the smaller one, and she did not.',
        },
        {
          kind: 'speak',
          id: 'g1_read_09_s1',
          prompt: 'The last line says something in her felt full. What do you think that means?',
          accept: [
            'her heart', 'she felt happy', 'she felt good', 'she felt good inside',
            'her heart was full', 'happy', 'she was glad', 'she felt nice',
          ],
          sampleAnswer: 'Her heart felt full because she did something kind.',
          hint: 'Her tummy was still hungry. What part of her was not?',
          teach: 'That is the two kinds of hungry in the title. Her stomach and her heart.',
        },
        {
          kind: 'choice',
          id: 'g1_read_09_c3',
          prompt: 'How do we know the boy was uncomfortable?',
          options: [
            'He was crying',
            'He was looking at the table, not at anyone',
            'He asked for food',
            'He left the room',
          ],
          correct: 1,
          teach: 'The story shows us instead of telling us. He would not look up.',
        },
        {
          kind: 'speak',
          id: 'g1_read_09_s2',
          prompt: 'Why was it hard for Hazel to share?',
          accept: [
            'she was hungry', 'she was very hungry', 'she only had one',
            'because she wanted it', 'she wanted to eat it',
          ],
          sampleAnswer: 'Because she was very hungry and only had one apple.',
          teach: 'Right. Sharing when you have plenty is easy. This was the other kind.',
        },
      ],
    },
  },
  {
    id: 'g1_read_10',
    subject: 'reading',
    grade: 1,
    title: 'The Girl Who Asked Why',
    blurb: 'Our last story in this constellation is about the best question there is.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Girl Who Asked Why',
        preview: [
          { word: 'question', meaning: 'something you ask when you want to know' },
          { word: 'answer', meaning: 'what you say back to a question' },
        ],
        paragraphs: [
          'June asked a lot of questions. Why is grass green? Why do we sleep? Why is the ocean salty?',
          'Sometimes people said, "That is just how it is."',
          'June did not like that answer. It did not tell her anything.',
          'One day her teacher said something different. "I do not know," she said. "Let us find out together."',
          'They looked it up. They read about it. And June learned something nobody in her house had known that morning.',
          'That was the day June found out that "I do not know" can be the start of something, not the end.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_10_c1',
          prompt: 'What did June do a lot?',
          options: ['Sleep', 'Ask questions', 'Run', 'Draw'],
          correct: 1,
          teach: 'She asked questions. Lots and lots of them.',
        },
        {
          kind: 'speak',
          id: 'g1_read_10_s1',
          prompt: 'Why did June not like the answer "That is just how it is"?',
          accept: [
            'it did not tell her anything', 'it was not an answer',
            'it did not help', 'it told her nothing', 'because it did not explain',
            'it does not tell her anything',
          ],
          sampleAnswer: 'Because it did not tell her anything.',
          hint: 'The story says it right after.',
          teach: 'It sounds like an answer, but it does not explain anything at all.',
        },
        {
          kind: 'choice',
          id: 'g1_read_10_c2',
          prompt: 'What did the teacher say that was different?',
          options: [
            '"I do not know. Let us find out together."',
            '"Stop asking questions."',
            '"That is just how it is."',
            '"Ask your mother."',
          ],
          correct: 0,
          teach: 'She admitted she did not know, and then she helped June find out.',
        },
        {
          kind: 'choice',
          id: 'g1_read_10_c3',
          prompt: 'What did June learn that day?',
          options: [
            'Not to ask questions',
            'That "I do not know" can be a beginning',
            'That teachers know everything',
            'That grass is blue',
          ],
          correct: 1,
          teach: 'That is the last line, and it is the whole point of the story.',
        },
        {
          kind: 'speak',
          id: 'g1_read_10_s2',
          prompt: 'What is a question you have wondered about?',
          accept: ['why', 'what', 'how', 'where', 'when', 'who', 'i wonder', 'does', 'is'],
          sampleAnswer: 'I wonder why the sky is blue.',
          teach: 'Hold on to that one. We can go find out together, just like June did.',
        },
      ],
    },
  },
  {
    id: 'g1_read_11',
    subject: 'reading',
    grade: 1,
    title: 'The Rainy Day Race',
    blurb: 'Things do not always go the way you planned. That is okay.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Rainy Day Race',
        preview: [{ word: 'puddle', meaning: 'a small pool of water on the ground' }],
        paragraphs: [
          'Kai trained for the race all week. He wanted to be the fastest.',
          'Then it rained. The race was muddy and wet.',
          'Kai slipped and fell. He got back up, covered in mud. Other kids were faster than him.',
          'But he kept going. When he crossed the finish line, everyone cheered.',
          'He did not win the race. But he won something else: he knew he could try hard even when it was hard.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_11_c1',
          prompt: 'What did the weather do on race day?',
          options: ['It snowed', 'It rained', 'It was sunny', 'It was windy'],
          correct: 1,
          teach: 'It rained. That made everything muddy and wet.',
        },
        {
          kind: 'speak',
          id: 'g1_read_11_s1',
          prompt: 'What did Kai win, even though he did not come first?',
          accept: ['he knew he could try', 'knowing he could try hard', 'he was strong', 'he could try', 'perseverance'],
          sampleAnswer: 'He knew he could try hard even when it was hard.',
          teach: 'That is a bigger win than coming first.',
        },
        {
          kind: 'choice',
          id: 'g1_read_11_c2',
          prompt: 'When Kai fell, what did he do?',
          options: ['Stopped trying', 'Cried', 'Got back up', 'Went home'],
          correct: 2,
          teach: 'He got back up and kept going.',
        },
      ],
    },
  },
  {
    id: 'g1_read_12',
    subject: 'reading',
    grade: 1,
    title: 'Max the Plant',
    blurb: 'Sometimes the smallest things need the most care.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'Max the Plant',
        preview: [{ word: 'wilt', meaning: 'to droop and look sad, like a plant without water' }],
        paragraphs: [
          'Asha had a little plant she named Max. She watered him once and then forgot.',
          'One day Max was wilting. His leaves hung down. He looked very sad.',
          'Asha gave him water right away. She also moved him to a sunny window.',
          'In three days, Max was standing up again. His leaves were green and strong.',
          '"I am sorry, Max," Asha said. "I will check on you every day now."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_12_c1',
          prompt: 'What was the plant\'s name?',
          options: ['Tom', 'Max', 'Sam', 'Leo'],
          correct: 1,
          teach: 'Max. That is what Asha named him.',
        },
        {
          kind: 'speak',
          id: 'g1_read_12_s1',
          prompt: 'What are two things Asha did to help Max get better?',
          accept: ['water', 'sunny window', 'gave water', 'moved', 'sun', 'watered'],
          sampleAnswer: 'She watered him and moved him to a sunny window.',
          teach: 'Two simple things. Caring for a living thing means doing these things over and over.',
        },
        {
          kind: 'choice',
          id: 'g1_read_12_c2',
          prompt: 'How long did it take Max to get better?',
          options: ['One day', 'Two days', 'Three days', 'A week'],
          correct: 2,
          teach: 'Three days. It did not happen right away, but it did happen.',
        },
      ],
    },
  },
  {
    id: 'g1_read_13',
    subject: 'reading',
    grade: 1,
    title: 'The Secret Message',
    blurb: 'Sometimes the kindest thing is very small.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Secret Message',
        preview: [{ word: 'message', meaning: 'words you send to someone' }],
        paragraphs: [
          'Leo felt sad at school. He did not have many friends.',
          'He found a note in his desk. It said: "You are kind. —A friend"',
          'Leo looked around. He did not know who wrote it.',
          'But now he felt different. Someone had noticed he was kind. Someone cared.',
          'The next day, Leo wrote a note for someone else. Now he had a secret to keep.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_13_c1',
          prompt: 'How did Leo feel at the start?',
          options: ['Happy', 'Sad', 'Angry', 'Tired'],
          correct: 1,
          teach: 'Sad. He felt alone.',
        },
        {
          kind: 'speak',
          id: 'g1_read_13_s1',
          prompt: 'What did the note say?',
          accept: ['you are kind', 'kind', 'a friend', 'you are kind a friend'],
          sampleAnswer: '"You are kind. —A friend"',
          teach: 'Four words that changed Leo\'s whole day.',
        },
        {
          kind: 'choice',
          id: 'g1_read_13_c2',
          prompt: 'What did Leo do the next day?',
          options: ['Looked for the note writer', 'Wrote a note for someone else', 'Told a teacher', 'Stayed home'],
          correct: 1,
          teach: 'He wrote a note for someone else. He became the friend Leo needed.',
        },
      ],
    },
  },
  {
    id: 'g1_read_14',
    subject: 'reading',
    grade: 1,
    title: 'The Garden Party',
    blurb: 'You can make something beautiful from very little.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Garden Party',
        preview: [{ word: 'guest', meaning: 'someone who comes to visit' }],
        paragraphs: [
          'Emma wanted to have a party for her friends. But her mom said, "We do not have much food."',
          'Emma looked at the garden. She picked flowers and berries. She set them on a table in the sun.',
          'Her friends came. They sat in the grass. They picked berries and talked.',
          '"This is the best party ever," said Jo.',
          '"Because of the cake?" asked Emma. "No," said Jo. "Because you are here."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_14_c1',
          prompt: 'What did Emma use to make the party?',
          options: ['Toys', 'Flowers and berries', 'Books', 'Pictures'],
          correct: 1,
          teach: 'Flowers and berries from the garden.',
        },
        {
          kind: 'speak',
          id: 'g1_read_14_s1',
          prompt: 'Why did Jo think it was the best party?',
          accept: ['because emma was there', 'because of emma', 'because the friends were there', 'the people'],
          sampleAnswer: 'Because Emma was there.',
          teach: 'The best party is the one where you are with people you like.',
        },
        {
          kind: 'choice',
          id: 'g1_read_14_c2',
          prompt: 'What does this story teach us?',
          options: ['Money buys happiness', 'You need cake for a party', 'You can make something nice from simple things', 'Parties are boring'],
          correct: 2,
          teach: 'Emma created something beautiful without money. Just imagination and friends.',
        },
      ],
    },
  },
  {
    id: 'g1_read_15',
    subject: 'reading',
    grade: 1,
    title: 'The Lost Tooth',
    blurb: 'Losing a tooth is scary until you understand what it means.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Lost Tooth',
        preview: [{ word: 'baby tooth', meaning: 'a small tooth that falls out when you are a child' }],
        paragraphs: [
          'Elias had a wiggly tooth. He was scared to touch it.',
          'One morning, he bit an apple and the tooth fell out. He ran to his mom.',
          '"That is good!" she said. "A new tooth is growing underneath."',
          'Elias put the tooth under his pillow. That night, something strange happened.',
          'The tooth was gone. In its place was a coin. Elias smiled with his new big tooth.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_15_c1',
          prompt: 'What made Elias\'s tooth fall out?',
          options: ['He pulled it', 'He bit an apple', 'He knocked it', 'It just fell'],
          correct: 1,
          teach: 'He bit an apple. Sometimes the simplest thing makes it happen.',
        },
        {
          kind: 'speak',
          id: 'g1_read_15_s1',
          prompt: 'Why was Elias scared at first?',
          accept: ['the tooth was wiggly', 'he was afraid', 'he did not know', 'it would hurt'],
          sampleAnswer: 'He did not know what would happen.',
          teach: 'New things are scary until we understand them.',
        },
        {
          kind: 'choice',
          id: 'g1_read_15_c2',
          prompt: 'What does a baby tooth falling out mean?',
          options: ['Something is wrong', 'A new tooth is growing', 'You need to see a doctor', 'Your mouth is broken'],
          correct: 1,
          teach: 'It means you are growing. A new, bigger tooth is on the way.',
        },
      ],
    },
  },
  {
    id: 'g1_read_16',
    subject: 'reading',
    grade: 1,
    title: 'The Tiny Bridge',
    blurb: 'Sometimes courage is just one small step.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Tiny Bridge',
        preview: [{ word: 'creek', meaning: 'a very small river' }],
        paragraphs: [
          'Mina was hiking with her dad. They came to a creek.',
          'There was a bridge made of rocks. It did not look strong.',
          '"I cannot do it," said Mina. "It is too high."',
          'Her dad said, "Look only at the next rock. Not the whole bridge. Just the next step."',
          'Mina looked down. The next rock was very close. She stepped on it. Then the next. Then the next.',
          'She was across. She had crossed the whole bridge by taking it one rock at a time.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_16_c1',
          prompt: 'What made Mina scared?',
          options: ['The water', 'The rocks', 'The height', 'Her dad'],
          correct: 2,
          teach: 'She thought the bridge was too high.',
        },
        {
          kind: 'speak',
          id: 'g1_read_16_s1',
          prompt: 'What did her dad tell her to do?',
          accept: ['look at the next rock', 'one rock at a time', 'one step', 'next rock'],
          sampleAnswer: 'Look at only the next rock, not the whole bridge.',
          teach: 'When something big seems impossible, break it into tiny pieces.',
        },
        {
          kind: 'choice',
          id: 'g1_read_16_c2',
          prompt: 'How did Mina cross the bridge?',
          options: ['Her dad carried her', 'She jumped', 'One rock at a time', 'She swam'],
          correct: 2,
          teach: 'One step at a time. That is how you do big things.',
        },
      ],
    },
  },
  {
    id: 'g1_read_17',
    subject: 'reading',
    grade: 1,
    title: 'The Color That Is Not Allowed',
    blurb: 'Rules are there for a reason, but sometimes they change.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Color That Is Not Allowed',
        preview: [{ word: 'paint', meaning: 'a colored liquid you use to cover something' }],
        paragraphs: [
          'At art class, the rule was: "Everyone paint the sky blue. That is how a sky is."',
          'Maya wanted to paint her sky purple. She was scared.',
          '"Is that allowed?" she asked.',
          'The teacher looked at her painting. "Purple clouds at sunset," she said. "I have seen that. You are looking carefully."',
          'Maya painted her sky purple. The next day, three other children painted purple skies too. By the end of the week, the rule had changed.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_17_c1',
          prompt: 'What was the old rule about painting?',
          options: ['Always use blue paint', 'Paint the sky blue', 'Never use purple', 'Only paint in black'],
          correct: 1,
          teach: 'Everyone paint the sky blue. That was the rule.',
        },
        {
          kind: 'speak',
          id: 'g1_read_17_s1',
          prompt: 'Why was Maya scared?',
          accept: ['she wanted to break the rule', 'she wanted to do it differently', 'purple sky', 'she was not sure'],
          sampleAnswer: 'Because she wanted to break the rule.',
          teach: 'Sometimes the best ideas need a little courage first.',
        },
        {
          kind: 'choice',
          id: 'g1_read_17_c2',
          prompt: 'What did the teacher say about Maya\'s purple sky?',
          options: ['"That is wrong."', '"You are looking carefully."', '"Do not do that again."', '"That is ugly."'],
          correct: 1,
          teach: 'The teacher said Maya was looking carefully. Maya was not breaking the rule. She was seeing the real world.',
        },
      ],
    },
  },
  {
    id: 'g1_read_18',
    subject: 'reading',
    grade: 1,
    title: 'The Mistake Was Good',
    blurb: 'Sometimes the things we get wrong teach us the best lessons.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Mistake Was Good',
        preview: [{ word: 'mistake', meaning: 'something you do wrong by accident' }],
        paragraphs: [
          'Zoe was mixing paint. She wanted yellow.',
          'She mixed too much blue in. She got green instead.',
          'She was about to throw it away. Then she stopped.',
          '"Wait," she said. "Green is beautiful too."',
          'She used the green to paint trees around her yellow sun. Her painting was better than she planned.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_18_c1',
          prompt: 'What color was Zoe trying to make?',
          options: ['Green', 'Blue', 'Yellow', 'Red'],
          correct: 2,
          teach: 'Yellow. But things did not go as planned.',
        },
        {
          kind: 'speak',
          id: 'g1_read_18_s1',
          prompt: 'What did Zoe do with the green color?',
          accept: ['painted trees', 'used it', 'made trees', 'put it in her painting'],
          sampleAnswer: 'She used it to paint trees around her sun.',
          teach: 'She turned a mistake into something better.',
        },
        {
          kind: 'choice',
          id: 'g1_read_18_c2',
          prompt: 'What is the big idea of this story?',
          options: ['Mistakes are always bad', 'Mistakes can lead to something good', 'Green is the best color', 'Never paint'],
          correct: 1,
          teach: 'Mistakes are not always failures. Sometimes they are just starting points.',
        },
      ],
    },
  },
  {
    id: 'g1_read_19',
    subject: 'reading',
    grade: 1,
    title: 'The Shy Friend',
    blurb: 'Quiet people have wonderful things to say if you wait.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Shy Friend',
        preview: [{ word: 'shy', meaning: 'quiet and a little nervous around other people' }],
        paragraphs: [
          'Ava was loud. She talked all the time.',
          'Her new friend Lily was quiet. She barely said anything.',
          'One day, Ava asked Lily, "Why do you not talk?"',
          'Lily said very quietly, "I like to listen. People are interesting."',
          'Ava became quiet too. She started listening. She discovered that she liked it.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_19_c1',
          prompt: 'What was Lily like?',
          options: ['Very loud', 'Quiet', 'Angry', 'Silly'],
          correct: 1,
          teach: 'Quiet. She did not say much.',
        },
        {
          kind: 'speak',
          id: 'g1_read_19_s1',
          prompt: 'What did Lily say about why she was quiet?',
          accept: ['she likes to listen', 'people are interesting', 'listening'],
          sampleAnswer: 'She likes to listen, and people are interesting.',
          teach: 'Listening is its own kind of talking. It says: I care about what you think.',
        },
        {
          kind: 'choice',
          id: 'g1_read_19_c2',
          prompt: 'What did Ava learn?',
          options: ['She should never talk', 'Listening is good', 'Shy people are boring', 'Quiet is mean'],
          correct: 1,
          teach: 'Ava learned to listen too, and she liked it.',
        },
      ],
    },
  },
  {
    id: 'g1_read_20',
    subject: 'reading',
    grade: 1,
    title: 'The Wall of Kind Words',
    blurb: 'A good day can start with something someone else wrote.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Wall of Kind Words',
        preview: [{ word: 'wall', meaning: 'a side of a building or room' }],
        paragraphs: [
          'At school, there was a wall where people could write kind words.',
          'Maya had a bad day. She was sad.',
          'She looked at the wall. It said: "Maya is a good friend." "Maya makes me laugh." "Maya is kind to everyone."',
          'She had not known people thought these things. But now she did.',
          'That night, Maya wrote on the wall too. "Ava is brave. Zoe is smart. Leo is funny."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_20_c1',
          prompt: 'How was Maya feeling at the start?',
          options: ['Happy', 'Sad', 'Angry', 'Excited'],
          correct: 1,
          teach: 'Sad. She had a bad day.',
        },
        {
          kind: 'speak',
          id: 'g1_read_20_s1',
          prompt: 'What did the words on the wall make Maya realize?',
          accept: ['people cared', 'people liked her', 'she was liked', 'people thought good things'],
          sampleAnswer: 'That people cared about her and thought good things.',
          teach: 'Sometimes we do not know how much people like us until we hear it.',
        },
        {
          kind: 'choice',
          id: 'g1_read_20_c2',
          prompt: 'What did Maya do that night?',
          options: ['Went to sleep', 'Wrote kind words for others', 'Read all day', 'Stayed sad'],
          correct: 1,
          teach: 'She wrote kind words for her friends too. Kindness makes a circle.',
        },
      ],
    },
  },
  {
    id: 'g1_read_21',
    subject: 'reading',
    grade: 1,
    title: 'The Book Under the Bed',
    blurb: 'Some stories are so good you want to read them over and over.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Book Under the Bed',
        preview: [{ word: 'adventure', meaning: 'an exciting journey or event' }],
        paragraphs: [
          'Noah found an old book under his bed. He read it in one night.',
          'It was about a girl and a dragon. They had an adventure.',
          'The next night, he read it again. And the next night.',
          'His mom said, "Why do you read the same book every night?"',
          '"Because," said Noah, "I want to be that girl. And one more time is not too much."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_21_c1',
          prompt: 'What book did Noah find?',
          options: ['A new book', 'A book about dragons', 'An old book about a girl and a dragon', 'A boring book'],
          correct: 2,
          teach: 'An old book about a girl and a dragon.',
        },
        {
          kind: 'speak',
          id: 'g1_read_21_s1',
          prompt: 'Why did Noah read the same book every night?',
          accept: ['he liked it', 'he wanted to be the girl', 'adventure', 'it was good'],
          sampleAnswer: 'Because he wanted to be that girl, and one more time is not too much.',
          teach: 'Good stories do not get old. They get better each time you read them.',
        },
        {
          kind: 'choice',
          id: 'g1_read_21_c2',
          prompt: 'What happened in the book?',
          options: ['A girl and a dragon had an adventure', 'A boy got lost', 'A dragon was mean', 'Nothing happened'],
          correct: 0,
          teach: 'A girl and a dragon went on an adventure together.',
        },
      ],
    },
  },
  {
    id: 'g1_read_22',
    subject: 'reading',
    grade: 1,
    title: 'The Broken Toy',
    blurb: 'Sometimes the best part of a toy is not the toy itself.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Broken Toy',
        preview: [{ word: 'broken', meaning: 'not working anymore because it was damaged' }],
        paragraphs: [
          'Ethan\'s favorite toy broke. One wheel fell off. It would not roll anymore.',
          'He was sad. He put it in a box.',
          'His sister Mia said, "Can I have it?"',
          'Mia turned it into something else. She made a little house for her dolls.',
          'Now Ethan liked the broken toy even better. It was not broken. It was just a different kind of working.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_22_c1',
          prompt: 'What broke on Ethan\'s toy?',
          options: ['The wheel', 'The handle', 'The door', 'The whole thing'],
          correct: 0,
          teach: 'One wheel fell off and it would not roll anymore.',
        },
        {
          kind: 'speak',
          id: 'g1_read_22_s1',
          prompt: 'What did Mia make with the broken toy?',
          accept: ['a house', 'a house for dolls', 'a doll house', 'a dollhouse'],
          sampleAnswer: 'A little house for her dolls.',
          teach: 'She saw a new possibility when everyone else saw something broken.',
        },
        {
          kind: 'choice',
          id: 'g1_read_22_c2',
          prompt: 'Why did Ethan like the toy better after it was broken?',
          options: [
            'He forgot about it',
            'It worked better',
            'It was not broken—it was a different kind of working',
            'Mia fixed it',
          ],
          correct: 2,
          teach: 'It had a new life with a new purpose. Being broken was not the end.',
        },
      ],
    },
  },
  {
    id: 'g1_read_23',
    subject: 'reading',
    grade: 1,
    title: 'The First Snow',
    blurb: 'Waiting for something you want makes it twice as sweet.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The First Snow',
        preview: [{ word: 'snowflake', meaning: 'a small piece of ice that falls from clouds' }],
        paragraphs: [
          'It was December. Sofia wanted snow.',
          'She looked out the window. Every morning, she checked. Still no snow.',
          'One night, she fell asleep looking at the dark sky.',
          'In the morning, everything was white. The first snow had come.',
          'She did not play with it right away. She just stood and looked. She had waited so long.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_23_c1',
          prompt: 'What was Sofia waiting for?',
          options: ['Rain', 'Sun', 'Snow', 'Wind'],
          correct: 2,
          teach: 'Snow. She waited and waited.',
        },
        {
          kind: 'speak',
          id: 'g1_read_23_s1',
          prompt: 'What did Sofia do first when she saw the snow?',
          accept: ['looked at it', 'stood and looked', 'watched', 'she just stood'],
          sampleAnswer: 'She just stood and looked.',
          teach: 'Sometimes the best thing is just to look at something beautiful.',
        },
        {
          kind: 'choice',
          id: 'g1_read_23_c2',
          prompt: 'Why did Sofia not play right away?',
          options: ['She was tired', 'It was too cold', 'She had waited so long', 'She did not want to'],
          correct: 2,
          teach: 'She had waited so long that just looking was enough for the moment.',
        },
      ],
    },
  },
  {
    id: 'g1_read_24',
    subject: 'reading',
    grade: 1,
    title: 'The Code',
    blurb: 'Real friends understand you without many words.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Code',
        preview: [{ word: 'code', meaning: 'a secret system for sending messages' }],
        paragraphs: [
          'Liam and his friend Cole created a secret code. One tap meant yes. Two taps meant no.',
          'Three taps meant "I need help."',
          'One day at school, Cole felt scared about something. He tapped Liam\'s shoulder three times.',
          'Liam did not ask questions. He sat next to Cole all day.',
          'Later, Cole said, "Thank you. I did not know how to tell you."',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_24_c1',
          prompt: 'What did three taps mean?',
          options: ['No', 'Yes', '"I need help."', 'Hello'],
          correct: 2,
          teach: 'Three taps meant "I need help."',
        },
        {
          kind: 'speak',
          id: 'g1_read_24_s1',
          prompt: 'What did Liam do when Cole sent the code?',
          accept: ['sat with him', 'helped', 'stayed with him', 'sat next to cole'],
          sampleAnswer: 'He sat next to Cole all day.',
          teach: 'Liam understood without Cole having to explain. That is what a real friend does.',
        },
        {
          kind: 'choice',
          id: 'g1_read_24_c2',
          prompt: 'What did the code help them do?',
          options: ['Play a game', 'Talk without words', 'Keep a secret', 'Get in trouble'],
          correct: 1,
          teach: 'It let them send messages without speaking. That helped Cole ask for help.',
        },
      ],
    },
  },
  {
    id: 'g1_read_25',
    subject: 'reading',
    grade: 1,
    title: 'The Gift of Time',
    blurb: 'The best gift is your attention.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Gift of Time',
        preview: [{ word: 'attention', meaning: 'the focus and care you give to someone' }],
        paragraphs: [
          'On her birthday, Nia asked for a toy. Her dad said, "I have a different idea."',
          'He gave her a promise: one whole day with no phone, no distractions. Just them.',
          'Nia and her dad made a fort. They read books inside. They told jokes.',
          'At the end of the day, Nia said, "This is my favorite gift ever."',
          'Her dad smiled. He had given her something he could not buy.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_25_c1',
          prompt: 'What did Nia ask for?',
          options: ['A toy', 'A day with her dad', 'A phone', 'A book'],
          correct: 0,
          teach: 'A toy. But her dad had a different idea.',
        },
        {
          kind: 'speak',
          id: 'g1_read_25_s1',
          prompt: 'What was Nia\'s dad\'s gift?',
          accept: ['a day with him', 'time', 'his attention', 'no phone'],
          sampleAnswer: 'One whole day with no phone and no distractions.',
          teach: 'Time and attention. Those are gifts you cannot buy.',
        },
        {
          kind: 'choice',
          id: 'g1_read_25_c2',
          prompt: 'Why was it her favorite gift?',
          options: ['It was expensive', 'It showed she mattered', 'It was small', 'It was broken'],
          correct: 1,
          teach: 'Because her dad gave her his full attention. That showed her how much she mattered.',
        },
      ],
    },
  },
  {
    id: 'g1_read_26',
    subject: 'reading',
    grade: 1,
    title: 'The Lighthouse',
    blurb: 'Sometimes being small does not mean being unimportant.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Lighthouse',
        preview: [{ word: 'lighthouse', meaning: 'a tall tower with a bright light that helps ships find their way' }],
        paragraphs: [
          'Kai felt small. He was the smallest in his class.',
          '"How can I help?" he asked his dad.',
          '"Look at the lighthouse," his dad said. "It is not the biggest building at the beach. But its light helps every ship find its way home."',
          'Kai looked at the lighthouse. It shone so bright.',
          '"I want to be a light too," said Kai. And from that day on, he tried to be kind to people who felt alone.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_26_c1',
          prompt: 'Why did Kai feel small?',
          options: ['He was sick', 'He was the smallest in his class', 'He was unhappy', 'He was quiet'],
          correct: 1,
          teach: 'He was the smallest in his class.',
        },
        {
          kind: 'speak',
          id: 'g1_read_26_s1',
          prompt: 'What did the lighthouse do?',
          accept: ['shone light', 'helped ships', 'lit the way', 'showed the way'],
          sampleAnswer: 'It shone a bright light to help ships find their way home.',
          teach: 'It was not the biggest building, but it was the most important light.',
        },
        {
          kind: 'choice',
          id: 'g1_read_26_c2',
          prompt: 'What did Kai learn?',
          options: [
            'Being small is bad',
            'Size is all that matters',
            'Being small does not mean being unimportant',
            'Lighthouses are cool',
          ],
          correct: 2,
          teach: 'The lighthouse taught him that being small does not mean being useless.',
        },
      ],
    },
  },
  {
    id: 'g1_read_27',
    subject: 'reading',
    grade: 1,
    title: 'The Pattern in the Carpet',
    blurb: 'Beauty is waiting for someone to notice it.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Pattern in the Carpet',
        preview: [{ word: 'pattern', meaning: 'a repeated design made of shapes or colors' }],
        paragraphs: [
          'Amara lived in an apartment. The floor had an old carpet.',
          'Everyone walked on it. No one saw it.',
          'One day Amara lay on her back on the carpet. She looked up at it.',
          'It had the most beautiful colors and patterns. They had been there all along.',
          'She started drawing what she saw. Soon her whole notebook was filled with the beauty that was under everyone\'s feet.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_27_c1',
          prompt: 'What did everyone do on the carpet?',
          options: ['Looked at it', 'Walked on it', 'Cleaned it', 'Danced on it'],
          correct: 1,
          teach: 'They walked on it. They did not stop to look at it.',
        },
        {
          kind: 'speak',
          id: 'g1_read_27_s1',
          prompt: 'What did Amara do to see the beauty?',
          accept: ['looked at it', 'lay on her back', 'looked up', 'looked closely'],
          sampleAnswer: 'She lay on her back and looked up at it.',
          teach: 'She changed how she was looking. Sometimes that is all it takes.',
        },
        {
          kind: 'choice',
          id: 'g1_read_27_c2',
          prompt: 'What did Amara do with what she found?',
          options: ['Threw it away', 'Drew it', 'Hid it', 'Told everyone to look'],
          correct: 1,
          teach: 'She drew the patterns in her notebook.',
        },
      ],
    },
  },
  {
    id: 'g1_read_28',
    subject: 'reading',
    grade: 1,
    title: 'The Singing Stones',
    blurb: 'Music can come from the most unexpected places.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Singing Stones',
        preview: [{ word: 'singing', meaning: 'making musical sounds with your voice' }],
        paragraphs: [
          'Kenji found some smooth stones by the river. He tapped them together.',
          'Each stone made a different sound. High. Low. Medium.',
          'He tapped them in a pattern. It was like music.',
          'His friends laughed at first. Then they listened. Soon they were tapping their own stones.',
          'By the river, a river orchestra had been born from nothing but stones and someone who listened.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_28_c1',
          prompt: 'Where did Kenji find the stones?',
          options: ['In a mountain', 'In a store', 'By the river', 'In his house'],
          correct: 2,
          teach: 'By the river. He found smooth stones there.',
        },
        {
          kind: 'speak',
          id: 'g1_read_28_s1',
          prompt: 'What made the stones sing?',
          accept: ['tapping', 'he tapped them', 'hitting them together', 'kenji'],
          sampleAnswer: 'Kenji tapped them together.',
          teach: 'He discovered that stones could make music when you listened carefully.',
        },
        {
          kind: 'choice',
          id: 'g1_read_28_c2',
          prompt: 'What happened at the end?',
          options: ['Everyone went home', 'A river orchestra was born', 'The stones broke', 'Nothing changed'],
          correct: 1,
          teach: 'A river orchestra was born. Music came from friendship and listening.',
        },
      ],
    },
  },
  {
    id: 'g1_read_29',
    subject: 'reading',
    grade: 1,
    title: 'The Wish',
    blurb: 'Sometimes what you want is waiting in plain sight.',
    minutes: 12,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Wish',
        preview: [{ word: 'wish', meaning: 'something you want very much to happen' }],
        paragraphs: [
          'Yuki wished she had a best friend. She felt alone at school.',
          'She found a penny. She tossed it in a fountain and made a wish.',
          '"I wish for a best friend," she whispered.',
          'Nothing happened right away. But the next day, a new girl sat next to her.',
          'Yuki did not know: the new girl was lonely too. They both needed someone. They had both been waiting.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_29_c1',
          prompt: 'What did Yuki wish for?',
          options: ['A toy', 'Money', 'A best friend', 'A dog'],
          correct: 2,
          teach: 'A best friend. She was feeling alone.',
        },
        {
          kind: 'speak',
          id: 'g1_read_29_s1',
          prompt: 'Did the wish come true in a magical way?',
          accept: ['no', 'no, a girl sat with her', 'a new girl came', 'she met a friend'],
          sampleAnswer: 'No. A new girl sat next to her, and they became friends.',
          teach: 'The magic was that they both needed each other at the same time.',
        },
        {
          kind: 'choice',
          id: 'g1_read_29_c2',
          prompt: 'Why was the new girl lonely too?',
          options: ['She was new', 'She had no friends', 'The story does not say', 'She was sad'],
          correct: 2,
          teach: 'The story does not tell us. But Yuki found out the new girl was lonely too.',
        },
      ],
    },
  },
  {
    id: 'g1_read_30',
    subject: 'reading',
    grade: 1,
    title: 'The Home We Build',
    blurb: 'Our final story in this constellation is about what home really means.',
    minutes: 13,
    content: {
      kind: 'passage',
      passage: {
        title: 'The Home We Build',
        preview: [{ word: 'home', meaning: 'a place where you feel safe and loved' }],
        paragraphs: [
          'Home was not always a house. For Kai, home was his mom\'s car at first.',
          'Then they rented an apartment. Kai put his drawings on the walls.',
          'One day, they had a real house with a garden. Kai planted seeds.',
          'The seeds grew into flowers. His mom said, "Look at what we built."',
          'Kai knew she was not talking about just the house. She was talking about a place where a boy and his mom were happy. That was home.',
        ],
      },
      challenges: [
        {
          kind: 'choice',
          id: 'g1_read_30_c1',
          prompt: 'Where was Kai\'s first home?',
          options: ['A house', 'A car', 'An apartment', 'A garden'],
          correct: 1,
          teach: 'In his mom\'s car at first.',
        },
        {
          kind: 'speak',
          id: 'g1_read_30_s1',
          prompt: 'What did his mom mean when she said "Look at what we built"?',
          accept: ['a home', 'a happy place', 'where we are happy', 'love', 'love and happiness'],
          sampleAnswer: 'Not just the house, but a place where they were happy together.',
          teach: 'Home is not just walls and a roof. It is where people love each other.',
        },
        {
          kind: 'choice',
          id: 'g1_read_30_c2',
          prompt: 'What is the big idea of the whole constellation?',
          options: [
            'Houses are important',
            'Stories are boring',
            'People and their feelings are the most important thing',
            'Reading is hard',
          ],
          correct: 2,
          teach: 'Through all these stories, we learned that people and their feelings are what really matter.',
        },
      ],
    },
  },
];
