import type { Star } from '../../types';

/**
 * Grade 1 critical thinking — 10 stars.
 *
 * The point is reasoning, not recall, so most challenges ask "why" as a follow
 * up to "which". Riddles are kept fair: every one can be worked out from what
 * is stated, with no trick knowledge required.
 */

export const grade1Thinking: Star[] = [
  {
    id: 'g1_think_01',
    subject: 'thinking',
    grade: 1,
    title: 'What Comes Next',
    blurb: 'Patterns are everywhere once you start looking.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_01_a',
          prompt: 'Circle, square, circle, square, circle... what comes next?',
          display: '⭕ ⬛ ⭕ ⬛ ⭕ ❓',
          options: ['Square', 'Circle', 'Triangle', 'Star'],
          correct: 0,
          teach: 'Square. The pattern goes back and forth between two shapes.',
        },
        {
          kind: 'choice',
          id: 'g1_think_01_b',
          prompt: 'Red, red, blue, red, red, blue, red... what comes next?',
          display: '🔴 🔴 🔵 🔴 🔴 🔵 🔴 ❓',
          options: ['Blue', 'Red', 'Green', 'Nothing'],
          correct: 1,
          teach: 'Red. The group is red-red-blue, so we are only one red in.',
          hint: 'Say it out loud in groups of three.',
        },
        {
          kind: 'choice',
          id: 'g1_think_01_c',
          prompt: 'Big, small, big, small, big... what comes next?',
          options: ['Small', 'Big', 'Medium', 'Huge'],
          correct: 0,
          teach: 'Small. Two things taking turns again.',
        },
        {
          kind: 'order',
          id: 'g1_think_01_d',
          prompt: 'Put these in order from smallest to biggest.',
          items: ['Ant', 'Cat', 'Horse', 'Elephant'],
          teach: 'Ant, cat, horse, elephant. You sorted by size in your head.',
        },
        {
          kind: 'speak',
          id: 'g1_think_01_e',
          prompt: 'Clap, clap, stomp, clap, clap, stomp. What comes after the stomp?',
          accept: ['clap', 'a clap', 'clapping', 'clap clap'],
          sampleAnswer: 'Clap.',
          teach: 'Clap. Patterns work with sounds just as well as with shapes.',
        },
        {
          kind: 'choice',
          id: 'g1_think_01_f',
          prompt: 'Which one breaks the pattern? Square, square, square, circle, square.',
          options: ['The first square', 'The circle', 'The last square', 'Nothing breaks it'],
          correct: 1,
          teach: 'The circle. Finding what does not fit is its own useful skill.',
        },
      ],
    },
  },
  {
    id: 'g1_think_02',
    subject: 'thinking',
    grade: 1,
    title: 'Which One Does Not Belong',
    blurb: 'Sometimes there is more than one good answer. I want to hear your reason.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_02_a',
          prompt: 'Which one does not belong? Apple, banana, carrot, orange.',
          options: ['Apple', 'Banana', 'Carrot', 'Orange'],
          correct: 2,
          teach: 'Carrot. The others are fruit, and a carrot is a vegetable.',
        },
        {
          kind: 'choice',
          id: 'g1_think_02_b',
          prompt: 'Which one does not belong? Dog, cat, rabbit, chair.',
          options: ['Dog', 'Cat', 'Rabbit', 'Chair'],
          correct: 3,
          teach: 'Chair. The others are alive.',
        },
        {
          kind: 'choice',
          id: 'g1_think_02_c',
          prompt: 'Which one does not belong? Shoe, sock, boot, hat.',
          options: ['Shoe', 'Sock', 'Boot', 'Hat'],
          correct: 3,
          teach: 'Hat. The other three go on your feet.',
        },
        {
          kind: 'speak',
          id: 'g1_think_02_d',
          prompt: 'Sun, moon, star, rock. Which does not belong, and why?',
          accept: ['rock', 'the rock', 'rock because', 'a rock'],
          sampleAnswer: 'The rock, because the others are in the sky.',
          hint: 'Where do you find each one?',
          teach: 'The rock. The others are all up in the sky.',
        },
        {
          kind: 'choice',
          id: 'g1_think_02_e',
          prompt: 'Which one does not belong? Two, four, six, seven.',
          options: ['Two', 'Four', 'Six', 'Seven'],
          correct: 3,
          teach: 'Seven. The others are all even numbers you say when counting by twos.',
        },
        {
          kind: 'speak',
          id: 'g1_think_02_f',
          prompt: 'Here is a hard one. Circle, ball, wheel, box. Which does not belong?',
          accept: ['box', 'the box', 'box because'],
          sampleAnswer: 'The box, because the others are round.',
          teach: 'The box. Everything else is round.',
        },
      ],
    },
  },
  {
    id: 'g1_think_03',
    subject: 'thinking',
    grade: 1,
    title: 'Because and So',
    blurb: 'Every thing that happens has a reason behind it.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_03_a',
          prompt: 'The grass is wet. What most likely happened?',
          options: ['It rained', 'The sun was hot', 'It was very windy', 'Someone shouted'],
          correct: 0,
          teach: 'Rain is the most likely reason. Good thinking.',
        },
        {
          kind: 'choice',
          id: 'g1_think_03_b',
          prompt: 'Ana is holding an umbrella and wearing boots. What is the weather?',
          options: ['Hot and sunny', 'Rainy', 'Very snowy', 'Windy but dry'],
          correct: 1,
          teach: 'Rainy. You read the clues instead of being told.',
        },
        {
          kind: 'choice',
          id: 'g1_think_03_c',
          prompt: 'The plant turned brown and dry. What probably happened?',
          options: [
            'It got too much water',
            'Nobody watered it',
            'It was moved to a bigger pot',
            'Someone sang to it',
          ],
          correct: 1,
          teach: 'It needed water. Dry and brown is what thirsty looks like on a plant.',
        },
        {
          kind: 'speak',
          id: 'g1_think_03_d',
          prompt: 'You hear the smoke alarm beeping in the kitchen. What might be happening?',
          accept: ['something is burning', 'burning', 'smoke', 'fire', 'the food is burning', 'toast'],
          sampleAnswer: 'Something might be burning.',
          teach: 'Yes. And that is a sound you should always tell a grown-up about.',
        },
        {
          kind: 'choice',
          id: 'g1_think_03_e',
          prompt: 'Mia is yawning and rubbing her eyes. What does she probably need?',
          options: ['A snack', 'Sleep', 'A coat', 'A book'],
          correct: 1,
          teach: 'Sleep. Bodies give us clues about what they need.',
        },
        {
          kind: 'speak',
          id: 'g1_think_03_f',
          prompt: 'The ice cream is a puddle on the sidewalk. Tell me why.',
          accept: ['it melted', 'melted', 'it was hot', 'the sun', 'it got warm', 'because it was hot'],
          sampleAnswer: 'It melted because it was hot outside.',
          teach: 'It melted. Heat turns solid ice cream into liquid.',
        },
      ],
    },
  },
  {
    id: 'g1_think_04',
    subject: 'thinking',
    grade: 1,
    title: 'Put the Story in Order',
    blurb: 'Things happen in an order. Let us get them right.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g1_think_04_a',
          prompt: 'Put these in the right order for planting a seed.',
          items: ['Dig a small hole', 'Drop in the seed', 'Cover it with soil', 'Give it water'],
          teach: 'Dig, drop, cover, water. Order matters — you cannot water a seed you have not planted.',
        },
        {
          kind: 'order',
          id: 'g1_think_04_b',
          prompt: 'Put these in order for making a sandwich.',
          items: ['Get two slices of bread', 'Spread on the filling', 'Put the slices together', 'Take a bite'],
          teach: 'Exactly right.',
        },
        {
          kind: 'order',
          id: 'g1_think_04_c',
          prompt: 'Put these in order from first to last in a day.',
          items: ['Wake up', 'Eat breakfast', 'Go to school', 'Go to bed'],
          teach: 'That is a whole day, start to finish.',
        },
        {
          kind: 'order',
          id: 'g1_think_04_d',
          prompt: 'Put the butterfly\'s life in order.',
          items: ['An egg on a leaf', 'A hungry caterpillar', 'A hard chrysalis', 'A butterfly flies away'],
          teach: 'Egg, caterpillar, chrysalis, butterfly. That is called a life cycle.',
          hint: 'Which one is the very smallest to begin with?',
        },
        {
          kind: 'order',
          id: 'g1_think_04_e',
          prompt: 'Put these in order, smallest amount of time to longest.',
          items: ['A second', 'A minute', 'An hour', 'A day'],
          teach: 'Second, minute, hour, day. Each one holds many of the one before it.',
        },
      ],
    },
  },
  {
    id: 'g1_think_05',
    subject: 'thinking',
    grade: 1,
    title: 'Riddles in the Dark',
    blurb: 'Every clue you need is right there in the words.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_05_a',
          prompt: 'I am full of holes, but I can still hold water. What am I?',
          accept: ['sponge', 'a sponge'],
          sampleAnswer: 'A sponge.',
          hint: 'You might find me by the kitchen sink.',
          teach: 'A sponge. The holes are exactly what let it hold the water.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_b',
          prompt: 'I go up when the rain comes down. What am I?',
          accept: ['umbrella', 'an umbrella'],
          sampleAnswer: 'An umbrella.',
          teach: 'An umbrella. Up it goes.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_c',
          prompt: 'I have hands but I cannot clap. What am I?',
          accept: ['clock', 'a clock', 'watch', 'a watch'],
          sampleAnswer: 'A clock.',
          hint: 'I tell you when it is time for dinner.',
          teach: 'A clock. Its hands point instead of clapping.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_d',
          prompt: 'I follow you everywhere in the sunshine, but you cannot catch me. What am I?',
          accept: ['shadow', 'my shadow', 'your shadow', 'a shadow'],
          sampleAnswer: 'A shadow.',
          teach: 'Your shadow. It goes where you go and never lets you grab it.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_e',
          prompt: 'The more you take away from me, the bigger I get. What am I?',
          accept: ['hole', 'a hole'],
          sampleAnswer: 'A hole.',
          hint: 'Think about digging.',
          teach: 'A hole. That one bends your brain a little, does it not?',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_f',
          prompt: 'I am light as a feather, but nobody can hold me for long. What am I?',
          accept: ['breath', 'your breath', 'air', 'my breath'],
          sampleAnswer: 'Your breath.',
          teach: 'Your breath. Try holding it and you will see.',
        },
      ],
    },
  },
  {
    id: 'g1_think_06',
    subject: 'thinking',
    grade: 1,
    title: 'Same and Different',
    blurb: 'Two things can be alike in one way and different in another.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_06_a',
          prompt: 'How are a cat and a dog the same?',
          accept: ['animals', 'they are animals', 'pets', 'they are pets', 'four legs', 'they have fur', 'fur'],
          sampleAnswer: 'They are both animals with four legs.',
          teach: 'Both animals, both pets, both have fur and four legs. Lots of ways.',
        },
        {
          kind: 'speak',
          id: 'g1_think_06_b',
          prompt: 'Now tell me one way a cat and a dog are different.',
          accept: ['barks', 'dogs bark', 'meow', 'cats meow', 'size', 'climb', 'sound'],
          sampleAnswer: 'Dogs bark and cats meow.',
          teach: 'Good. Same in some ways, different in others. Most things are.',
        },
        {
          kind: 'choice',
          id: 'g1_think_06_c',
          prompt: 'How are a bicycle and a car the same?',
          options: [
            'They both have wheels',
            'They both have engines',
            'They both need gas',
            'They are both very small',
          ],
          correct: 0,
          teach: 'Wheels. That is the thing they share.',
        },
        {
          kind: 'choice',
          id: 'g1_think_06_d',
          prompt: 'How are the sun and a lamp the same?',
          options: [
            'They both give light',
            'They are both very far away',
            'They both run on batteries',
            'They are both cold',
          ],
          correct: 0,
          teach: 'They both give light. One is a bit bigger than the other.',
        },
        {
          kind: 'match',
          id: 'g1_think_06_e',
          prompt: 'Match each baby animal to its grown-up.',
          pairs: [
            { left: 'Puppy', right: 'Dog' },
            { left: 'Kitten', right: 'Cat' },
            { left: 'Chick', right: 'Hen' },
            { left: 'Calf', right: 'Cow' },
          ],
          teach: 'Every one of those grows up into the other.',
        },
      ],
    },
  },
  {
    id: 'g1_think_07',
    subject: 'thinking',
    grade: 1,
    title: 'What Would You Do',
    blurb: 'These have no single right answer. I want to hear how you think.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_07_a',
          prompt: 'You see a friend sitting alone at lunch looking sad. What could you do?',
          accept: ['sit with her', 'ask her', 'talk to her', 'i would sit', 'ask what is wrong', 'go over', 'sit'],
          sampleAnswer: 'I would go sit with her and ask if she is okay.',
          teach: 'That is a kind plan. Just going over is usually enough.',
        },
        {
          kind: 'speak',
          id: 'g1_think_07_b',
          prompt: 'You broke something by accident and nobody saw. What should you do?',
          accept: ['tell', 'tell the truth', 'say sorry', 'tell my mom', 'be honest', 'i would tell'],
          sampleAnswer: 'Tell a grown-up the truth.',
          teach: 'Telling the truth is harder when nobody saw. That is exactly when it counts.',
        },
        {
          kind: 'choice',
          id: 'g1_think_07_c',
          prompt: 'You are lost in a big store. What is the safest thing to do?',
          options: [
            'Run around looking for your grown-up',
            'Go outside to the parking lot',
            'Stay put and ask a worker for help',
            'Hide until they find you',
          ],
          correct: 2,
          teach: 'Stay where you are and ask a worker. Moving around makes you harder to find.',
        },
        {
          kind: 'speak',
          id: 'g1_think_07_d',
          prompt: 'Your sister is using the toy you wanted. What could you do that is not fighting?',
          accept: ['ask', 'ask for a turn', 'wait', 'take turns', 'play with something else', 'share', 'ask nicely'],
          sampleAnswer: 'Ask if I can have a turn when she is done.',
          teach: 'Asking and waiting. Both harder than grabbing, and both work better.',
        },
        {
          kind: 'choice',
          id: 'g1_think_07_e',
          prompt: 'Someone you do not know asks you to go with them. What do you do?',
          options: [
            'Go if they seem nice',
            'Say no and find a grown-up you know',
            'Ask them where they are going',
            'Follow them a little way',
          ],
          correct: 1,
          teach: 'Say no and find a grown-up you trust. Always. No matter how nice they seem.',
        },
      ],
    },
  },
  {
    id: 'g1_think_08',
    subject: 'thinking',
    grade: 1,
    title: 'Sorting Things Out',
    blurb: 'Putting things into groups is a kind of thinking.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'match',
          id: 'g1_think_08_a',
          prompt: 'Match each thing to where it belongs.',
          pairs: [
            { left: 'Fish', right: 'Water' },
            { left: 'Bird', right: 'Sky' },
            { left: 'Worm', right: 'Soil' },
            { left: 'Squirrel', right: 'Tree' },
          ],
          teach: 'Every creature has a home that fits it.',
        },
        {
          kind: 'match',
          id: 'g1_think_08_b',
          prompt: 'Match each tool to the job it does.',
          pairs: [
            { left: 'Scissors', right: 'Cutting' },
            { left: 'Spoon', right: 'Eating soup' },
            { left: 'Broom', right: 'Sweeping' },
            { left: 'Pencil', right: 'Writing' },
          ],
          teach: 'Tools are made on purpose for one job.',
        },
        {
          kind: 'choice',
          id: 'g1_think_08_c',
          prompt: 'Which group do a hammer, a saw, and a screwdriver belong to?',
          options: ['Foods', 'Tools', 'Animals', 'Clothes'],
          correct: 1,
          teach: 'Tools. You found the group they share.',
        },
        {
          kind: 'choice',
          id: 'g1_think_08_d',
          prompt: 'Which of these is NOT something you wear?',
          options: ['Scarf', 'Mitten', 'Kettle', 'Sock'],
          correct: 2,
          teach: 'A kettle. That one boils water instead.',
        },
        {
          kind: 'speak',
          id: 'g1_think_08_e',
          prompt: 'Name three things you would find in a kitchen.',
          accept: ['spoon', 'fork', 'plate', 'cup', 'pot', 'pan', 'stove', 'sink', 'fridge', 'bowl', 'knife'],
          sampleAnswer: 'A spoon, a plate, and a cup.',
          teach: 'Nicely sorted. You pictured the room and read it in your mind.',
        },
      ],
    },
  },
  {
    id: 'g1_think_09',
    subject: 'thinking',
    grade: 1,
    title: 'Number Puzzles',
    blurb: 'Thinking puzzles that happen to use numbers.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_09_a',
          prompt: 'There are 3 birds on a branch. Two more land. Then one flies away. How many now?',
          accept: ['4', 'four'],
          sampleAnswer: '4',
          hint: 'Do it one step at a time. Three, then five, then...',
          teach: 'Four. Three plus two is five, minus one is four.',
        },
        {
          kind: 'speak',
          id: 'g1_think_09_b',
          prompt: 'You have 2 hands. Each hand has 5 fingers. How many fingers altogether?',
          accept: ['10', 'ten'],
          sampleAnswer: '10',
          teach: 'Ten. Two groups of five.',
        },
        {
          kind: 'choice',
          id: 'g1_think_09_c',
          prompt: 'Zoe is taller than Mia. Mia is taller than Ana. Who is the tallest?',
          options: ['Zoe', 'Mia', 'Ana', 'They are the same'],
          correct: 0,
          teach: 'Zoe. You lined all three up in your head without ever seeing them.',
          hint: 'Line them up one at a time, tallest first.',
        },
        {
          kind: 'choice',
          id: 'g1_think_09_d',
          prompt: 'A basket holds 4 apples. You take 4 out. How many are left?',
          options: ['4', '1', '0', '8'],
          correct: 2,
          teach: 'Zero. An empty basket.',
        },
        {
          kind: 'speak',
          id: 'g1_think_09_e',
          prompt: 'If today is Tuesday, what day is tomorrow?',
          accept: ['wednesday'],
          sampleAnswer: 'Wednesday',
          teach: 'Wednesday. Days come in an order, just like numbers.',
        },
        {
          kind: 'speak',
          id: 'g1_think_09_f',
          prompt: 'A cat has 4 legs. How many legs do 2 cats have?',
          accept: ['8', 'eight'],
          sampleAnswer: '8',
          teach: 'Eight. Two groups of four.',
        },
      ],
    },
  },
  {
    id: 'g1_think_10',
    subject: 'thinking',
    grade: 1,
    title: 'Is That Always True',
    blurb: 'Some things are true sometimes, and some are true always. There is a difference.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_10_a',
          prompt: 'True or not always true? "All birds can fly."',
          options: ['Always true', 'Not always true'],
          correct: 1,
          teach: 'Not always. Penguins and ostriches are birds, and they cannot fly.',
        },
        {
          kind: 'choice',
          id: 'g1_think_10_b',
          prompt: 'True or not always true? "All squares have four sides."',
          options: ['Always true', 'Not always true'],
          correct: 0,
          teach: 'Always true. Four sides is part of what makes it a square.',
        },
        {
          kind: 'choice',
          id: 'g1_think_10_c',
          prompt: 'True or not always true? "If it is cloudy, it will rain."',
          options: ['Always true', 'Not always true'],
          correct: 1,
          teach: 'Not always. Plenty of cloudy days stay dry.',
        },
        {
          kind: 'choice',
          id: 'g1_think_10_d',
          prompt: 'True or not always true? "Every person needs water to live."',
          options: ['Always true', 'Not always true'],
          correct: 0,
          teach: 'Always true. That one has no exceptions.',
        },
        {
          kind: 'speak',
          id: 'g1_think_10_e',
          prompt: 'Someone says "all dogs are big." Can you think of a dog that proves it wrong?',
          accept: ['puppy', 'a puppy', 'small dog', 'chihuahua', 'little dog', 'baby dog', 'a small one'],
          sampleAnswer: 'A puppy is a small dog.',
          teach: 'One example is enough to show that an "all" statement is wrong. That is real logic.',
        },
        {
          kind: 'speak',
          id: 'g1_think_10_f',
          prompt: 'Is this always true? "The sun comes up in the morning."',
          accept: ['yes', 'true', 'always', 'always true', 'yes it is'],
          sampleAnswer: 'Yes, that is always true.',
          teach: 'That one holds up. Every single morning, so far.',
        },
      ],
    },
  },
  {
    id: 'g1_think_11',
    subject: 'thinking',
    grade: 1,
    title: 'What Happens Next',
    blurb: 'Think ahead. What will happen after?',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_11_a',
          prompt: 'You drop a glass of milk. What happens next?',
          options: ['It spills', 'It flies up', 'It turns to juice', 'Nothing'],
          correct: 0,
          teach: 'It spills. Thinking ahead helps you be careful.',
        },
        {
          kind: 'choice',
          id: 'g1_think_11_b',
          prompt: 'You leave ice cream in the sun. What happens?',
          options: ['It gets colder', 'It melts', 'It grows', 'It turns blue'],
          correct: 1,
          teach: 'It melts. Warm things melt cold things.',
        },
        {
          kind: 'speak',
          id: 'g1_think_11_c',
          prompt: 'You water a seed every day. What happens after many days?',
          accept: ['it grows', 'a plant', 'it sprouts', 'grows', 'a flower comes'],
          sampleAnswer: 'It grows into a plant.',
          teach: 'Right. Care plus time makes things grow.',
        },
        {
          kind: 'choice',
          id: 'g1_think_11_d',
          prompt: 'You do not water a plant for many weeks. What happens?',
          options: ['It grows bigger', 'It wilts', 'It moves', 'It sings'],
          correct: 1,
          teach: 'It wilts. Living things need care to stay alive.',
        },
        {
          kind: 'speak',
          id: 'g1_think_11_e',
          prompt: 'You are kind to a new kid at school. What might happen next?',
          accept: ['friend', 'they are happy', 'we become friends', 'they smile', 'they feel good'],
          sampleAnswer: 'We might become friends.',
          teach: 'Kindness usually comes back to you.',
        },
      ],
    },
  },
  {
    id: 'g1_think_12',
    subject: 'thinking',
    grade: 1,
    title: 'Sorting Things Out',
    blurb: 'Put things into groups that make sense.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_12_a',
          prompt: 'Apple, banana, grape. What group do these belong to?',
          options: ['Animals', 'Fruits', 'Toys', 'Clothes'],
          correct: 1,
          teach: 'Fruits. They all grow and we eat them.',
        },
        {
          kind: 'choice',
          id: 'g1_think_12_b',
          prompt: 'Shirt, pants, hat. What group is this?',
          options: ['Food', 'Animals', 'Clothes', 'Cars'],
          correct: 2,
          teach: 'Clothes. Things we wear.',
        },
        {
          kind: 'order',
          id: 'g1_think_12_c',
          prompt: 'Put these in order from youngest to oldest.',
          items: ['Baby', 'Kid', 'Teenager', 'Grandma'],
          teach: 'Baby, kid, teenager, grandma. You sorted by age.',
        },
        {
          kind: 'choice',
          id: 'g1_think_12_d',
          prompt: 'Which one belongs with "things that fly"? ',
          options: ['Fish', 'Butterfly', 'Worm', 'Rock'],
          correct: 1,
          teach: 'Butterfly. It has wings and uses them.',
        },
        {
          kind: 'speak',
          id: 'g1_think_12_e',
          prompt: 'Name something that belongs in the group "things in the kitchen."',
          accept: ['spoon', 'fork', 'plate', 'cup', 'pot', 'pan', 'fridge', 'stove', 'oven', 'food'],
          sampleAnswer: 'A spoon.',
          teach: 'Yes, that lives in the kitchen. Grouping helps us find things.',
        },
      ],
    },
  },
  {
    id: 'g1_think_13',
    subject: 'thinking',
    grade: 1,
    title: 'Big Problems, Small Steps',
    blurb: 'Every big problem is made of small pieces.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_13_a',
          prompt: 'Your room is very messy. What is the best first step?',
          options: ['Clean everything at once', 'Pick up one thing', 'Close the door', 'Wait for help'],
          correct: 1,
          teach: 'Pick up one thing. Then another. Small steps finish big jobs.',
        },
        {
          kind: 'order',
          id: 'g1_think_13_b',
          prompt: 'Put the steps for making a sandwich in order.',
          items: ['Get the bread', 'Add the filling', 'Put the top on', 'Eat it'],
          teach: 'Bread, filling, top, eat. Steps have an order that matters.',
        },
        {
          kind: 'choice',
          id: 'g1_think_13_c',
          prompt: 'You want to learn to jump rope. What should you do first?',
          options: ['Give up', 'Try jumping without the rope', 'Buy ten ropes', 'Watch TV'],
          correct: 1,
          teach: 'Practice the jump first, then add the rope. Break it into parts.',
        },
        {
          kind: 'speak',
          id: 'g1_think_13_d',
          prompt: 'You have to carry ten books but can only hold three. What do you do?',
          accept: ['make trips', 'carry three at a time', 'more trips', 'go back', 'ask for help', 'a few at a time'],
          sampleAnswer: 'Carry three at a time and make more trips.',
          teach: 'More trips with small loads. That is solving it with steps.',
        },
        {
          kind: 'choice',
          id: 'g1_think_13_e',
          prompt: 'A puzzle has 100 pieces. How do you start?',
          options: ['Do the corners and edges first', 'Throw the pieces', 'Do it all at once', 'Hide some pieces'],
          correct: 0,
          teach: 'Corners and edges first. Start with what you can see clearly.',
        },
      ],
    },
  },
  {
    id: 'g1_think_14',
    subject: 'thinking',
    grade: 1,
    title: 'True or Not True',
    blurb: 'Some things are always true. Some are not.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_14_a',
          prompt: 'Is this true? "All birds can fly."',
          options: ['True', 'Not true — penguins cannot fly', 'True on Mondays', 'Birds do not exist'],
          correct: 1,
          teach: 'Penguins and ostriches are birds that cannot fly. One example can test a rule.',
        },
        {
          kind: 'choice',
          id: 'g1_think_14_b',
          prompt: 'Is this true? "The sun is bigger than the moon."',
          options: ['True', 'Not true', 'They are the same', 'No one knows'],
          correct: 0,
          teach: 'True. The sun is much bigger — it just looks small because it is far away.',
        },
        {
          kind: 'choice',
          id: 'g1_think_14_c',
          prompt: 'Is this true? "Everyone likes the same food."',
          options: ['True', 'Not true — people like different things', 'True for pizza', 'Food is not real'],
          correct: 1,
          teach: 'People like different things. That is what makes sharing meals interesting.',
        },
        {
          kind: 'speak',
          id: 'g1_think_14_d',
          prompt: 'Say one thing that is always true about water.',
          accept: ['wet', 'it is wet', 'we drink it', 'you can drink it', 'it flows', 'we need it'],
          sampleAnswer: 'Water is wet.',
          teach: 'Yes. Finding what is always true is how rules are made.',
        },
        {
          kind: 'choice',
          id: 'g1_think_14_e',
          prompt: 'Someone says "cats always land on their feet." How could you check?',
          options: ['Just believe it', 'Watch what cats really do', 'Ask a dog', 'Never check'],
          correct: 1,
          teach: 'Watch and see. Checking is better than just believing.',
        },
      ],
    },
  },
  {
    id: 'g1_think_15',
    subject: 'thinking',
    grade: 1,
    title: 'The Why Chain',
    blurb: 'Every why has an answer, and every answer has another why.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_15_a',
          prompt: 'Why do we wear coats in winter?',
          options: ['To look nice', 'To stay warm', 'Because everyone does', 'To hide'],
          correct: 1,
          teach: 'To stay warm. Our clothes solve a problem.',
        },
        {
          kind: 'choice',
          id: 'g1_think_15_b',
          prompt: 'Why do plants grow toward the window?',
          options: ['They like the view', 'They want light', 'They are scared', 'They do not'],
          correct: 1,
          teach: 'They grow toward light because they need it to live.',
        },
        {
          kind: 'speak',
          id: 'g1_think_15_c',
          prompt: 'Why do we sleep at night?',
          accept: ['rest', 'to rest', 'tired', 'our body needs rest', 'to grow', 'energy'],
          sampleAnswer: 'Our bodies need rest to grow and have energy.',
          teach: 'Sleep is how our bodies and brains fix themselves up for tomorrow.',
        },
        {
          kind: 'choice',
          id: 'g1_think_15_d',
          prompt: 'Why do we say thank you?',
          options: ['It is a rule with no reason', 'To show we noticed a kindness', 'To end talking', 'To get more things'],
          correct: 1,
          teach: 'It tells someone their kindness was seen. That matters.',
        },
        {
          kind: 'speak',
          id: 'g1_think_15_e',
          prompt: 'Ask me a why question about anything.',
          accept: ['why'],
          sampleAnswer: 'Why is the sky blue?',
          teach: 'A wonderful why. Keep asking those forever.',
        },
      ],
    },
  },
  {
    id: 'g1_think_16',
    subject: 'thinking',
    grade: 1,
    title: 'Same and Different',
    blurb: 'Two things can be alike and not alike at the same time.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_16_a',
          prompt: 'How are a cat and a dog the same?',
          options: ['Both are pets with fur', 'Both can fly', 'Both live in water', 'Both are plants'],
          correct: 0,
          teach: 'Both are furry pets. Finding sameness is a thinking skill.',
        },
        {
          kind: 'choice',
          id: 'g1_think_16_b',
          prompt: 'How are a cat and a dog different?',
          options: ['One is alive', 'Cats meow and dogs bark', 'One has legs', 'They are not different'],
          correct: 1,
          teach: 'Different sounds, different play. Same group, different members.',
        },
        {
          kind: 'choice',
          id: 'g1_think_16_c',
          prompt: 'How are a bike and a car the same?',
          options: ['Both have wheels and take you places', 'Both have engines', 'Both fly', 'Both are animals'],
          correct: 0,
          teach: 'Wheels and travel. They solve the same problem differently.',
        },
        {
          kind: 'speak',
          id: 'g1_think_16_d',
          prompt: 'Tell me one way the sun and a lamp are the same.',
          accept: ['light', 'both give light', 'they shine', 'bright', 'both are bright'],
          sampleAnswer: 'They both give light.',
          teach: 'Both make light. One is just a lot bigger and further away.',
        },
        {
          kind: 'speak',
          id: 'g1_think_16_e',
          prompt: 'Tell me one way the sun and a lamp are different.',
          accept: ['sun is bigger', 'lamp turns off', 'sun is hot', 'one is in the sky', 'we made lamps', 'sun is far'],
          sampleAnswer: 'You can turn a lamp off, but not the sun.',
          teach: 'Same job, very different things. Comparing helps us understand both.',
        },
      ],
    },
  },
  {
    id: 'g1_think_17',
    subject: 'thinking',
    grade: 1,
    title: 'The Riddle Road',
    blurb: 'Riddles hide their answers in plain sight.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_17_a',
          prompt: 'I have hands but cannot clap. What am I?',
          options: ['A glove', 'A clock', 'A tree', 'A shoe'],
          correct: 1,
          teach: 'A clock has hands that point, not clap.',
        },
        {
          kind: 'choice',
          id: 'g1_think_17_b',
          prompt: 'I get wetter the more I dry. What am I?',
          options: ['A towel', 'The sun', 'A cup', 'A book'],
          correct: 0,
          teach: 'A towel gets wet as it dries you.',
        },
        {
          kind: 'choice',
          id: 'g1_think_17_c',
          prompt: 'I have teeth but never eat. What am I?',
          options: ['A shark', 'A comb', 'A baby', 'A spoon'],
          correct: 1,
          teach: 'A comb. Its teeth are for hair, not food.',
        },
        {
          kind: 'choice',
          id: 'g1_think_17_d',
          prompt: 'I go up but never come down. What am I?',
          options: ['A ball', 'Rain', 'Your age', 'A bird'],
          correct: 2,
          teach: 'Your age only ever goes up. Happy growing!',
        },
        {
          kind: 'speak',
          id: 'g1_think_17_e',
          prompt: 'I am full of holes but I hold water. What am I? (Hint: you wash with me)',
          accept: ['sponge', 'a sponge'],
          sampleAnswer: 'A sponge.',
          teach: 'A sponge! Full of holes, and still holds water.',
        },
      ],
    },
  },
  {
    id: 'g1_think_18',
    subject: 'thinking',
    grade: 1,
    title: 'What Would You Do',
    blurb: 'There is often more than one good answer.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_18_a',
          prompt: 'You find a wallet on the ground. What is the best thing to do?',
          options: ['Keep it', 'Give it to a grown-up you trust', 'Hide it', 'Leave it and tell no one'],
          correct: 1,
          teach: 'A trusted grown-up can help find who lost it.',
        },
        {
          kind: 'choice',
          id: 'g1_think_18_b',
          prompt: 'Your friend is crying. What could you do first?',
          options: ['Walk away', 'Ask if they are okay', 'Laugh', 'Tell everyone'],
          correct: 1,
          teach: 'Asking shows you care. Sometimes that is all they need.',
        },
        {
          kind: 'speak',
          id: 'g1_think_18_c',
          prompt: 'You broke your mom\'s cup by accident. What do you do?',
          accept: ['tell her', 'say sorry', 'tell the truth', 'be honest', 'tell my mom'],
          sampleAnswer: 'Tell her the truth and say sorry.',
          teach: 'Honesty first. Accidents are forgivable; hiding them is harder to fix.',
        },
        {
          kind: 'choice',
          id: 'g1_think_18_d',
          prompt: 'Two friends both want to play different games with you. What is fair?',
          options: ['Play only with one', 'Play one game then the other', 'Play alone', 'Get angry'],
          correct: 1,
          teach: 'Taking turns lets everyone have a good time.',
        },
        {
          kind: 'speak',
          id: 'g1_think_18_e',
          prompt: 'You see someone being left out of a game. What could you do?',
          accept: ['invite them', 'ask them to play', 'include them', 'let them play', 'be kind'],
          sampleAnswer: 'Invite them to play too.',
          teach: 'Including someone costs nothing and can change their whole day.',
        },
      ],
    },
  },
  {
    id: 'g1_think_19',
    subject: 'thinking',
    grade: 1,
    title: 'Guess and Check',
    blurb: 'Good guesses come from good clues.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_19_a',
          prompt: 'It has four legs, says woof, and wags its tail. What is it?',
          options: ['A cat', 'A dog', 'A table', 'A bird'],
          correct: 1,
          teach: 'A dog. The clues pointed right at it.',
        },
        {
          kind: 'choice',
          id: 'g1_think_19_b',
          prompt: 'It is yellow, curved, and monkeys love it. What is it?',
          options: ['A lemon', 'The moon', 'A banana', 'Cheese'],
          correct: 2,
          teach: 'A banana. All three clues had to fit.',
        },
        {
          kind: 'choice',
          id: 'g1_think_19_c',
          prompt: 'It is cold, white, and falls in winter. What is it?',
          options: ['Rain', 'Snow', 'Leaves', 'Sunshine'],
          correct: 1,
          teach: 'Snow. Cold, white, winter — the clues locked it in.',
        },
        {
          kind: 'speak',
          id: 'g1_think_19_d',
          prompt: 'It is round, bounces, and you play with it. What is it?',
          accept: ['ball', 'a ball'],
          sampleAnswer: 'A ball.',
          teach: 'A ball. You used all the clues together.',
        },
        {
          kind: 'speak',
          id: 'g1_think_19_e',
          prompt: 'Now you give ME clues about an animal. Do not say its name!',
          accept: ['it has', 'it is', 'it can', 'it says', 'it lives'],
          sampleAnswer: 'It is big and gray and has a long trunk.',
          teach: 'Great clues! Making clues is even harder than guessing.',
        },
      ],
    },
  },
  {
    id: 'g1_think_20',
    subject: 'thinking',
    grade: 1,
    title: 'Before and After',
    blurb: 'Time has an order. Let us think about it.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g1_think_20_a',
          prompt: 'Put a day in order.',
          items: ['Wake up', 'Eat breakfast', 'Go to school', 'Go to bed'],
          teach: 'That is how most days flow. Order helps us plan.',
        },
        {
          kind: 'choice',
          id: 'g1_think_20_b',
          prompt: 'What comes before you eat a banana?',
          options: ['You peel it', 'You plant it', 'You cook it', 'Nothing'],
          correct: 0,
          teach: 'Peel first, then eat. Some steps cannot be skipped.',
        },
        {
          kind: 'order',
          id: 'g1_think_20_c',
          prompt: 'Put a butterfly\'s life in order.',
          items: ['Egg', 'Caterpillar', 'Chrysalis', 'Butterfly'],
          teach: 'Egg, caterpillar, chrysalis, butterfly. Nature follows its own order.',
        },
        {
          kind: 'choice',
          id: 'g1_think_20_d',
          prompt: 'What happens right after you plant a seed?',
          options: ['A flower blooms instantly', 'You water it and wait', 'It becomes a tree', 'You dig it up'],
          correct: 1,
          teach: 'Water and wait. Some steps take patience.',
        },
        {
          kind: 'speak',
          id: 'g1_think_20_e',
          prompt: 'What do you do before you cross a street?',
          accept: ['look', 'look both ways', 'stop', 'stop and look', 'hold a hand', 'check for cars'],
          sampleAnswer: 'Stop and look both ways.',
          teach: 'Stop, look, listen. That order keeps you safe.',
        },
      ],
    },
  },
  {
    id: 'g1_think_21',
    subject: 'thinking',
    grade: 1,
    title: 'The Counting Detectives',
    blurb: 'Use numbers to solve little mysteries.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_21_a',
          prompt: 'There were 5 cookies. Now there are 2. How many were eaten?',
          options: ['2', '3', '5', '7'],
          correct: 1,
          teach: 'Three cookies are missing. Numbers tell stories.',
        },
        {
          kind: 'choice',
          id: 'g1_think_21_b',
          prompt: 'Ana is taller than Ben. Ben is taller than Cam. Who is shortest?',
          options: ['Ana', 'Ben', 'Cam', 'They are the same'],
          correct: 2,
          teach: 'Cam. You lined them up in your head.',
        },
        {
          kind: 'choice',
          id: 'g1_think_21_c',
          prompt: 'You have 2 red socks and 2 blue socks in a dark drawer. You grab 3 socks. Do you have a matching pair?',
          options: ['Always yes', 'Never', 'Only sometimes', 'Impossible to know'],
          correct: 0,
          teach: 'Always! With only two colors, three socks must include a pair.',
        },
        {
          kind: 'speak',
          id: 'g1_think_21_d',
          prompt: 'There are 4 chairs and 6 kids. What is the problem?',
          accept: ['not enough chairs', 'too many kids', 'two kids have no chair', 'need more chairs'],
          sampleAnswer: 'There are not enough chairs for everyone.',
          teach: 'Two kids would have no seat. Comparing numbers finds problems.',
        },
        {
          kind: 'choice',
          id: 'g1_think_21_e',
          prompt: 'A ladybug has 6 legs. Two ladybugs have how many legs?',
          options: ['6', '8', '12', '10'],
          correct: 2,
          teach: 'Twelve. Six and six more.',
        },
      ],
    },
  },
  {
    id: 'g1_think_22',
    subject: 'thinking',
    grade: 1,
    title: 'Looking Closely',
    blurb: 'The best thinkers are the best noticers.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_22_a',
          prompt: 'Which tells you it rained last night?',
          options: ['Dry ground', 'Puddles everywhere', 'A sunny sky', 'Warm air'],
          correct: 1,
          teach: 'Puddles are clues. The rain left evidence.',
        },
        {
          kind: 'choice',
          id: 'g1_think_22_b',
          prompt: 'You see paw prints in the snow. What do you know?',
          options: ['An animal walked here', 'It is summer', 'The snow is fake', 'Nothing at all'],
          correct: 0,
          teach: 'An animal passed by. Prints are stories written on the ground.',
        },
        {
          kind: 'choice',
          id: 'g1_think_22_c',
          prompt: 'The plant by the window is green. The one in the dark closet is yellow. Why?',
          options: ['Plants need light', 'The closet is cold', 'Someone painted it', 'Plants change color for fun'],
          correct: 0,
          teach: 'Light keeps plants green and strong. You compared and found the difference.',
        },
        {
          kind: 'speak',
          id: 'g1_think_22_d',
          prompt: 'Your friend is wearing a coat, hat, and mittens. What season is it probably?',
          accept: ['winter', 'cold', 'it is cold', 'snowy'],
          sampleAnswer: 'Winter, because those are warm clothes.',
          teach: 'Clothes are clues about weather.',
        },
        {
          kind: 'speak',
          id: 'g1_think_22_e',
          prompt: 'Look around you right now. Tell me one thing you never noticed before.',
          accept: ['i see', 'there is', 'a', 'the', 'i never', 'i notice'],
          sampleAnswer: 'I never noticed the little pattern on the ceiling.',
          teach: 'Noticing is a superpower. It was there all along, waiting for you.',
        },
      ],
    },
  },
  {
    id: 'g1_think_23',
    subject: 'thinking',
    grade: 1,
    title: 'The Opposite Game',
    blurb: 'Every thing has a flip side.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_23_a',
          prompt: 'What is the opposite of hot?',
          options: ['Warm', 'Cold', 'Wet', 'Soft'],
          correct: 1,
          teach: 'Cold. Opposites sit at the two ends.',
        },
        {
          kind: 'choice',
          id: 'g1_think_23_b',
          prompt: 'What is the opposite of empty?',
          options: ['Big', 'Full', 'Open', 'Round'],
          correct: 1,
          teach: 'Full. Think of a cup both ways.',
        },
        {
          kind: 'speak',
          id: 'g1_think_23_c',
          prompt: 'What is the opposite of loud?',
          accept: ['quiet', 'soft', 'silent'],
          sampleAnswer: 'Quiet.',
          teach: 'Quiet. You flipped it perfectly.',
        },
        {
          kind: 'choice',
          id: 'g1_think_23_d',
          prompt: 'Which pair are NOT opposites?',
          options: ['Up and down', 'Fast and slow', 'Big and huge', 'Day and night'],
          correct: 2,
          teach: 'Big and huge are almost the same! The others are true opposites.',
        },
        {
          kind: 'speak',
          id: 'g1_think_23_e',
          prompt: 'Tell me an opposite pair all by yourself.',
          accept: ['and', 'open', 'close', 'in', 'out', 'happy', 'sad', 'wet', 'dry', 'light', 'dark', 'tall', 'short'],
          sampleAnswer: 'Open and closed.',
          teach: 'A perfect pair. Opposites help us describe the whole world.',
        },
      ],
    },
  },
  {
    id: 'g1_think_24',
    subject: 'thinking',
    grade: 1,
    title: 'What Is It For',
    blurb: 'Everything is made for something.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_24_a',
          prompt: 'What is an umbrella for?',
          options: ['Keeping dry in rain', 'Eating soup', 'Flying', 'Reading'],
          correct: 0,
          teach: 'It keeps rain off you. Made for exactly that job.',
        },
        {
          kind: 'choice',
          id: 'g1_think_24_b',
          prompt: 'What is a refrigerator for?',
          options: ['Warming food', 'Keeping food cold and fresh', 'Washing dishes', 'Making music'],
          correct: 1,
          teach: 'Cold keeps food fresh longer. A cold box solves a real problem.',
        },
        {
          kind: 'speak',
          id: 'g1_think_24_c',
          prompt: 'What is a key for?',
          accept: ['open', 'opening', 'lock', 'unlock', 'doors', 'to open doors'],
          sampleAnswer: 'Opening locks and doors.',
          teach: 'Keys open locks. Small tool, big power.',
        },
        {
          kind: 'choice',
          id: 'g1_think_24_d',
          prompt: 'Could you use a shoe to hammer a nail?',
          options: ['Never', 'Maybe, but a hammer works much better', 'Shoes are for nails', 'Yes, shoes are hammers'],
          correct: 1,
          teach: 'You could try! But tools work best at the job they were made for.',
        },
        {
          kind: 'speak',
          id: 'g1_think_24_e',
          prompt: 'Invent a machine! What would you build, and what would it do?',
          accept: ['a machine', 'it would', 'my machine', 'robot', 'i would build'],
          sampleAnswer: 'A robot that finds lost socks.',
          teach: 'Inventors start exactly like that — with a problem and an idea.',
        },
      ],
    },
  },
  {
    id: 'g1_think_25',
    subject: 'thinking',
    grade: 1,
    title: 'How Do You Know',
    blurb: 'It is okay to ask: how do we know that is true?',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_25_a',
          prompt: 'How do you know if it is cold outside without going out?',
          options: ['Guess', 'Look at how people outside are dressed', 'It is always cold', 'You cannot know'],
          correct: 1,
          teach: 'Coats and hats on people outside are evidence of cold.',
        },
        {
          kind: 'choice',
          id: 'g1_think_25_b',
          prompt: 'How do you know a plant needs water?',
          options: ['It tells you', 'Its leaves droop and soil is dry', 'Plants never need water', 'You just wait'],
          correct: 1,
          teach: 'Drooping leaves and dry soil are the plant\'s way of showing its need.',
        },
        {
          kind: 'speak',
          id: 'g1_think_25_c',
          prompt: 'How do you know when cookies are done baking?',
          accept: ['smell', 'they smell', 'golden', 'brown', 'timer', 'look at them', 'the timer rings'],
          sampleAnswer: 'They turn golden and smell wonderful.',
          teach: 'Color, smell, timer — three kinds of evidence, all telling the same story.',
        },
        {
          kind: 'choice',
          id: 'g1_think_25_d',
          prompt: 'Your friend says there is a dragon in the park. What is a good question?',
          options: ['"What color is its fire?"', '"Did you really see it, or is it a story?"', 'No questions', '"Can I ride it?"'],
          correct: 1,
          teach: 'Asking "how do you know?" kindly is what good thinkers do.',
        },
        {
          kind: 'choice',
          id: 'g1_think_25_e',
          prompt: 'What is the best way to know if a story in your head is right?',
          options: ['Believe it always', 'Check it against what you can see', 'Never think stories', 'Ask a cat'],
          correct: 1,
          teach: 'Check your ideas against the real world. That is what scientists do.',
        },
      ],
    },
  },
  {
    id: 'g1_think_26',
    subject: 'thinking',
    grade: 1,
    title: 'The Pattern Hunters',
    blurb: 'Patterns hide in numbers, shapes, and days.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_26_a',
          prompt: '2, 4, 6, 8... what comes next?',
          options: ['9', '10', '12', '7'],
          correct: 1,
          teach: 'Ten. Counting by twos is a number pattern.',
        },
        {
          kind: 'choice',
          id: 'g1_think_26_b',
          prompt: 'Monday, Tuesday, Wednesday... what comes next?',
          options: ['Friday', 'Sunday', 'Thursday', 'Monday again'],
          correct: 2,
          teach: 'Thursday. The week is a pattern that repeats forever.',
        },
        {
          kind: 'choice',
          id: 'g1_think_26_c',
          prompt: '1, 2, 3, 1, 2, 3, 1... what comes next?',
          options: ['1', '2', '3', '4'],
          correct: 1,
          teach: 'Two. The group of three starts over each time.',
        },
        {
          kind: 'speak',
          id: 'g1_think_26_d',
          prompt: 'Spring, summer, fall, winter, spring, summer... what comes next?',
          accept: ['fall', 'autumn'],
          sampleAnswer: 'Fall.',
          teach: 'Fall. The seasons circle around and around.',
        },
        {
          kind: 'choice',
          id: 'g1_think_26_e',
          prompt: '10, 9, 8, 7... what kind of pattern is this?',
          options: ['Going up', 'Counting down', 'Random', 'Doubling'],
          correct: 1,
          teach: 'Counting down. Patterns can go in any direction.',
        },
      ],
    },
  },
  {
    id: 'g1_think_27',
    subject: 'thinking',
    grade: 1,
    title: 'Cause and Effect',
    blurb: 'One thing makes another thing happen.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_27_a',
          prompt: 'The ground is wet. What probably caused it?',
          options: ['Rain', 'The moon', 'A loud noise', 'Cold air'],
          correct: 0,
          teach: 'Rain is the most likely cause. Wet ground is the effect.',
        },
        {
          kind: 'choice',
          id: 'g1_think_27_b',
          prompt: 'You flip the light switch. What is the effect?',
          options: ['The door opens', 'The light turns on', 'Music plays', 'Nothing ever'],
          correct: 1,
          teach: 'Switch causes light. Cause first, effect after.',
        },
        {
          kind: 'speak',
          id: 'g1_think_27_c',
          prompt: 'You practice piano every day. What is the effect after a year?',
          accept: ['better', 'you get better', 'good at piano', 'you can play', 'improve'],
          sampleAnswer: 'You get much better at playing.',
          teach: 'Practice causes skill. Slow causes are still causes.',
        },
        {
          kind: 'choice',
          id: 'g1_think_27_d',
          prompt: 'The dog is barking at the door. What might be the cause?',
          options: ['Someone is there', 'The dog is asleep', 'It is raining inside', 'Dogs bark for no reason ever'],
          correct: 0,
          teach: 'Probably someone or something outside. Barking is a clue pointing to a cause.',
        },
        {
          kind: 'speak',
          id: 'g1_think_27_e',
          prompt: 'You share your toys with a friend. What effect might that have?',
          accept: ['happy', 'they are happy', 'they share too', 'we have fun', 'friendship', 'they like me'],
          sampleAnswer: 'My friend feels happy and shares back.',
          teach: 'Kind causes make kind effects. It really works that way.',
        },
      ],
    },
  },
  {
    id: 'g1_think_28',
    subject: 'thinking',
    grade: 1,
    title: 'Is That a Good Reason',
    blurb: 'Some reasons are strong. Some are wobbly.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_28_a',
          prompt: '"You should wear a helmet because it protects your head." Is that a good reason?',
          options: ['Yes, it explains why', 'No, helmets are silly', 'No reason is good', 'Only on Tuesdays'],
          correct: 0,
          teach: 'It gives a real why. That makes it strong.',
        },
        {
          kind: 'choice',
          id: 'g1_think_28_b',
          prompt: '"You should do it because everyone does it." Is that a strong reason?',
          options: ['Very strong', 'Wobbly — everyone can be wrong', 'The strongest', 'Reasons do not matter'],
          correct: 1,
          teach: 'Wobbly. Lots of people doing something does not make it right.',
        },
        {
          kind: 'choice',
          id: 'g1_think_28_c',
          prompt: '"Eat vegetables because they help your body grow strong." Strong or wobbly?',
          options: ['Strong — it says why', 'Wobbly', 'Silly', 'Mean'],
          correct: 0,
          teach: 'Strong. It connects the action to a real benefit.',
        },
        {
          kind: 'speak',
          id: 'g1_think_28_d',
          prompt: 'Give me a good reason to brush your teeth.',
          accept: ['clean', 'healthy', 'cavities', 'no cavities', 'germs', 'keep them strong', 'so they do not rot'],
          sampleAnswer: 'To keep them clean and stop cavities.',
          teach: 'A real reason with a real why. Excellent.',
        },
        {
          kind: 'choice',
          id: 'g1_think_28_e',
          prompt: '"Because I said so" tells you...',
          options: ['The full reason', 'That the reason was not explained', 'Everything', 'A lie'],
          correct: 1,
          teach: 'It skips the why. Grown-ups sometimes use it when busy — but real whys exist.',
        },
      ],
    },
  },
  {
    id: 'g1_think_29',
    subject: 'thinking',
    grade: 1,
    title: 'Imagine If',
    blurb: 'Imagining is thinking about what is not here yet.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_29_a',
          prompt: 'Imagine everyone could fly. What problem would we have?',
          options: ['No problems ever', 'Crowded skies and bumping', 'Shoes would cry', 'The ground would leave'],
          correct: 1,
          teach: 'The sky would need traffic rules! Imagining finds new problems to solve.',
        },
        {
          kind: 'choice',
          id: 'g1_think_29_b',
          prompt: 'Imagine there were no clocks anywhere. What would be hard?',
          options: ['Nothing', 'Knowing when to meet people', 'Eating', 'Sleeping'],
          correct: 1,
          teach: 'Meeting at the same time would be very tricky without clocks.',
        },
        {
          kind: 'speak',
          id: 'g1_think_29_c',
          prompt: 'Imagine your pet could talk for one day. What would you ask it?',
          accept: ['i would ask', 'what', 'why', 'how', 'do you', 'are you'],
          sampleAnswer: 'I would ask what it dreams about.',
          teach: 'What a question! Imagining opens doors that are not there yet.',
        },
        {
          kind: 'choice',
          id: 'g1_think_29_d',
          prompt: 'Imagine a world with no colors, only gray. What would you miss most?',
          options: ['Nothing', 'Rainbows and sunsets', 'Gray things', 'Rocks'],
          correct: 1,
          teach: 'Imagining what is missing teaches us what we treasure.',
        },
        {
          kind: 'speak',
          id: 'g1_think_29_e',
          prompt: 'Invent a brand new holiday. What would we celebrate?',
          accept: ['day', 'we would', 'celebrate', 'a holiday', 'i would make'],
          sampleAnswer: 'Kindness Day, where everyone does one secret kind thing.',
          teach: 'A brand new idea from your very own head. That is creation.',
        },
      ],
    },
  },
  {
    id: 'g1_think_30',
    subject: 'thinking',
    grade: 1,
    title: 'The Thinking Crown',
    blurb: 'The last thinking star. Every kind of puzzle, one more time.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_30_a',
          prompt: 'Square, circle, square, circle, square... what comes next?',
          options: ['Square', 'Circle', 'Triangle', 'Heart'],
          correct: 1,
          teach: 'Circle. Patterns were our very first puzzle — and you still see them.',
        },
        {
          kind: 'choice',
          id: 'g1_think_30_b',
          prompt: 'Bird, bee, butterfly, dog. Which does not belong?',
          options: ['Bird', 'Bee', 'Butterfly', 'Dog'],
          correct: 3,
          teach: 'The dog — all the others can fly.',
        },
        {
          kind: 'order',
          id: 'g1_think_30_c',
          prompt: 'Put these story parts in order.',
          items: ['Once upon a time', 'A problem happened', 'They solved it', 'The end'],
          teach: 'Beginning, problem, solution, ending. Every story you know follows this.',
        },
        {
          kind: 'choice',
          id: 'g1_think_30_d',
          prompt: 'The sidewalk is wet but the street is dry. What probably happened?',
          options: ['It rained everywhere', 'Someone watered plants near the sidewalk', 'The street is magic', 'Nothing'],
          correct: 1,
          teach: 'Rain would wet both. A sprinkler or hose explains just the sidewalk. Detective-level thinking!',
        },
        {
          kind: 'speak',
          id: 'g1_think_30_e',
          prompt: 'I have a face and two hands but no arms or legs. What am I?',
          accept: ['clock', 'a clock', 'watch', 'a watch'],
          sampleAnswer: 'A clock.',
          teach: 'A clock! You finished every thinking star. Your brain is stronger than when you started.',
        },
        {
          kind: 'speak',
          id: 'g1_think_30_f',
          prompt: 'What was the hardest puzzle in all these stars? Why was it hard?',
          accept: ['the', 'it was', 'because', 'riddle', 'pattern', 'hard'],
          sampleAnswer: 'The riddles, because the answer hides.',
          teach: 'Knowing what is hard for you is the smartest thinking of all. I am proud of you.',
        },
      ],
    },
  },
];
