import type { Star } from '../../types';

/**
 * Grade 1 critical thinking — 10 stars.
 *
 * The point is reasoning, not recall, so most challenges ask "why" as a follow
 * up to "which". Riddles are kept fair: every one can be worked out from what
 * is stated, with no trick knowledge required.
 */

export const grade1Thinking: Star[] = [
  {
    id: 'g1_think_01',
    subject: 'thinking',
    grade: 1,
    title: 'What Comes Next',
    blurb: 'Patterns are everywhere once you start looking.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_01_a',
          prompt: 'Circle, square, circle, square, circle... what comes next?',
          display: '⭕ ⬛ ⭕ ⬛ ⭕ ❓',
          options: ['Square', 'Circle', 'Triangle', 'Star'],
          correct: 0,
          teach: 'Square. The pattern goes back and forth between two shapes.',
        },
        {
          kind: 'choice',
          id: 'g1_think_01_b',
          prompt: 'Red, red, blue, red, red, blue, red... what comes next?',
          display: '🔴 🔴 🔵 🔴 🔴 🔵 🔴 ❓',
          options: ['Blue', 'Red', 'Green', 'Nothing'],
          correct: 1,
          teach: 'Red. The group is red-red-blue, so we are only one red in.',
          hint: 'Say it out loud in groups of three.',
        },
        {
          kind: 'choice',
          id: 'g1_think_01_c',
          prompt: 'Big, small, big, small, big... what comes next?',
          options: ['Small', 'Big', 'Medium', 'Huge'],
          correct: 0,
          teach: 'Small. Two things taking turns again.',
        },
        {
          kind: 'order',
          id: 'g1_think_01_d',
          prompt: 'Put these in order from smallest to biggest.',
          items: ['Ant', 'Cat', 'Horse', 'Elephant'],
          teach: 'Ant, cat, horse, elephant. You sorted by size in your head.',
        },
        {
          kind: 'speak',
          id: 'g1_think_01_e',
          prompt: 'Clap, clap, stomp, clap, clap, stomp. What comes after the stomp?',
          accept: ['clap', 'a clap', 'clapping', 'clap clap'],
          sampleAnswer: 'Clap.',
          teach: 'Clap. Patterns work with sounds just as well as with shapes.',
        },
        {
          kind: 'choice',
          id: 'g1_think_01_f',
          prompt: 'Which one breaks the pattern? Square, square, square, circle, square.',
          options: ['The first square', 'The circle', 'The last square', 'Nothing breaks it'],
          correct: 1,
          teach: 'The circle. Finding what does not fit is its own useful skill.',
        },
      ],
    },
  },
  {
    id: 'g1_think_02',
    subject: 'thinking',
    grade: 1,
    title: 'Which One Does Not Belong',
    blurb: 'Sometimes there is more than one good answer. I want to hear your reason.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_02_a',
          prompt: 'Which one does not belong? Apple, banana, carrot, orange.',
          options: ['Apple', 'Banana', 'Carrot', 'Orange'],
          correct: 2,
          teach: 'Carrot. The others are fruit, and a carrot is a vegetable.',
        },
        {
          kind: 'choice',
          id: 'g1_think_02_b',
          prompt: 'Which one does not belong? Dog, cat, rabbit, chair.',
          options: ['Dog', 'Cat', 'Rabbit', 'Chair'],
          correct: 3,
          teach: 'Chair. The others are alive.',
        },
        {
          kind: 'choice',
          id: 'g1_think_02_c',
          prompt: 'Which one does not belong? Shoe, sock, boot, hat.',
          options: ['Shoe', 'Sock', 'Boot', 'Hat'],
          correct: 3,
          teach: 'Hat. The other three go on your feet.',
        },
        {
          kind: 'speak',
          id: 'g1_think_02_d',
          prompt: 'Sun, moon, star, rock. Which does not belong, and why?',
          accept: ['rock', 'the rock', 'rock because', 'a rock'],
          sampleAnswer: 'The rock, because the others are in the sky.',
          hint: 'Where do you find each one?',
          teach: 'The rock. The others are all up in the sky.',
        },
        {
          kind: 'choice',
          id: 'g1_think_02_e',
          prompt: 'Which one does not belong? Two, four, six, seven.',
          options: ['Two', 'Four', 'Six', 'Seven'],
          correct: 3,
          teach: 'Seven. The others are all even numbers you say when counting by twos.',
        },
        {
          kind: 'speak',
          id: 'g1_think_02_f',
          prompt: 'Here is a hard one. Circle, ball, wheel, box. Which does not belong?',
          accept: ['box', 'the box', 'box because'],
          sampleAnswer: 'The box, because the others are round.',
          teach: 'The box. Everything else is round.',
        },
      ],
    },
  },
  {
    id: 'g1_think_03',
    subject: 'thinking',
    grade: 1,
    title: 'Because and So',
    blurb: 'Every thing that happens has a reason behind it.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_03_a',
          prompt: 'The grass is wet. What most likely happened?',
          options: ['It rained', 'The sun was hot', 'It was very windy', 'Someone shouted'],
          correct: 0,
          teach: 'Rain is the most likely reason. Good thinking.',
        },
        {
          kind: 'choice',
          id: 'g1_think_03_b',
          prompt: 'Ana is holding an umbrella and wearing boots. What is the weather?',
          options: ['Hot and sunny', 'Rainy', 'Very snowy', 'Windy but dry'],
          correct: 1,
          teach: 'Rainy. You read the clues instead of being told.',
        },
        {
          kind: 'choice',
          id: 'g1_think_03_c',
          prompt: 'The plant turned brown and dry. What probably happened?',
          options: [
            'It got too much water',
            'Nobody watered it',
            'It was moved to a bigger pot',
            'Someone sang to it',
          ],
          correct: 1,
          teach: 'It needed water. Dry and brown is what thirsty looks like on a plant.',
        },
        {
          kind: 'speak',
          id: 'g1_think_03_d',
          prompt: 'You hear the smoke alarm beeping in the kitchen. What might be happening?',
          accept: ['something is burning', 'burning', 'smoke', 'fire', 'the food is burning', 'toast'],
          sampleAnswer: 'Something might be burning.',
          teach: 'Yes. And that is a sound you should always tell a grown-up about.',
        },
        {
          kind: 'choice',
          id: 'g1_think_03_e',
          prompt: 'Mia is yawning and rubbing her eyes. What does she probably need?',
          options: ['A snack', 'Sleep', 'A coat', 'A book'],
          correct: 1,
          teach: 'Sleep. Bodies give us clues about what they need.',
        },
        {
          kind: 'speak',
          id: 'g1_think_03_f',
          prompt: 'The ice cream is a puddle on the sidewalk. Tell me why.',
          accept: ['it melted', 'melted', 'it was hot', 'the sun', 'it got warm', 'because it was hot'],
          sampleAnswer: 'It melted because it was hot outside.',
          teach: 'It melted. Heat turns solid ice cream into liquid.',
        },
      ],
    },
  },
  {
    id: 'g1_think_04',
    subject: 'thinking',
    grade: 1,
    title: 'Put the Story in Order',
    blurb: 'Things happen in an order. Let us get them right.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'order',
          id: 'g1_think_04_a',
          prompt: 'Put these in the right order for planting a seed.',
          items: ['Dig a small hole', 'Drop in the seed', 'Cover it with soil', 'Give it water'],
          teach: 'Dig, drop, cover, water. Order matters — you cannot water a seed you have not planted.',
        },
        {
          kind: 'order',
          id: 'g1_think_04_b',
          prompt: 'Put these in order for making a sandwich.',
          items: ['Get two slices of bread', 'Spread on the filling', 'Put the slices together', 'Take a bite'],
          teach: 'Exactly right.',
        },
        {
          kind: 'order',
          id: 'g1_think_04_c',
          prompt: 'Put these in order from first to last in a day.',
          items: ['Wake up', 'Eat breakfast', 'Go to school', 'Go to bed'],
          teach: 'That is a whole day, start to finish.',
        },
        {
          kind: 'order',
          id: 'g1_think_04_d',
          prompt: 'Put the butterfly\'s life in order.',
          items: ['An egg on a leaf', 'A hungry caterpillar', 'A hard chrysalis', 'A butterfly flies away'],
          teach: 'Egg, caterpillar, chrysalis, butterfly. That is called a life cycle.',
          hint: 'Which one is the very smallest to begin with?',
        },
        {
          kind: 'order',
          id: 'g1_think_04_e',
          prompt: 'Put these in order, smallest amount of time to longest.',
          items: ['A second', 'A minute', 'An hour', 'A day'],
          teach: 'Second, minute, hour, day. Each one holds many of the one before it.',
        },
      ],
    },
  },
  {
    id: 'g1_think_05',
    subject: 'thinking',
    grade: 1,
    title: 'Riddles in the Dark',
    blurb: 'Every clue you need is right there in the words.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_05_a',
          prompt: 'I am full of holes, but I can still hold water. What am I?',
          accept: ['sponge', 'a sponge'],
          sampleAnswer: 'A sponge.',
          hint: 'You might find me by the kitchen sink.',
          teach: 'A sponge. The holes are exactly what let it hold the water.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_b',
          prompt: 'I go up when the rain comes down. What am I?',
          accept: ['umbrella', 'an umbrella'],
          sampleAnswer: 'An umbrella.',
          teach: 'An umbrella. Up it goes.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_c',
          prompt: 'I have hands but I cannot clap. What am I?',
          accept: ['clock', 'a clock', 'watch', 'a watch'],
          sampleAnswer: 'A clock.',
          hint: 'I tell you when it is time for dinner.',
          teach: 'A clock. Its hands point instead of clapping.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_d',
          prompt: 'I follow you everywhere in the sunshine, but you cannot catch me. What am I?',
          accept: ['shadow', 'my shadow', 'your shadow', 'a shadow'],
          sampleAnswer: 'A shadow.',
          teach: 'Your shadow. It goes where you go and never lets you grab it.',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_e',
          prompt: 'The more you take away from me, the bigger I get. What am I?',
          accept: ['hole', 'a hole'],
          sampleAnswer: 'A hole.',
          hint: 'Think about digging.',
          teach: 'A hole. That one bends your brain a little, does it not?',
        },
        {
          kind: 'speak',
          id: 'g1_think_05_f',
          prompt: 'I am light as a feather, but nobody can hold me for long. What am I?',
          accept: ['breath', 'your breath', 'air', 'my breath'],
          sampleAnswer: 'Your breath.',
          teach: 'Your breath. Try holding it and you will see.',
        },
      ],
    },
  },
  {
    id: 'g1_think_06',
    subject: 'thinking',
    grade: 1,
    title: 'Same and Different',
    blurb: 'Two things can be alike in one way and different in another.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_06_a',
          prompt: 'How are a cat and a dog the same?',
          accept: ['animals', 'they are animals', 'pets', 'they are pets', 'four legs', 'they have fur', 'fur'],
          sampleAnswer: 'They are both animals with four legs.',
          teach: 'Both animals, both pets, both have fur and four legs. Lots of ways.',
        },
        {
          kind: 'speak',
          id: 'g1_think_06_b',
          prompt: 'Now tell me one way a cat and a dog are different.',
          accept: ['barks', 'dogs bark', 'meow', 'cats meow', 'size', 'climb', 'sound'],
          sampleAnswer: 'Dogs bark and cats meow.',
          teach: 'Good. Same in some ways, different in others. Most things are.',
        },
        {
          kind: 'choice',
          id: 'g1_think_06_c',
          prompt: 'How are a bicycle and a car the same?',
          options: [
            'They both have wheels',
            'They both have engines',
            'They both need gas',
            'They are both very small',
          ],
          correct: 0,
          teach: 'Wheels. That is the thing they share.',
        },
        {
          kind: 'choice',
          id: 'g1_think_06_d',
          prompt: 'How are the sun and a lamp the same?',
          options: [
            'They both give light',
            'They are both very far away',
            'They both run on batteries',
            'They are both cold',
          ],
          correct: 0,
          teach: 'They both give light. One is a bit bigger than the other.',
        },
        {
          kind: 'match',
          id: 'g1_think_06_e',
          prompt: 'Match each baby animal to its grown-up.',
          pairs: [
            { left: 'Puppy', right: 'Dog' },
            { left: 'Kitten', right: 'Cat' },
            { left: 'Chick', right: 'Hen' },
            { left: 'Calf', right: 'Cow' },
          ],
          teach: 'Every one of those grows up into the other.',
        },
      ],
    },
  },
  {
    id: 'g1_think_07',
    subject: 'thinking',
    grade: 1,
    title: 'What Would You Do',
    blurb: 'These have no single right answer. I want to hear how you think.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_07_a',
          prompt: 'You see a friend sitting alone at lunch looking sad. What could you do?',
          accept: ['sit with her', 'ask her', 'talk to her', 'i would sit', 'ask what is wrong', 'go over', 'sit'],
          sampleAnswer: 'I would go sit with her and ask if she is okay.',
          teach: 'That is a kind plan. Just going over is usually enough.',
        },
        {
          kind: 'speak',
          id: 'g1_think_07_b',
          prompt: 'You broke something by accident and nobody saw. What should you do?',
          accept: ['tell', 'tell the truth', 'say sorry', 'tell my mom', 'be honest', 'i would tell'],
          sampleAnswer: 'Tell a grown-up the truth.',
          teach: 'Telling the truth is harder when nobody saw. That is exactly when it counts.',
        },
        {
          kind: 'choice',
          id: 'g1_think_07_c',
          prompt: 'You are lost in a big store. What is the safest thing to do?',
          options: [
            'Run around looking for your grown-up',
            'Go outside to the parking lot',
            'Stay put and ask a worker for help',
            'Hide until they find you',
          ],
          correct: 2,
          teach: 'Stay where you are and ask a worker. Moving around makes you harder to find.',
        },
        {
          kind: 'speak',
          id: 'g1_think_07_d',
          prompt: 'Your sister is using the toy you wanted. What could you do that is not fighting?',
          accept: ['ask', 'ask for a turn', 'wait', 'take turns', 'play with something else', 'share', 'ask nicely'],
          sampleAnswer: 'Ask if I can have a turn when she is done.',
          teach: 'Asking and waiting. Both harder than grabbing, and both work better.',
        },
        {
          kind: 'choice',
          id: 'g1_think_07_e',
          prompt: 'Someone you do not know asks you to go with them. What do you do?',
          options: [
            'Go if they seem nice',
            'Say no and find a grown-up you know',
            'Ask them where they are going',
            'Follow them a little way',
          ],
          correct: 1,
          teach: 'Say no and find a grown-up you trust. Always. No matter how nice they seem.',
        },
      ],
    },
  },
  {
    id: 'g1_think_08',
    subject: 'thinking',
    grade: 1,
    title: 'Sorting Things Out',
    blurb: 'Putting things into groups is a kind of thinking.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'match',
          id: 'g1_think_08_a',
          prompt: 'Match each thing to where it belongs.',
          pairs: [
            { left: 'Fish', right: 'Water' },
            { left: 'Bird', right: 'Sky' },
            { left: 'Worm', right: 'Soil' },
            { left: 'Squirrel', right: 'Tree' },
          ],
          teach: 'Every creature has a home that fits it.',
        },
        {
          kind: 'match',
          id: 'g1_think_08_b',
          prompt: 'Match each tool to the job it does.',
          pairs: [
            { left: 'Scissors', right: 'Cutting' },
            { left: 'Spoon', right: 'Eating soup' },
            { left: 'Broom', right: 'Sweeping' },
            { left: 'Pencil', right: 'Writing' },
          ],
          teach: 'Tools are made on purpose for one job.',
        },
        {
          kind: 'choice',
          id: 'g1_think_08_c',
          prompt: 'Which group do a hammer, a saw, and a screwdriver belong to?',
          options: ['Foods', 'Tools', 'Animals', 'Clothes'],
          correct: 1,
          teach: 'Tools. You found the group they share.',
        },
        {
          kind: 'choice',
          id: 'g1_think_08_d',
          prompt: 'Which of these is NOT something you wear?',
          options: ['Scarf', 'Mitten', 'Kettle', 'Sock'],
          correct: 2,
          teach: 'A kettle. That one boils water instead.',
        },
        {
          kind: 'speak',
          id: 'g1_think_08_e',
          prompt: 'Name three things you would find in a kitchen.',
          accept: ['spoon', 'fork', 'plate', 'cup', 'pot', 'pan', 'stove', 'sink', 'fridge', 'bowl', 'knife'],
          sampleAnswer: 'A spoon, a plate, and a cup.',
          teach: 'Nicely sorted. You pictured the room and read it in your mind.',
        },
      ],
    },
  },
  {
    id: 'g1_think_09',
    subject: 'thinking',
    grade: 1,
    title: 'Number Puzzles',
    blurb: 'Thinking puzzles that happen to use numbers.',
    minutes: 11,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'speak',
          id: 'g1_think_09_a',
          prompt: 'There are 3 birds on a branch. Two more land. Then one flies away. How many now?',
          accept: ['4', 'four'],
          sampleAnswer: '4',
          hint: 'Do it one step at a time. Three, then five, then...',
          teach: 'Four. Three plus two is five, minus one is four.',
        },
        {
          kind: 'speak',
          id: 'g1_think_09_b',
          prompt: 'You have 2 hands. Each hand has 5 fingers. How many fingers altogether?',
          accept: ['10', 'ten'],
          sampleAnswer: '10',
          teach: 'Ten. Two groups of five.',
        },
        {
          kind: 'choice',
          id: 'g1_think_09_c',
          prompt: 'Zoe is taller than Mia. Mia is taller than Ana. Who is the tallest?',
          options: ['Zoe', 'Mia', 'Ana', 'They are the same'],
          correct: 0,
          teach: 'Zoe. You lined all three up in your head without ever seeing them.',
          hint: 'Line them up one at a time, tallest first.',
        },
        {
          kind: 'choice',
          id: 'g1_think_09_d',
          prompt: 'A basket holds 4 apples. You take 4 out. How many are left?',
          options: ['4', '1', '0', '8'],
          correct: 2,
          teach: 'Zero. An empty basket.',
        },
        {
          kind: 'speak',
          id: 'g1_think_09_e',
          prompt: 'If today is Tuesday, what day is tomorrow?',
          accept: ['wednesday'],
          sampleAnswer: 'Wednesday',
          teach: 'Wednesday. Days come in an order, just like numbers.',
        },
        {
          kind: 'speak',
          id: 'g1_think_09_f',
          prompt: 'A cat has 4 legs. How many legs do 2 cats have?',
          accept: ['8', 'eight'],
          sampleAnswer: '8',
          teach: 'Eight. Two groups of four.',
        },
      ],
    },
  },
  {
    id: 'g1_think_10',
    subject: 'thinking',
    grade: 1,
    title: 'Is That Always True',
    blurb: 'Some things are true sometimes, and some are true always. There is a difference.',
    minutes: 12,
    content: {
      kind: 'fixed',
      challenges: [
        {
          kind: 'choice',
          id: 'g1_think_10_a',
          prompt: 'True or not always true? "All birds can fly."',
          options: ['Always true', 'Not always true'],
          correct: 1,
          teach: 'Not always. Penguins and ostriches are birds, and they cannot fly.',
        },
        {
          kind: 'choice',
          id: 'g1_think_10_b',
          prompt: 'True or not always true? "All squares have four sides."',
          options: ['Always true', 'Not always true'],
          correct: 0,
          teach: 'Always true. Four sides is part of what makes it a square.',
        },
        {
          kind: 'choice',
          id: 'g1_think_10_c',
          prompt: 'True or not always true? "If it is cloudy, it will rain."',
          options: ['Always true', 'Not always true'],
          correct: 1,
          teach: 'Not always. Plenty of cloudy days stay dry.',
        },
        {
          kind: 'choice',
          id: 'g1_think_10_d',
          prompt: 'True or not always true? "Every person needs water to live."',
          options: ['Always true', 'Not always true'],
          correct: 0,
          teach: 'Always true. That one has no exceptions.',
        },
        {
          kind: 'speak',
          id: 'g1_think_10_e',
          prompt: 'Someone says "all dogs are big." Can you think of a dog that proves it wrong?',
          accept: ['puppy', 'a puppy', 'small dog', 'chihuahua', 'little dog', 'baby dog', 'a small one'],
          sampleAnswer: 'A puppy is a small dog.',
          teach: 'One example is enough to show that an "all" statement is wrong. That is real logic.',
        },
        {
          kind: 'speak',
          id: 'g1_think_10_f',
          prompt: 'Is this always true? "The sun comes up in the morning."',
          accept: ['yes', 'true', 'always', 'always true', 'yes it is'],
          sampleAnswer: 'Yes, that is always true.',
          teach: 'That one holds up. Every single morning, so far.',
        },
      ],
    },
  },
];
