import type { Star } from '../../types';
import { buildVocabStar, type VocabStarSpec } from '../vocabBuilder';

/**
 * Grade 1 vocabulary — 10 stars, 6 words each, grouped by theme so related
 * words reinforce one another. Definitions are written the way you would say
 * them out loud to a six-year-old, because AnSo reads them aloud.
 */

const specs: VocabStarSpec[] = [
  {
    id: 'g1_vocab_01',
    grade: 1,
    title: 'Feeling Words',
    blurb: 'Words for what happens inside you.',
    minutes: 11,
    words: [
      {
        word: 'joyful',
        meaning: 'very happy, all the way through',
        cloze: 'She was ____ when she saw the puppy.',
        decoys: ['very tired and sleepy', 'a little bit cold', 'quiet and still'],
      },
      {
        word: 'nervous',
        meaning: 'worried about something that is coming',
        cloze: 'I felt ____ before my first day of school.',
        decoys: ['very fast', 'full of food', 'sure about everything'],
      },
      {
        word: 'proud',
        meaning: 'glad about something good you did',
        cloze: 'She was ____ that she tied her own shoes.',
        decoys: ['sorry about a mistake', 'hungry for lunch', 'lost in a big store'],
      },
      {
        word: 'gentle',
        meaning: 'soft and careful, not rough',
        cloze: 'Be ____ when you hold the baby bird.',
        decoys: ['loud and fast', 'angry at someone', 'far away'],
      },
      {
        word: 'curious',
        meaning: 'wanting very much to know',
        cloze: 'She was ____ about what was in the box.',
        decoys: ['bored by everything', 'ready to sleep', 'sure she was right'],
      },
      {
        word: 'grateful',
        meaning: 'thankful for something you were given',
        cloze: 'I am ____ for my warm bed.',
        decoys: ['upset about a gift', 'unsure what to do', 'faster than before'],
      },
    ],
  },
  {
    id: 'g1_vocab_02',
    grade: 1,
    title: 'Sky Words',
    blurb: 'Words for the things above your head.',
    minutes: 11,
    words: [
      {
        word: 'orbit',
        meaning: 'the path something takes as it goes around something else',
        cloze: 'The moon travels in an ____ around Earth.',
        decoys: ['a hole in the ground', 'a kind of loud noise', 'the top of a hill'],
        note: 'Orbit is a path, not a place. The moon is always on the move.',
      },
      {
        word: 'glow',
        meaning: 'to give off a soft light',
        cloze: 'The stars ____ in the dark sky.',
        decoys: ['to fall down fast', 'to be very cold', 'to make a loud sound'],
      },
      {
        word: 'vast',
        meaning: 'very, very big',
        cloze: 'Space is ____ and full of stars.',
        decoys: ['very small', 'nearly empty of air', 'made of stone'],
      },
      {
        word: 'distant',
        meaning: 'very far away',
        cloze: 'That ____ star took years to send its light to us.',
        decoys: ['close enough to touch', 'brand new', 'broken in half'],
      },
      {
        word: 'shimmer',
        meaning: 'to shine with a light that wobbles',
        cloze: 'The water began to ____ in the sunlight.',
        decoys: ['to sink slowly', 'to grow taller', 'to become silent'],
      },
      {
        word: 'journey',
        meaning: 'a long trip from one place to another',
        cloze: 'We are on a ____ through the stars.',
        decoys: ['a short nap', 'a kind of meal', 'a small room'],
      },
    ],
  },
  {
    id: 'g1_vocab_03',
    grade: 1,
    title: 'Doing Words',
    blurb: 'Strong words for things you can do.',
    minutes: 11,
    words: [
      {
        word: 'discover',
        meaning: 'to find something out for the first time',
        cloze: 'Let us ____ what is inside this shell.',
        decoys: ['to lose something', 'to close a door', 'to sit down slowly'],
      },
      {
        word: 'wander',
        meaning: 'to walk slowly with no set plan',
        cloze: 'We like to ____ through the garden.',
        decoys: ['to run in a straight line', 'to shout loudly', 'to fall asleep'],
      },
      {
        word: 'gather',
        meaning: 'to bring things together into one place',
        cloze: 'Let us ____ all the leaves in a pile.',
        decoys: ['to throw things apart', 'to hide alone', 'to break something'],
      },
      {
        word: 'whisper',
        meaning: 'to talk in a very soft voice',
        cloze: 'You have to ____ in the library.',
        decoys: ['to yell as loud as you can', 'to sing a fast song', 'to stay silent'],
      },
      {
        word: 'balance',
        meaning: 'to hold steady without falling',
        cloze: 'She can ____ on one foot for ten seconds.',
        decoys: ['to fall down on purpose', 'to run very fast', 'to lie flat'],
      },
      {
        word: 'protect',
        meaning: 'to keep something safe from harm',
        cloze: 'A helmet will ____ your head.',
        decoys: ['to break something on purpose', 'to give away', 'to forget about'],
      },
    ],
  },
  {
    id: 'g1_vocab_04',
    grade: 1,
    title: 'Size and Shape',
    blurb: 'Words that tell us how big, how small, how wide.',
    minutes: 11,
    words: [
      {
        word: 'tiny',
        meaning: 'extremely small',
        cloze: 'An ant is a ____ creature.',
        decoys: ['taller than a house', 'very heavy', 'made of glass'],
      },
      {
        word: 'enormous',
        meaning: 'extremely large',
        cloze: 'A whale is an ____ animal.',
        decoys: ['smaller than a bug', 'very quiet', 'nearly invisible'],
      },
      {
        word: 'narrow',
        meaning: 'not wide, close together on the sides',
        cloze: 'We walked down a ____ path between the trees.',
        decoys: ['very wide open', 'high in the air', 'colored bright red'],
      },
      {
        word: 'curved',
        meaning: 'bending, not straight',
        cloze: 'The road was ____ like the letter C.',
        decoys: ['perfectly straight', 'broken in two', 'standing still'],
      },
      {
        word: 'hollow',
        meaning: 'empty on the inside',
        cloze: 'The owl lived in a ____ tree.',
        decoys: ['packed full of rocks', 'painted green', 'very sharp'],
      },
      {
        word: 'steep',
        meaning: 'going up or down very sharply',
        cloze: 'The hill was too ____ to ride down.',
        decoys: ['flat and level', 'warm to touch', 'made of water'],
      },
    ],
  },
  {
    id: 'g1_vocab_05',
    grade: 1,
    title: 'Kindness Words',
    blurb: 'Words for how we treat each other.',
    minutes: 11,
    words: [
      {
        word: 'patient',
        meaning: 'able to wait without getting upset',
        cloze: 'She was ____ while her sister finished her turn.',
        decoys: ['always in a rush', 'unkind to others', 'very loud'],
      },
      {
        word: 'honest',
        meaning: 'telling the truth even when it is hard',
        cloze: 'He was ____ and said he broke the cup.',
        decoys: ['saying things that are not true', 'very fast at running', 'good at drawing'],
      },
      {
        word: 'forgive',
        meaning: 'to stop being angry at someone who was sorry',
        cloze: 'She chose to ____ her friend.',
        decoys: ['to stay angry forever', 'to run away', 'to give a present'],
      },
      {
        word: 'include',
        meaning: 'to let someone join in with you',
        cloze: 'Let us ____ her in our game.',
        decoys: ['to leave someone out', 'to hide from someone', 'to laugh at someone'],
      },
      {
        word: 'comfort',
        meaning: 'to help someone feel better when they are sad',
        cloze: 'She sat close to ____ her friend.',
        decoys: ['to make someone cry', 'to walk away', 'to shout at someone'],
      },
      {
        word: 'generous',
        meaning: 'happy to give and share',
        cloze: 'It was ____ of him to share his snack.',
        decoys: ['keeping everything', 'always hungry', 'good at math'],
      },
    ],
  },
  {
    id: 'g1_vocab_06',
    grade: 1,
    title: 'Weather Words',
    blurb: 'Words for what the sky is doing today.',
    minutes: 11,
    words: [
      {
        word: 'breeze',
        meaning: 'a light, gentle wind',
        cloze: 'A cool ____ moved through the trees.',
        decoys: ['a heavy rock', 'a warm blanket', 'a loud bang'],
      },
      {
        word: 'drizzle',
        meaning: 'very light rain',
        cloze: 'It was only a ____, so we still went outside.',
        decoys: ['bright sunshine', 'thick snow', 'strong wind'],
      },
      {
        word: 'thunder',
        meaning: 'the loud sound that comes after lightning',
        cloze: 'The ____ made the windows shake.',
        decoys: ['a soft light', 'a kind of cloud', 'a small puddle'],
      },
      {
        word: 'frost',
        meaning: 'thin white ice on cold mornings',
        cloze: 'There was ____ on the grass when we woke up.',
        decoys: ['warm steam', 'green moss', 'falling leaves'],
      },
      {
        word: 'humid',
        meaning: 'sticky because the air is full of water',
        cloze: 'The day was hot and ____.',
        decoys: ['dry and dusty', 'freezing cold', 'very windy'],
      },
      {
        word: 'clear',
        meaning: 'with nothing in the way to block your view',
        cloze: 'The night was ____, so we saw every star.',
        decoys: ['covered in thick clouds', 'full of noise', 'very crowded'],
      },
    ],
  },
  {
    id: 'g1_vocab_07',
    grade: 1,
    title: 'Story Words',
    blurb: 'Words that help you talk about books.',
    minutes: 11,
    words: [
      {
        word: 'character',
        meaning: 'a person or animal in a story',
        cloze: 'My favorite ____ in that book is the little owl.',
        decoys: ['the place a story happens', 'the last page', 'the color of a book'],
      },
      {
        word: 'setting',
        meaning: 'where and when a story happens',
        cloze: 'The ____ of the story is a farm long ago.',
        decoys: ['the person telling the story', 'the problem in a story', 'the name of a book'],
      },
      {
        word: 'problem',
        meaning: 'the trouble the characters have to solve',
        cloze: 'The ____ was that the bridge kept falling down.',
        decoys: ['the happy ending', 'the cover of a book', 'a kind of animal'],
      },
      {
        word: 'solution',
        meaning: 'the way a problem gets fixed',
        cloze: 'Her ____ was to make the stacks wider.',
        decoys: ['the start of a story', 'a kind of weather', 'a sad feeling'],
      },
      {
        word: 'author',
        meaning: 'the person who wrote the book',
        cloze: 'The ____ of this book also drew the pictures.',
        decoys: ['a person who reads a book', 'a person in the story', 'a kind of library'],
      },
      {
        word: 'predict',
        meaning: 'to guess what will happen next',
        cloze: 'Can you ____ how the story will end?',
        decoys: ['to remember the beginning', 'to close the book', 'to read out loud'],
      },
    ],
  },
  {
    id: 'g1_vocab_08',
    grade: 1,
    title: 'Nature Words',
    blurb: 'Words from outside your window.',
    minutes: 11,
    words: [
      {
        word: 'meadow',
        meaning: 'a wide field full of grass and flowers',
        cloze: 'We ran across the ____ looking for butterflies.',
        decoys: ['a tall building', 'a deep cave', 'a busy road'],
      },
      {
        word: 'burrow',
        meaning: 'a hole an animal digs to live in',
        cloze: 'The rabbit went down into its ____.',
        decoys: ['a nest high in a tree', 'a kind of bird', 'a small stream'],
      },
      {
        word: 'blossom',
        meaning: 'a flower on a tree or plant',
        cloze: 'Every ____ on the tree opened in spring.',
        decoys: ['a fallen branch', 'a piece of bark', 'a small stone'],
      },
      {
        word: 'stream',
        meaning: 'a small, narrow river',
        cloze: 'We stepped over the ____ on flat rocks.',
        decoys: ['a wide ocean', 'a dry desert', 'a tall mountain'],
      },
      {
        word: 'shade',
        meaning: 'a cool dark place out of the sun',
        cloze: 'We sat in the ____ under the big tree.',
        decoys: ['the hottest spot', 'the top of a hill', 'a bright light'],
      },
      {
        word: 'creature',
        meaning: 'any living animal',
        cloze: 'Every ____ in the pond went quiet at once.',
        decoys: ['a kind of rock', 'a type of cloud', 'a machine'],
      },
    ],
  },
  {
    id: 'g1_vocab_09',
    grade: 1,
    title: 'Thinking Words',
    blurb: 'Words for what your mind does.',
    minutes: 11,
    words: [
      {
        word: 'imagine',
        meaning: 'to make a picture in your mind',
        cloze: 'Close your eyes and ____ a purple elephant.',
        decoys: ['to forget on purpose', 'to say out loud', 'to write down'],
      },
      {
        word: 'notice',
        meaning: 'to see something you might have missed',
        cloze: 'Did you ____ the bird on the fence?',
        decoys: ['to look away quickly', 'to break something', 'to fall asleep'],
      },
      {
        word: 'compare',
        meaning: 'to look at how things are the same or different',
        cloze: 'Let us ____ these two leaves.',
        decoys: ['to throw two things away', 'to count to ten', 'to draw a circle'],
      },
      {
        word: 'explain',
        meaning: 'to tell someone how or why something works',
        cloze: 'Can you ____ how you got that answer?',
        decoys: ['to keep it secret', 'to guess wildly', 'to ask a question'],
      },
      {
        word: 'wonder',
        meaning: 'to think about something you do not know yet',
        cloze: 'I ____ how far away that star is.',
        decoys: ['to be certain already', 'to stop thinking', 'to run in circles'],
      },
      {
        word: 'decide',
        meaning: 'to choose what you are going to do',
        cloze: 'You get to ____ which book we read.',
        decoys: ['to leave it to chance', 'to change nothing', 'to lose something'],
      },
    ],
  },
  {
    id: 'g1_vocab_10',
    grade: 1,
    title: 'Time Words',
    blurb: 'Words for when things happen.',
    minutes: 11,
    words: [
      {
        word: 'suddenly',
        meaning: 'happening fast and without warning',
        cloze: '____, the lights went out.',
        decoys: ['very slowly over years', 'every single day', 'never at all'],
      },
      {
        word: 'often',
        meaning: 'many times, again and again',
        cloze: 'We ____ walk to the park after dinner.',
        decoys: ['only one time ever', 'never', 'a long time ago'],
      },
      {
        word: 'finally',
        meaning: 'at last, after waiting',
        cloze: 'On day six the seed ____ sprouted.',
        decoys: ['right at the beginning', 'before anything else', 'by accident'],
      },
      {
        word: 'meanwhile',
        meaning: 'at the same time as something else',
        cloze: 'She read a book. ____, her sister drew a picture.',
        decoys: ['much later that year', 'before she was born', 'instead of that'],
      },
      {
        word: 'ancient',
        meaning: 'from a very, very long time ago',
        cloze: 'The light from that star is ____.',
        decoys: ['brand new today', 'happening right now', 'still to come'],
      },
      {
        word: 'moment',
        meaning: 'a very short piece of time',
        cloze: 'Wait here for a ____, please.',
        decoys: ['a whole year', 'a hundred days', 'the rest of your life'],
      },
    ],
  },
  {
    id: 'g1_vocab_11',
    grade: 1,
    title: 'Water Words',
    blurb: 'Words about water and the things it does.',
    minutes: 11,
    words: [
      {
        word: 'splash',
        meaning: 'to throw water around with noise and movement',
        cloze: 'The kids ____ in the puddle.',
        decoys: ['sit very still', 'sleep deeply', 'whisper quietly'],
      },
      {
        word: 'stream',
        meaning: 'water running down a hill or path',
        cloze: 'We found a small ____ in the woods.',
        decoys: ['a tall mountain', 'a bright light', 'a loud noise'],
      },
      {
        word: 'drip',
        meaning: 'drops of liquid falling one at a time',
        cloze: 'The faucet made a ____ sound.',
        decoys: ['a crash', 'a bang', 'silence'],
      },
      {
        word: 'waves',
        meaning: 'moving water on the surface of the ocean',
        cloze: 'The ____ knocked me down at the beach.',
        decoys: ['sand on the shore', 'rocks in the path', 'the hot sun'],
      },
      {
        word: 'float',
        meaning: 'to stay on top of water',
        cloze: 'The leaf will ____ down the stream.',
        decoys: ['sink to the bottom', 'disappear', 'dry up'],
      },
      {
        word: 'frozen',
        meaning: 'turned into ice, very hard from cold',
        cloze: 'In winter the pond is ____.',
        decoys: ['very warm', 'moving fast', 'full of fish'],
      },
    ],
  },
  {
    id: 'g1_vocab_12',
    grade: 1,
    title: 'Movement Words',
    blurb: 'Words for how things move.',
    minutes: 11,
    words: [
      {
        word: 'glide',
        meaning: 'to move smooth and easy',
        cloze: 'The bird will ____ through the air.',
        decoys: ['jump up and down', 'fall straight down', 'stay in one place'],
      },
      {
        word: 'tumble',
        meaning: 'to fall and roll',
        cloze: 'He will ____ down the hill.',
        decoys: ['climb up slowly', 'stand still', 'fly away'],
      },
      {
        word: 'dart',
        meaning: 'to move fast and quick',
        cloze: 'The fish will ____ away.',
        decoys: ['swim slowly', 'stay put', 'turn around'],
      },
      {
        word: 'crawl',
        meaning: 'to move on your hands and knees',
        cloze: 'The baby will ____ across the floor.',
        decoys: ['stand up tall', 'jump high', 'run fast'],
      },
      {
        word: 'sway',
        meaning: 'to move back and forth gently',
        cloze: 'The trees will ____ in the wind.',
        decoys: ['stand still', 'fall down', 'grow taller'],
      },
      {
        word: 'soar',
        meaning: 'to fly high in the sky',
        cloze: 'The eagle will ____ above us.',
        decoys: ['land on the ground', 'hide in a nest', 'stay in one place'],
      },
    ],
  },
  {
    id: 'g1_vocab_13',
    grade: 1,
    title: 'Nature Words',
    blurb: 'Words for things in the world.',
    minutes: 11,
    words: [
      {
        word: 'blossom',
        meaning: 'a pretty flower on a tree or plant',
        cloze: 'The cherry tree had pink ____.',
        decoys: ['green leaves', 'brown bark', 'dark roots'],
      },
      {
        word: 'meadow',
        meaning: 'a field of grass and flowers',
        cloze: 'We ran through the ____.',
        decoys: ['deep forest', 'rocky mountain', 'sandy beach'],
      },
      {
        word: 'moss',
        meaning: 'soft green plant that grows on rocks and trees',
        cloze: 'The rock was covered in ____.',
        decoys: ['sharp thorns', 'sticky sap', 'hard dust'],
      },
      {
        word: 'coral',
        meaning: 'colorful plants and animals that live in the ocean',
        cloze: 'Fish swim around the ____.',
        decoys: ['sandy beach', 'icy glacier', 'muddy swamp'],
      },
      {
        word: 'burrow',
        meaning: 'a hole in the ground where an animal lives',
        cloze: 'The rabbit went into its ____.',
        decoys: ['bird\'s nest', 'beaver\'s dam', 'fox\'s den'],
      },
      {
        word: 'pebble',
        meaning: 'a small smooth stone',
        cloze: 'I found a pretty ____ at the beach.',
        decoys: ['grain of sand', 'piece of shell', 'smooth rock'],
      },
    ],
  },
  {
    id: 'g1_vocab_14',
    grade: 1,
    title: 'Sound Words',
    blurb: 'Words for the things we hear.',
    minutes: 11,
    words: [
      {
        word: 'whisper',
        meaning: 'to speak very softly',
        cloze: 'She will ____ so no one else hears.',
        decoys: ['shout loudly', 'sing a song', 'stay quiet'],
      },
      {
        word: 'crackle',
        meaning: 'to make a sound like small breaking sounds',
        cloze: 'The fire will ____ as it burns.',
        decoys: ['roar loudly', 'fade away', 'pop once'],
      },
      {
        word: 'chime',
        meaning: 'to ring like a bell',
        cloze: 'The clock will ____ at noon.',
        decoys: ['tick slowly', 'buzz loudly', 'hum quietly'],
      },
      {
        word: 'rustle',
        meaning: 'to make a soft whispering sound',
        cloze: 'The leaves will ____ in the wind.',
        decoys: ['crack and break', 'crash down', 'stay silent'],
      },
      {
        word: 'echo',
        meaning: 'a sound bouncing back to you',
        cloze: 'Shout in the cave and hear an ____.',
        decoys: ['whisper', 'music', 'silence'],
      },
      {
        word: 'melody',
        meaning: 'a pretty sequence of musical notes',
        cloze: 'The bird sang a beautiful ____.',
        decoys: ['loud noise', 'sad sound', 'quiet word'],
      },
    ],
  },
  {
    id: 'g1_vocab_15',
    grade: 1,
    title: 'Texture Words',
    blurb: 'Words for how things feel.',
    minutes: 11,
    words: [
      {
        word: 'velvet',
        meaning: 'soft and smooth cloth',
        cloze: 'The ribbon was made of ____.',
        decoys: ['rough burlap', 'scratchy wool', 'stiff plastic'],
      },
      {
        word: 'gritty',
        meaning: 'having tiny rough bits on it',
        cloze: 'The beach sand is ____.',
        decoys: ['smooth and slippery', 'soft and fluffy', 'wet and muddy'],
      },
      {
        word: 'brittle',
        meaning: 'hard but easy to break',
        cloze: 'The thin ice is ____.',
        decoys: ['thick and strong', 'soft and squeezy', 'wet and stretchy'],
      },
      {
        word: 'plush',
        meaning: 'very soft and thick',
        cloze: 'The carpet is ____.',
        decoys: ['thin and scratchy', 'hard and cold', 'bumpy and rough'],
      },
      {
        word: 'rubbery',
        meaning: 'bouncy and flexible like rubber',
        cloze: 'The eraser is ____.',
        decoys: ['hard and stiff', 'sharp and pointy', 'wet and drippy'],
      },
      {
        word: 'bumpy',
        meaning: 'having raised parts on the surface',
        cloze: 'The toad\'s skin is ____.',
        decoys: ['smooth and sleek', 'soft and furry', 'wet and slippery'],
      },
    ],
  },
  {
    id: 'g1_vocab_16',
    grade: 1,
    title: 'Color Words',
    blurb: 'More words for the colors we see.',
    minutes: 11,
    words: [
      {
        word: 'scarlet',
        meaning: 'a bright red',
        cloze: 'She wore a ____ dress.',
        decoys: ['pale pink', 'dark purple', 'light yellow'],
      },
      {
        word: 'burgundy',
        meaning: 'a dark reddish-brown',
        cloze: 'His jacket was ____.',
        decoys: ['bright orange', 'light tan', 'navy blue'],
      },
      {
        word: 'turquoise',
        meaning: 'a blue-green color',
        cloze: 'The water was ____.',
        decoys: ['deep purple', 'yellow-green', 'gray-white'],
      },
      {
        word: 'amber',
        meaning: 'a golden-orange color',
        cloze: 'The light was ____.',
        decoys: ['bright white', 'deep red', 'dark gray'],
      },
      {
        word: 'ebony',
        meaning: 'a deep black',
        cloze: 'The night was ____.',
        decoys: ['dark blue', 'dark purple', 'dark green'],
      },
      {
        word: 'ivory',
        meaning: 'a cream or off-white color',
        cloze: 'The piano keys are ____.',
        decoys: ['jet black', 'pure white', 'pale yellow'],
      },
    ],
  },
  {
    id: 'g1_vocab_17',
    grade: 1,
    title: 'Size Words',
    blurb: 'Words for different sizes.',
    minutes: 11,
    words: [
      {
        word: 'miniature',
        meaning: 'very, very small',
        cloze: 'She had a ____ toy house.',
        decoys: ['giant-sized', 'full-sized', 'normal-sized'],
      },
      {
        word: 'petite',
        meaning: 'small and delicate',
        cloze: 'She is a ____ girl.',
        decoys: ['tall and strong', 'large and wide', 'average-sized'],
      },
      {
        word: 'colossal',
        meaning: 'huge and enormous',
        cloze: 'The dinosaur was ____.',
        decoys: ['small and tiny', 'average-sized', 'medium-built'],
      },
      {
        word: 'vast',
        meaning: 'very, very large',
        cloze: 'The ocean is ____.',
        decoys: ['shallow and small', 'narrow and tight', 'shallow and calm'],
      },
      {
        word: 'microscopic',
        meaning: 'so small you need a microscope to see',
        cloze: 'Germs are ____.',
        decoys: ['big and visible', 'medium-sized', 'very small but visible'],
      },
      {
        word: 'slender',
        meaning: 'thin and graceful',
        cloze: 'The graceful dancer was ____.',
        decoys: ['big and bulky', 'short and round', 'tall and thick'],
      },
    ],
  },
  {
    id: 'g1_vocab_18',
    grade: 1,
    title: 'Taste and Smell Words',
    blurb: 'Words for flavors and scents.',
    minutes: 11,
    words: [
      {
        word: 'tangy',
        meaning: 'sharp and slightly sour taste',
        cloze: 'The lemon was ____.',
        decoys: ['sweet', 'bitter', 'salty'],
      },
      {
        word: 'savory',
        meaning: 'having a nice salty taste',
        cloze: 'The soup was ____.',
        decoys: ['sweet', 'sour', 'bitter'],
      },
      {
        word: 'bland',
        meaning: 'having no strong taste',
        cloze: 'The plain rice was ____.',
        decoys: ['spicy', 'sweet', 'salty'],
      },
      {
        word: 'fragrant',
        meaning: 'having a nice smell',
        cloze: 'The flowers were ____.',
        decoys: ['stinky', 'invisible', 'soft'],
      },
      {
        word: 'aromatic',
        meaning: 'having a strong nice smell',
        cloze: 'The bread is ____.',
        decoys: ['sour', 'hard', 'cold'],
      },
      {
        word: 'pungent',
        meaning: 'having a strong sharp smell',
        cloze: 'The onion is ____.',
        decoys: ['sweet-smelling', 'soft', 'cold'],
      },
    ],
  },
  {
    id: 'g1_vocab_19',
    grade: 1,
    title: 'Thinking Words',
    blurb: 'Words for using your brain.',
    minutes: 11,
    words: [
      {
        word: 'wonder',
        meaning: 'to ask yourself about something',
        cloze: 'I ____ what is inside the box.',
        decoys: ['to know for sure', 'to forget', 'to look away'],
      },
      {
        word: 'notice',
        meaning: 'to see something and pay attention to it',
        cloze: 'Did you ____ the new picture on the wall?',
        decoys: ['to walk past', 'to close your eyes', 'to forget'],
      },
      {
        word: 'guess',
        meaning: 'to say an answer you are not sure about',
        cloze: 'Can you ____ what animal I am thinking of?',
        decoys: ['to know for sure', 'to write it down', 'to say nothing'],
      },
      {
        word: 'remember',
        meaning: 'to keep something in your mind',
        cloze: 'I ____ my first day of school.',
        decoys: ['to forget', 'to lose', 'to hide'],
      },
      {
        word: 'imagine',
        meaning: 'to make a picture in your mind',
        cloze: '____ you could fly like a bird.',
        decoys: ['to see with your eyes', 'to touch', 'to hear'],
      },
      {
        word: 'decide',
        meaning: 'to make up your mind about something',
        cloze: 'I cannot ____ which book to read first.',
        decoys: ['to ask someone else', 'to forget about it', 'to wait forever'],
      },
    ],
  },
  {
    id: 'g1_vocab_20',
    grade: 1,
    title: 'Friend Words',
    blurb: 'Words for being with others.',
    minutes: 11,
    words: [
      {
        word: 'invite',
        meaning: 'to ask someone to come',
        cloze: 'I will ____ her to my party.',
        decoys: ['to send away', 'to hide from', 'to forget'],
      },
      {
        word: 'welcome',
        meaning: 'to greet someone in a kind way',
        cloze: 'We ____ the new girl to our class.',
        decoys: ['to ignore', 'to chase away', 'to laugh at'],
      },
      {
        word: 'include',
        meaning: 'to let someone join in',
        cloze: 'Always ____ everyone in the game.',
        decoys: ['to leave out', 'to pick last', 'to play alone'],
      },
      {
        word: 'comfort',
        meaning: 'to help someone feel better',
        cloze: 'She gave her friend a hug to ____ her.',
        decoys: ['to make someone cry', 'to walk away', 'to be loud'],
      },
      {
        word: 'trust',
        meaning: 'to believe someone will do what they say',
        cloze: 'I ____ you to keep my secret.',
        decoys: ['to doubt', 'to check on', 'to follow'],
      },
      {
        word: 'forgive',
        meaning: 'to stop being upset with someone who said sorry',
        cloze: 'He said sorry, so I chose to ____ him.',
        decoys: ['to stay angry', 'to tell everyone', 'to run away'],
      },
    ],
  },
  {
    id: 'g1_vocab_21',
    grade: 1,
    title: 'Adventure Words',
    blurb: 'Words for exciting journeys.',
    minutes: 11,
    words: [
      {
        word: 'explore',
        meaning: 'to look around a new place',
        cloze: 'We went to ____ the woods behind the house.',
        decoys: ['to stay home', 'to sleep', 'to hide'],
      },
      {
        word: 'discover',
        meaning: 'to find something for the first time',
        cloze: 'Did you ____ the hidden door?',
        decoys: ['to lose', 'to cover up', 'to walk past'],
      },
      {
        word: 'journey',
        meaning: 'a long trip from one place to another',
        cloze: 'The ____ to the mountains took all day.',
        decoys: ['a short nap', 'a small snack', 'a quiet room'],
      },
      {
        word: 'treasure',
        meaning: 'something special and worth a lot',
        cloze: 'The map showed where the ____ was buried.',
        decoys: ['a pile of trash', 'an empty box', 'a plain rock'],
      },
      {
        word: 'brave',
        meaning: 'doing something even when you feel afraid',
        cloze: 'The ____ girl crossed the wobbly bridge.',
        decoys: ['too scared to try', 'very sleepy', 'very hungry'],
      },
      {
        word: 'path',
        meaning: 'a small trail you can walk along',
        cloze: 'Follow the ____ through the garden.',
        decoys: ['a big highway', 'a deep river', 'a tall wall'],
      },
    ],
  },
  {
    id: 'g1_vocab_22',
    grade: 1,
    title: 'Story Words',
    blurb: 'Words that make stories magical.',
    minutes: 11,
    words: [
      {
        word: 'castle',
        meaning: 'a big strong building where kings and queens live',
        cloze: 'The queen lived in a stone ____.',
        decoys: ['a small tent', 'a tree house', 'a little boat'],
      },
      {
        word: 'dragon',
        meaning: 'a big storybook animal that can breathe fire',
        cloze: 'The ____ flew over the mountain.',
        decoys: ['a tiny mouse', 'a slow turtle', 'a soft kitten'],
      },
      {
        word: 'magic',
        meaning: 'special powers in stories that make amazing things happen',
        cloze: 'The fairy used ____ to make the flowers glow.',
        decoys: ['hard work', 'loud noise', 'good luck'],
      },
      {
        word: 'hero',
        meaning: 'someone who does something brave to help others',
        cloze: 'The ____ saved the village.',
        decoys: ['someone who runs away', 'someone who sleeps', 'someone who watches'],
      },
      {
        word: 'wish',
        meaning: 'something you want very much to happen',
        cloze: 'She made a ____ on the first star.',
        decoys: ['a bad dream', 'a loud yell', 'a long list'],
      },
      {
        word: 'ending',
        meaning: 'the last part of a story',
        cloze: 'My favorite part was the happy ____.',
        decoys: ['the first page', 'the cover', 'the middle'],
      },
    ],
  },
  {
    id: 'g1_vocab_23',
    grade: 1,
    title: 'Kind Words',
    blurb: 'Words for nice things we do.',
    minutes: 11,
    words: [
      {
        word: 'helpful',
        meaning: 'doing things that make it easier for others',
        cloze: 'It was ____ of you to carry the bags.',
        decoys: ['making things harder', 'being loud', 'being fast'],
      },
      {
        word: 'polite',
        meaning: 'using kind words and good manners',
        cloze: 'It is ____ to say please and thank you.',
        decoys: ['rude and loud', 'fast and busy', 'quiet and sleepy'],
      },
      {
        word: 'generous',
        meaning: 'happy to share what you have',
        cloze: 'She was ____ and gave half her snack away.',
        decoys: ['keeping everything', 'being hungry', 'being first'],
      },
      {
        word: 'patient',
        meaning: 'able to wait without getting upset',
        cloze: 'Be ____ — the cookies are almost done.',
        decoys: ['in a big hurry', 'very upset', 'very loud'],
      },
      {
        word: 'honest',
        meaning: 'telling the truth',
        cloze: 'He was ____ and said he broke the cup.',
        decoys: ['telling lies', 'staying quiet', 'blaming others'],
      },
      {
        word: 'caring',
        meaning: 'showing you want others to be okay',
        cloze: 'The ____ nurse checked on me all night.',
        decoys: ['not noticing others', 'being busy', 'being far away'],
      },
    ],
  },
  {
    id: 'g1_vocab_24',
    grade: 1,
    title: 'Wonder Words',
    blurb: 'Words for amazing things.',
    minutes: 11,
    words: [
      {
        word: 'amazing',
        meaning: 'so good it surprises you',
        cloze: 'The fireworks were ____.',
        decoys: ['very boring', 'very small', 'hard to hear'],
      },
      {
        word: 'sparkle',
        meaning: 'to shine with little flashes of light',
        cloze: 'The snow began to ____ in the sun.',
        decoys: ['to melt away', 'to turn dark', 'to get dirty'],
      },
      {
        word: 'glow',
        meaning: 'to give off a soft warm light',
        cloze: 'The nightlight has a gentle ____.',
        decoys: ['a loud sound', 'a cold wind', 'a bad smell'],
      },
      {
        word: 'giant',
        meaning: 'very, very big',
        cloze: 'A ____ pumpkin grew in the garden.',
        decoys: ['very tiny', 'very quiet', 'very soft'],
      },
      {
        word: 'beautiful',
        meaning: 'very nice to look at',
        cloze: 'The rainbow was ____.',
        decoys: ['hard to see', 'very loud', 'very fast'],
      },
      {
        word: 'surprise',
        meaning: 'something you did not know was coming',
        cloze: 'The party was a big ____.',
        decoys: ['a plan you made', 'a daily chore', 'a school rule'],
      },
    ],
  },
  {
    id: 'g1_vocab_25',
    grade: 1,
    title: 'Brave Words',
    blurb: 'Words for being brave.',
    minutes: 11,
    words: [
      {
        word: 'courage',
        meaning: 'the strength to do something scary',
        cloze: 'It took ____ to sing in front of everyone.',
        decoys: ['a long nap', 'a big lunch', 'a new toy'],
      },
      {
        word: 'try',
        meaning: 'to give something your best effort',
        cloze: 'I will ____ to ride without training wheels.',
        decoys: ['to give up', 'to watch others', 'to wait'],
      },
      {
        word: 'practice',
        meaning: 'to do something again and again to get better',
        cloze: 'She does piano ____ every day.',
        decoys: ['doing it once', 'skipping it', 'watching TV'],
      },
      {
        word: 'strong',
        meaning: 'having a lot of power in your body or heart',
        cloze: 'The ____ horse pulled the heavy cart.',
        decoys: ['very weak', 'very sleepy', 'very small'],
      },
      {
        word: 'protect',
        meaning: 'to keep someone or something safe',
        cloze: 'The mother bird will ____ her eggs.',
        decoys: ['to leave behind', 'to give away', 'to forget'],
      },
      {
        word: 'rescue',
        meaning: 'to save someone from danger',
        cloze: 'The firefighter came to ____ the cat.',
        decoys: ['to leave alone', 'to watch', 'to call'],
      },
    ],
  },
  {
    id: 'g1_vocab_26',
    grade: 1,
    title: 'Dream Words',
    blurb: 'Words for hopes and goals.',
    minutes: 11,
    words: [
      {
        word: 'hope',
        meaning: 'wanting something good to happen',
        cloze: 'I ____ it snows tomorrow.',
        decoys: ['to be sure it will not', 'to forget', 'to be afraid'],
      },
      {
        word: 'dream',
        meaning: 'a big wish for your life',
        cloze: 'Her ____ is to be a vet someday.',
        decoys: ['a chore to do', 'a rule to follow', 'a food to eat'],
      },
      {
        word: 'goal',
        meaning: 'something you work hard to reach',
        cloze: 'My ____ is to read ten books this year.',
        decoys: ['an accident', 'a mistake', 'a game'],
      },
      {
        word: 'plan',
        meaning: 'the steps you will take to do something',
        cloze: 'We made a ____ for the lemonade stand.',
        decoys: ['a big mess', 'a long nap', 'a surprise'],
      },
      {
        word: 'someday',
        meaning: 'at a time in the future',
        cloze: '____ I will visit the ocean.',
        decoys: ['yesterday', 'never', 'right now'],
      },
      {
        word: 'grow',
        meaning: 'to get bigger or better over time',
        cloze: 'Keep practicing and your skills will ____.',
        decoys: ['to shrink', 'to stop', 'to hide'],
      },
    ],
  },
  {
    id: 'g1_vocab_27',
    grade: 1,
    title: 'Change Words',
    blurb: 'Words for when things become different.',
    minutes: 11,
    words: [
      {
        word: 'change',
        meaning: 'to become different',
        cloze: 'The leaves ____ color in the fall.',
        decoys: ['to stay the same', 'to disappear', 'to freeze'],
      },
      {
        word: 'melt',
        meaning: 'to turn from solid to liquid when warm',
        cloze: 'The ice cream started to ____ in the sun.',
        decoys: ['to freeze harder', 'to grow bigger', 'to change color'],
      },
      {
        word: 'hatch',
        meaning: 'to break out of an egg',
        cloze: 'The chick will ____ soon.',
        decoys: ['to fly away', 'to fall asleep', 'to swim'],
      },
      {
        word: 'bloom',
        meaning: 'when a flower opens up',
        cloze: 'The roses ____ in the spring.',
        decoys: ['to close up', 'to fall down', 'to turn brown'],
      },
      {
        word: 'repair',
        meaning: 'to fix something that is broken',
        cloze: 'Dad will ____ the wheel on my bike.',
        decoys: ['to break more', 'to throw away', 'to hide'],
      },
      {
        word: 'become',
        meaning: 'to turn into something',
        cloze: 'A caterpillar will ____ a butterfly.',
        decoys: ['to stay as', 'to run from', 'to eat'],
      },
    ],
  },
  {
    id: 'g1_vocab_28',
    grade: 1,
    title: 'Calm Words',
    blurb: 'Words for peaceful and quiet.',
    minutes: 11,
    words: [
      {
        word: 'calm',
        meaning: 'quiet and peaceful, not worried',
        cloze: 'The lake was ____ in the morning.',
        decoys: ['wild and stormy', 'loud and busy', 'fast and bumpy'],
      },
      {
        word: 'rest',
        meaning: 'to stop and relax your body',
        cloze: 'After the hike we sat down to ____.',
        decoys: ['to run more', 'to jump', 'to shout'],
      },
      {
        word: 'cozy',
        meaning: 'warm, soft, and comfortable',
        cloze: 'I read under a ____ blanket.',
        decoys: ['cold and wet', 'hard and rough', 'big and empty'],
      },
      {
        word: 'peaceful',
        meaning: 'quiet and without any trouble',
        cloze: 'The garden was ____ at sunset.',
        decoys: ['full of noise', 'full of people', 'full of cars'],
      },
      {
        word: 'relax',
        meaning: 'to let your body and mind rest',
        cloze: 'Take a deep breath and ____.',
        decoys: ['to hurry up', 'to worry', 'to work hard'],
      },
      {
        word: 'quiet',
        meaning: 'making very little sound',
        cloze: 'The library is a ____ place.',
        decoys: ['very loud', 'very bright', 'very cold'],
      },
    ],
  },
  {
    id: 'g1_vocab_29',
    grade: 1,
    title: 'Learning Words',
    blurb: 'Words about how we grow smarter.',
    minutes: 11,
    words: [
      {
        word: 'learn',
        meaning: 'to find out how to do something new',
        cloze: 'I want to ____ how to swim.',
        decoys: ['to forget', 'to skip', 'to watch only'],
      },
      {
        word: 'teach',
        meaning: 'to help someone else learn',
        cloze: 'Will you ____ me that card game?',
        decoys: ['to hide from', 'to test', 'to race'],
      },
      {
        word: 'question',
        meaning: 'something you ask when you want to know',
        cloze: 'Raise your hand if you have a ____.',
        decoys: ['an answer', 'a snack', 'a picture'],
      },
      {
        word: 'answer',
        meaning: 'what you say back to a question',
        cloze: 'She knew the ____ right away.',
        decoys: ['the question', 'the problem', 'the page'],
      },
      {
        word: 'mistake',
        meaning: 'something you get wrong by accident',
        cloze: 'A ____ is a chance to learn.',
        decoys: ['a prize', 'a plan', 'a rule'],
      },
      {
        word: 'improve',
        meaning: 'to get better at something',
        cloze: 'Practice helps you ____.',
        decoys: ['to get worse', 'to stay the same', 'to stop'],
      },
    ],
  },
  {
    id: 'g1_vocab_30',
    grade: 1,
    title: 'Happy Words',
    blurb: 'Our last vocabulary star celebrates happiness.',
    minutes: 11,
    words: [
      {
        word: 'cheerful',
        meaning: 'happy and full of smiles',
        cloze: 'The ____ song made everyone dance.',
        decoys: ['sad and slow', 'quiet and dark', 'angry and loud'],
      },
      {
        word: 'giggle',
        meaning: 'to laugh in a light, silly way',
        cloze: 'The joke made her ____.',
        decoys: ['to cry', 'to yawn', 'to frown'],
      },
      {
        word: 'delighted',
        meaning: 'very, very pleased',
        cloze: 'She was ____ with her new puppy.',
        decoys: ['very upset', 'very bored', 'very sleepy'],
      },
      {
        word: 'celebrate',
        meaning: 'to do something special for a happy day',
        cloze: 'We ____ birthdays with cake.',
        decoys: ['to forget', 'to sleep through', 'to work through'],
      },
      {
        word: 'smile',
        meaning: 'the happy shape your mouth makes',
        cloze: 'Her ____ lit up the room.',
        decoys: ['her frown', 'her tears', 'her yawn'],
      },
      {
        word: 'thankful',
        meaning: 'glad for the good things you have',
        cloze: 'I am ____ for my family.',
        decoys: ['upset about', 'bored with', 'confused by'],
      },
    ],
  },
];

export const grade1Vocabulary: Star[] = specs.map(buildVocabStar);
